### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by roshavagarga** [florisboard/florisboard#1]
Hello,

Will this app be available via F-Droid at any point?

**Comment by patrickgold** [comment]
I am definitely considering putting FlorisBoard on F-Droid. While I do not have a exact timeline for this, I plan to do it for the 0.2.0 version (0.1.0 is the first public alpha test on PlayStore).

**Comment by roshavagarga** [comment]
Awesome. When implementing dictionaries may I suggest looking at [openboard's](https://github.com/dslul/openboard/)? Thanks for the app :)

**Comment by patrickgold** [comment]
Thanks for the dictionary suggestion, I will definitely look into that when implementing this feature.

**Comment by patrickgold** [comment]
Note that I reopened the issue as it isn't resolved yet (I will close this issue when FlorisBoard is available on F-Droid).

**Comment by IzzySoft** [comment]
In about 21h from now (with the next regular sync), *FlorisBoard* will become available [in my repo](https://apt.izzysoft.de/fdroid/index/apk/dev.patrickgold.florisboard) – hope that's fine with you, Patrick: it's the first stage for many apps on their way to F-Droid. I've just added it, and my scanner confirms it seems well suited for "F-Droid proper" – no proprietary libs etc, which is very good!

I took the freedom to re-format your `full_description.txt` files (you will see the results once the listing is online tomorrow), and gladly offer them back to you – just let me know if you prefer a PR or "simple quote here". It would be a great idea to also add per-release changelogs to Fastlane; be welcome to let [my cheat-sheet](https://gitlab.com/snippets/1895688) guide you. Fastlane will be used by F-Droid, and my repo will also fetch "specified files" from there with each new release (currently icon, featureGraphic, screenshots, title and shortdesc – fulldesc requires some reformatting to "look good", so I'd enable that when you accept my contribution).

<sub>Disclosure: I'm also one of the F-Droid maintainers – so we'll meet again when you started the inclusion process there :wink:</sub>

**Comment by patrickgold** [comment]
Thank you IzzySoft for your work, I'm honored to see FlorisBoard in your repo! Its great to hear that your scan reported no proprietary libs etc., as this aspect was always important for me while developing FlorisBoard.

Regarding the reformatting of `full_description.txt`: it would be the best if you made a PR, so your changes are included in the commit history and you appear in the contribution panel of FlorisBoard. Tomorrow afternoon I will work on adding the changelogs to the fastlane directory (beginning with the 0.1.0 version, as this was the first 'public' alpha release).

Thanks again for your contribution and I'm looking forward to meet you again in the F-Droid inclusion process! :)

**Comment by IzzySoft** [comment]
Thanks for your fast response!

PR on its way (apologies: I forgot to create a separate branch first – I was too confused about the 20 "modifications" right after cloning :rofl:)

As for changelogs: It fully suffices starting with the latest – F-Droid currently supports only that. Just send me a ping when it's there, so I update my configuration to pull it when you make a new release.

Glad to read your high opinion of my repo – now it's me feeling honored! And yes, looking forward to see your application "over at F-Droid" then, whenever you feel ready. Once listed there, you have the option to use my repo for pre-releases/testing – or let me drop the app again after everything looks fine at F-Droid (most devs decide for the latter, maybe 5% for the former), whatever suits you best.

Oh: if you want to link to your app in my repo, be welcome to [use this badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) :smiley:

**Comment by patrickgold** [comment]
Thank you for your PR, I've just merged it into the master branch. I've also added the changelog for the latest version 0.2.0 (12) into the fastlane directory.

I'll also later this evening update my README.md to include a link to FlorisBoard in your repo using the provided badge!

**Comment by IzzySoft** [comment]
Thanks a lot, Patrick! I've just updated the metadata on my end, so my updater now also fetches fulldesc & changelog on each new release (so all changes should automatically be reflected in my repo). Also thanks for adding the badge, looks great there :smile:

Should you later add more files to fastlane which you want to be picked up (e.g. `video.txt`), please let me know so I take care for them to be picked up, too.

**Comment by TPS** [comment]
@patrickgold Just curious as _why_ you wish to delay the RFP to include this in F-Droid proper (thanks 🙇🏾‍♂️ @IzzySoft for including in _your_ repo), as it usually takes quite a bit of time (often _months_) before such actually makes it to the main repo.  (Thankfully, updates to _existing_ apps usually take only around a week or so.)

I figure, if you wish, I could put the RFP in now _while_ you're on the parallel track to achieve v0.2, &, ideally, this'll hit the repo around that time.

**Comment by patrickgold** [comment]
@TPS As this is my first app which I want to publish, I am entering fully new territory here when it comes to Google Play and F-Droid, so I want to make it right and not rush things. My thoughts on why I was delaying the proper F-Droid release were that I want to ship FlorisBoard in a state where it has at least a handful of fully functional features and not having almost every option with a _NYI_ flag. FlorisBoard in its current state already has some fully functional features, but personally I wanted either Gestures or Composing Suggestions before I released it to F-Droid. I decided for the former, which will be v0.3.0 (probably with sub versions v0.2.1 and v0.2.2 in between), so may plan was that I begin with the inclusion process around v0.2.2.

What I never thought of tbh is that the RFP can take months before it actually lands in F-Droid proper, which led me to the decision that I will put in the RFP now and continue with development in parallel. Thanks for your suggestion!

**Comment by IzzySoft** [comment]
The idea to put apps into my repo even if they already have an RFP open is exactly that: making them available immediately, as one can never tell how long the inclusion process might take. And I'd agree here with Patrick if he first wants to reach a "stable state" to not scare away potential new users with a "not-yet-fully-ready" app (my repo is known to cater some testing/alpha apps as well, so people are at least a bit aware of that).

Unfortunately, there's no way to "calculate" how long an RFP might take. If you want to start it earlier in advance, we always can "hold it back" by not applying the "ready" label (so at least we know early what the bot says). Additionally, you could have a note in your Fastlane descriptions with a "big warning" (like `<p><b>NOTE:</b> This app is still in an early stage of development…</p>`) which you then can drop if you feel it's "stable" (F-Droid always picks Fastlane from the same tag the app is build from, so that change would be attached to the correct version). In case we're "ready" earlier than expected, we still could push it "upstairs" to the packagers that way, no matter how long it takes them.

**Comment by patrickgold** [comment]
Personally I've planned to release F-Droid with v0.3.0, but in the event the RFP is ready before that and I'm already at v0.2.2, I've no problem going with this version as well, there is no need to hold it back.

Regarding the note in Fastlane, since the beginning I've had the note "Currently in alpha stage" in the short description to remind potential users that FlorisBoard is in an alpha state. Beginning with v0.4.0 it will say beta instead of alpha. Only with v1.0.0 (which is a looong way) this note will fully disappear.

**Comment by IzzySoft** [comment]
Exactly. And it's fully in your hands, thanks to Fastlane structures :smiley:

I'll start to work on your RFP as soon as the bot had its word(s).

**Comment by TPS** [comment]
For the record (& anyone _else_ following along 😉), the RFP's @ https://gitlab.com/fdroid/rfp/-/issues/1516.

**Comment by TPS** [comment]
> I'll start to work on your RFP as soon as the bot had its word(s).

@IzzySoft The bot's just [processed the RFP](https://gitlab.com/fdroid/rfp/-/issues/1516#note_427822958).

**Comment by IzzySoft** [comment]
Guess who was faster to tell me? The bot already sent me a notification :smiley: I already reviewed it, complemented the metadata (thanks to Patrick, I just needed to add the initial build section), and marked it for our packagers. That went well!

**Comment by patrickgold** [comment]
FlorisBoard has made it to the main F-Droid repo, hurrah! 🚀 Meta data merge for reference: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/8043. It should be available in about a week or so. Thanks everybody in here for the help and advice given, I really appreciate it! I will now close this issue, as the original intent of this issue is fulfilled.

@IzzySoft especially to you many many thanks as you've hosted FlorisBoard in your own F-Droid repo, which allowed me to bridge the rfp-process time and ship FlorisBoard way earlier, I really appreciate this! :)
One question: what should I do if any of the meta data changes sometime in the future? Like for instance if FlorisBoard gets a proper promotion web page instead of this GitHub repo README.md or if the translation link changes?

**Comment by IzzySoft** [comment]
First congrats for completing the process! It was a honor for me having done the review + merge as well as having hosted FlorisBoard in my repo (speaking of which: do you want me to keep it there once it shows up at F-Droid? Usually I remove apps after about a week's overlap, unless explicitly requested otherwise; [see here](https://gitlab.com/IzzyOnDroid/repo/-/wikis/FAQ) for some background).

As for metadata updates: what can be done via Fastlane will be pulled automatically with each release. Change of things fixed into our YAML metadata require a merge request to be updated/added/removed (like the website URL you mentioned, or donation links, Bitcoin/Litecoin address etc).

**Comment by patrickgold** [comment]
Thanks for your response!

I think it would be best if you remove FlorisBoard after a week's overlap, as I provide only one release track (main), and that will be shipped via F-Droid main now. If I decide sometime in the future that I am beginning to provide two tracks (main + beta), would it be possible that I contact you about having the beta track in your repo again, for users who want to be early testers?

> Change of things fixed into our YAML metadata require a merge request to be updated/added/removed

Ah I see, makes sense!

**Comment by IzzySoft** [comment]
> I think it would be best if you remove FlorisBoard after a week's overlap

Will be done (just added a corresponding note to the metadata on my end).

> would it be possible that I contact you about having the beta track in your repo again

Of course! Find the repo for my repo (ugh) with its issue-tracker [here](https://gitlab.com/IzzyOnDroid/repo). I'd suggest to use a separate package name for the beta then (e.g. `dev.patrickgold.florisboard.beta`) to make it easier to spot/pick and also possible to use while having the release/stable version installed at the same time.

**Comment by patrickgold** [comment]
> Of course! Find the repo for my repo (ugh) with its issue-tracker here (or just ping me from an issue in your repo if you prefer)

Perfect, thank you! :)

> I'd suggest to use a separate package name for the beta then (e.g. dev.patrickgold.florisboard.beta)

That's a great idea. I am already doing this for debug artifact builds (with `.debug` as suffix), so this is easy to set up for me when the time comes.
