### ISSUE TITLE
Not able to check crash.

### ISSUE THREAD

**Issue by Khatri7yash** [florisboard/florisboard#1005]
After changing some classes and solving some errors related to those changes i'm at the point where im not able to check this crash report in device as well as in android studio.... Is there any other way to check this crash report??

This is what popup in android studio while opening the file :
-->> Error opening contents of device file "1623063139059.stacktrace": Error executing shell command run-as

**Comment by patrickgold** [comment]
>  -->> Error opening contents of device file "1623063139059.stacktrace": Error executing shell command run-as

This probably means the crash handler does not write the file correctly and it is corrupted, but not sure. You could try to directly add a temporary logcat statement instead of writing the stacktrace file in the CrashUtility. https://github.com/florisboard/florisboard/blob/37bb4cea43b2cca453a59da3076908c02e9b7224/app/src/main/java/dev/patrickgold/florisboard/crashutility/CrashUtility.kt#L386
