### ISSUE TITLE
Flow typing in non-english (czech) language

### ISSUE THREAD

**Issue by CristianKerr** [florisboard/florisboard#1026]
Hi, 
I have installed the keyboard and It is already amazing! Kudos to that.
My question is: right now only flow typing in english works right? I also set czech keyboard and it does type english words anyway, so I just wonder if it is todo or if I do something wrong. 
Thanks and thanks again for the app, it looks promising!

**Comment by Glitchy-Tozier** [comment]
Hi  :)

You're not doing anything wrong, it's just that development didn't quite make it to non-English languages yet. Be rest assured that adding more languages is on the roadmap, it may take one or two more updates though.

The devellopment-plan for word-suggestions (which are necessary for glide typing) can be found in #352.

**Comment by CristianKerr** [comment]
Hello @Glitchy-Tozier 
thanks for the quick answer! 
Ok I will be very much looking forward to that! 
Fyi I was/am using Chrooma keyboard now because I didn't find anything even remotely as good, but your keyboard is actually on a really good path. I will be even using it instead of chrooma for english. One thing that not a lot keyboards do and do well is manual switching between languages and not mixing them. This is what I am looking forward here most :)

**Comment by Glitchy-Tozier** [comment]
Yeah, Patrick is doing some great work with this keyboard!

Should you have any specific ideas on how to improve FlorisBoard, make sure to post them (after checking that nobody, else has posted your idea already, of course). I'm sure people would be interested to hear what Chrooma does well and how FlorisBoard could improve with these designs. :)

**Comment by CristianKerr** [comment]
Sure, I will go through the road map properly and use it first a while, but then I will add some feature request for sure.

**Comment by Glitchy-Tozier** [comment]
@patrickgold What do you think about also pinning some issue that explains that other languages indeed will be properly supported?

There are quite a few questions regarding suggestions/glide typing in other languages.

**Comment by patrickgold** [comment]
> What do you think about also pinning some issue that explains that other languages indeed will be properly supported?

We could make a frequently asked questions issue, where we lock the conversation to moderators only, pin it and which acts as kind of a collection of different questions around some of the most requested features.

**Comment by Glitchy-Tozier** [comment]
Sounds great!

**Comment by Glitchy-Tozier** [comment]
Btw, this issue can probably be closed.

 Glude-typing will probably be added for all non-english languages all at once.

**Comment by patrickgold** [comment]
> Btw, this issue can probably be closed.

Agree on this one, glide typing improvements are connected with the new implementation of next-word dictionaries and the new implementation will add support for all languages at once, like I did also for the spell checker.

As for the FAQ idea you proposed above: if you want, we can go forward and begin setting it up, as I think it could be beneficial for avoiding some duplicate issues and make some questions also more clear for everyone. Do you want to discuss this topic in this issue or start a new one?

**Comment by Glitchy-Tozier** [comment]
> Do you want to discuss this topic in this issue or start a new one?

Whatever place you prefer :)

I think it should be an issue with a VERY easy title that cuts to the chase right away.

Why? Because most of the FAQ-info already exists in the readme. Imo we're doing this faq for people that don't bother reading the readme or searching for duplicates.

**Comment by patrickgold** [comment]
Ok then lets discuss it here :)

I propose two ideas for the FAQ:

1. A locked down FAQ issue thread, where only collaborators like you and admins can comment and edit the questions. The issue would be titled "Frequently asked questions" and the issue body will initially contain a compiled list of some questions we have seen a lot. After this the FAQ will be updated if we see a new question popping up or if something new is added which could cause some questions.
2. An open FAQ thread titled "Frequently asked questions mega thread" where the issue body is the same as in above idea (locked to admins and collaborators), but everyone is able to comment with a new question which should be added to the FAQ text or if they genuinely have a simple question for FlorisBoard (could reduce the number of question issues a bit).

Either way the issue will of course be pinned (I think the OOM thread will have to make space for the FAQ thread in the pinned issues slots) and we probably should also link to that FAQ issue in every issue template, to ensure most people have seen this before opening a new issue. As for the edit restriction of the FAQ, we can also include other frequent collaborators like @ X-yl to allow editing the FAQ in case some glide typing or clipboard related questions appear.

If you have another idea how to design the FAQ thread I am completely open here :)

As for the initial questions, this are some questions I think I have seen a lot in the past:

- When will other languages than English be supported for glide typing and next word suggestions?
- Will FlorisBoard support stickers and GIFs in the media panel?
- Will FlorisBoard have a recents emoji section in the media panel?
- Why does the adaptive theme feature show weird colors for some apps?
- The delete key randomly hangs after a long press and keeps deleting input until a restart of FlorisBoard
- The delete key gestures do not correctly select the text or delete the text, why?
- Why does Android keep saying "FlorisBoard keeps draining my battery" and how can I fix it?
- Why does F-Droid keep saying "FlorisBoard APK file not found"? (this issue is actually not in my hands but keeps popping up randomly, even for other apps)
- Is there a place where I can share my custom theme with others?
- Why do the clipboard cut/copy buttons seem to do nothing?
- ...

We could also categorize these questions and give each section a header, to sort the questions better, but this depends how many questions we collect over time.

**Comment by Glitchy-Tozier** [comment]
> I propose two ideas for the FAQ:

The first one seems better to me, as the second idea might be redundant (seeing as how question-issues already exists)

> I think the OOM thread will have to make space for the FAQ thread in the pinned issues slots

Absolutely, it should be un-pinned anyway, even if this new FAQ-issue wasn't created.

> If you have another idea how to design the FAQ thread I am completely open here :)

What I initially thought of was something was simpler. Something like the comment I'll post next. Tell me what you think about it!

**Comment by Glitchy-Tozier** [comment]
# Planned features
- Glide typing for all languages
- Spell checking for all languages
- Word suggestions for all languages
- Customizable smart-bar(s)
- Respect capitalization in auto-correct, glide, etc,
- …

**Comment by Glitchy-Tozier** [comment]
Now that I think about it, I feel like a proper FAQ that also contains common bugs might be the better choice.

The main thing (and the most difficult thing) is going to be deciding what to mention and how to structure the bullet points properly.

Maybe it could be 
```
# Bugs
- …

# Features
## Customization
- Customizable smart bar
## Languages
- YES ALL LANGUAGES WILL BE SUPPORTED
```

**Comment by patrickgold** [comment]
Thanks for the detailed idea :) I really like the separation in sections for bugs, features etc., I agree with you that the question tag already exists and allowing comments in the FAQ thread is kinda a redundant thing.

As we are putting a lot of the planned features into the FAQ (rightfully so because it gets asked way too often), should be move the feature roadmap entirely to the FAQ thread (so the FAQ thread is the roadmap and all major known bugs/questions at once?). I am proposing this as else the planned features are kinda duplicate (both in the FAQ and in the readme). The roadmap of course must be designed a bit better and more organized than in the current state in the readme, and especially highlighting that all major languages will be supported for all language related features.

> Now that I think about it, I feel like a proper FAQ that also contains common bugs might be the better choice.

Absolutely! A lot of questions and bug reports are for some specific areas and adding questions and answers that this issue is known and will be fixed sometime in the future is also important for an FAQ.

> The main thing (and the most difficult thing) is going to be deciding what to mention and how to structure the bullet points properly.

Yes that's always hard, especially if it should be easy to find stuff and easy to read through it.

A possible structure could be this:
```
<intro text>

<table of contents for all top-level headings> (kinda quick links if someone wants to directly jump to a certain section)

# Feature roadmap

## Feature 1
- This
- And that
- And that
- And yes ALL MAJOR LANGUAGES ARE SUPPORTED
## Feature 2
- This 
- And that
- and yes the emoji section will definitely get a rework
- ...

# Known issues
- Question 1
  Answer
- Question 2
  Answer
- ...

# Other stuff (don't know how to name this, but this would include all meta-related stuff like app store release, community repo for theme sharing, matrix group chat, etc.
-Theme sharing for community
- Beta release without Google group requirement
- ...
```

> Absolutely, it should be un-pinned anyway, even if this new FAQ-issue wasn't created.

That's true, as OOM isn't a major issue anymore, will do it momentarily.

**Comment by Glitchy-Tozier** [comment]
> and yes the emoji section will definitely get a rework

Forgot about that one, it should definitely be mentioned 😂

> A possible structure could be this:

Looks great.
A few unordered thoughts:

- To make this issue worthwhile, it should be as de-cluttered as possible. I think this is really important.
- I think we can skip the intro-text. Let's choose clear headings (just as a good programmer would name variables well and thus circumvent the need for big blocks of comments)
- I really like the phrasing "known issues"


> Absolutely! A lot of questions and bug reports are for some specific areas and adding questions and answers that this issue is known and will be fixed sometime in the future is also important for an FAQ.

Let's go with a FAQ then!

(I'll comment on the important issues&FRs later on.)

**Comment by patrickgold** [comment]
> Forgot about that one, it should definitely be mentioned joy

That's one thing I get in feedback emails that's more often mentioned than even the next-word suggestions, I guess this is really a thing we should mention at the beginning.

> I think we can skip the intro-text. Let's choose clear headings (just as a good programmer would name variables well and thus circumvent the need for big blocks of comments) and otherwise keep it simple to not scare lazy people into producing duplicates.

I agree, fewer is often times more. Also I kinda noticed I like doing these wall of texts (_cough cough_ App Setup wizard :smile: ), I really need to get away from that and sometimes make things more simple to understand.

> Somehow I really like the phrasing "known issues"

I dunno from which project(s) I have seen this but it just sounds better to the non-tech user because an issue can exist outside software development as well as within (and means the same), while a bug is a software-specific thing and may not sound familiar to many users.

I will think of the exact structure for the feature roadmap and comment with an proposal for it later on.

**Comment by Glitchy-Tozier** [comment]
Regarding your list: Those are the ones I recognize:

```diff
+When will other languages than English be supported for glide typing and next word suggestions?
-Will FlorisBoard support stickers and GIFs in the media panel?
Will FlorisBoard have a recents emoji section in the media panel?
+Why does the adaptive theme feature show weird colors for some apps?
+The delete key randomly hangs after a long press and keeps deleting input until a restart of FlorisBoard
-The delete key gestures do not correctly select the text or delete the text, why?
-Why does Android keep saying "FlorisBoard keeps draining my battery" and how can I fix it?
-Why does F-Droid keep saying "FlorisBoard APK file not found"? (this issue is actually not in my hands but keeps popping up randomly, even for other apps)
-Is there a place where I can share my custom theme with others?
-Why do the clipboard cut/copy buttons seem to do nothing?
```

Mentioning the language-support seems to be really important.

> Why does F-Droid keep saying "FlorisBoard APK file not found"? (this issue is actually not in my hands but keeps popping up randomly, even for other apps)

Yup, I know.

**Comment by Glitchy-Tozier** [comment]
The selection-keyboard also is a favourite of many people, I suggest also adding it to the list.

**Comment by Glitchy-Tozier** [comment]
Let's add "There will be smartbar-customization" to the list!
