### ISSUE TITLE
new beta

### ISSUE THREAD

**Issue by murph2495** [florisboard/florisboard#1043]
Hello. Do you have any idea when the new beta will arrive to continue testing?

**Comment by Glitchy-Tozier** [comment]
I haven't heard of anything. I thing Patrick currently is stuck doing exams or something, so devellopment should (probably) recommence within the next few weeks.

**Comment by Hayleia** [comment]
This branch here received commits the last 20 days.
https://github.com/florisboard/florisboard/tree/spelling
But since it's "a big whole feature that touches a lot of areas", it can't be on the main branch before all areas are done, and this takes time.

**Comment by Glitchy-Tozier** [comment]
I see, he's trying to be sneaky!
Ty for the info :)

**Comment by Luensche** [comment]
> 
> 
> I see edited 3 days ago on florisboard profile but on the commit page it says 20 days
> ![Capture](https://user-images.githubusercontent.com/83851584/123708330-c0e7b900-d85a-11eb-9586-33f845f64f7c.PNG)

The date on the main page is related to the current selected branch (mostly master for stable stuff):
![grafik](https://user-images.githubusercontent.com/17471658/124128932-8ca01280-da7d-11eb-97d3-c9e2f597dff7.png)

The date on the profile is changed on every change in the whole repo (including development branches). So this is the newest change.

**Comment by patrickgold** [comment]
Like I said in a few other places, I didn't anticipate that the spelling implementation would be so complicated. The mentioned spelling branch is indeed the active one and in https://github.com/florisboard/florisboard/pull/1052 you can see the first experimental preview of a FlorisBoard system spell check service. As I am developing FlorisBoard besides my other activities, I can only focus on one task at a time - thus I didn't provide new updates while this big fish was in development. Currently users who use my debug APK can try it out and give me feedback, later on after fixing some critical bugs and implementing some additional mechanics I will release spelling tagged as "Experimental" to the beta channel. I wish I could speed up development but like I said I am doing this in my free time and some libraries like ICU just require days of trial-and-error, long compilation times etc. until it even fits into this project (but is needed due to special character support in Hunspell dictionaries...). Hope you can understand.

**Comment by Glitchy-Tozier** [comment]
I imagine German spell-checking will be fun to implement. LibreOffice still is struggling with the fact that nouns can be combined.

**Comment by Glitchy-Tozier** [comment]
Beta 5&6 have been released since this issue. Should we close it?

**Comment by patrickgold** [comment]
I think so, yes.
