### ISSUE TITLE
Successful-import-toast shown even though import failed.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1066]
#### Short description
Nothing got imported, yet the alert still shows up.

#### Steps to reproduce
![Screenshot_20210714-122556_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/125607400-2fad6a89-990d-4568-9539-7868f00385ab.jpg)
![Screenshot_20210714-122602_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/125607416-1dc141a6-5e52-4ec5-851a-20736d3df517.jpg)
![Screenshot_20210714-122045_Material Files.jpg](https://user-images.githubusercontent.com/59611881/125607439-08e34a6e-f845-424b-b4d9-cdd09e485c0d.jpg)
![Screenshot_20210714-122611_FlorisBoard Beta.jpg](https://user-images.githubusercontent.com/59611881/125607456-491cf378-2010-418e-9953-413bb27616de.jpg)

#### Environment information
- FlorisBoard Version: Beta 5, 0.3.13
- Install Source: Google PlayStore
- Device:  Samsung Galaxy S9
- Android: 10

**Comment by patrickgold** [comment]
Thanks for your bug report! Loading XPI extensions is only supported within the spell checker UI, the user/system dictionary uses an entirely different format (try creating some entries and then export it). Nevertheless, it shouldn't show success if it actually failed, I agree on this point.

**Comment by Glitchy-Tozier** [comment]
I thought they were different formats, but I wanted to see what would happen :)

The best case scenario would be
1. Only allow user to pick the correct types of files (no idea whether that's an option in android)
2. Properly notify user of import-success

**Comment by patrickgold** [comment]
This bug is now fixed, invalid formats simply display an error toast now (may look ugly if you do it with a binary file though because it assumes that every input is text). Error messages partially go into detail and also display the source line, so it is easier to identify which line causes the failure.

Restricting the files to choose is not really an option because the `clb` file extension's mime type is not correctly detected as `text/plain`, but as some generic one.

Thanks again for reporting this bug, this fix will be included in 0.3.14-beta12!

**Comment by Glitchy-Tozier** [comment]
Good job, Patrick :)
