### ISSUE TITLE
what happened to the app size?

### ISSUE THREAD

**Issue by IzzySoft** [florisboard/florisboard#1079]
Starting with beta-05, APK size suddenly jumped from less than 8M to more than 36M, going beyond the size limit of my repo. Taking a look, number of libraries didn't change, number of architectures was even reduced. What is causing the huge size increase – and can that be mitigated?

Looking inside the APK, `libflorisboard-native.so` for ARMv7 was around 115k with beta-04, becoming 15M+ (!!) with beta-05. If that cannot be reduced, may I ask for an ARMv7-only build to keep FlorisBoard betas available in my repo? Thanks in advance!

**Comment by Glitchy-Tozier** [comment]
@patrickgold @-ing you because it seems important.

**Comment by IzzySoft** [comment]
Thanks @Glitchy-Tozier! For now I've set ArchivePolicy to only keep the latest APK in my repo as FlorisBoard was already eating 80M from its allotted 30M; I'm ready to make few exceptions if warranted, so if those 36M are really needed, we'll have to live with that ArchivePolicy – but if it was some unnoticed side-effect of something, it'd rather be fixed and I remove that restriction on my end :wink:

**Comment by Hayleia** [comment]
Spell-checking with nuspell happened and brought the ICU lib (+data), I think that's the culprit from what I gathered. There is more info in #1064 and #1063 and some random commits such as 1582c1a3cf2e42e7280a144c01eaa5f3749c0e88.

**Comment by patrickgold** [comment]
Ah crap I completely forgot the APK size limit for your repo, @IzzySoft, I am sorry! So the huge increase in the APK size was because I must ship the ICU library packaged with FlorisBoard so spell checking is possible. The ICU library without the data (just the logic) is fairly small. Then there's the ICU data (all the data like conversion mappings, codemaps for all kinds of charsets, etc.) which takes a huge amount of storage space, its ridiculous (but sadly needed like I saw with unexpected crashes in beta05 when some codemaps are missing). The ICU data library is about 14-15MB per arch (this is why I restricted the architectures for now to arm and arm64 for now).

The good thing is there's a way to package the ICU data so it must only be shipped in one format for all architectures, effectively cutting down the APK size by 14MB in the current configuration (should be around ~22MB after the re-packaging, which still means we can only keep one APK with that configuration for now but at least it doesn't exceed the limit). Another way is to use `data-feature-filter.json` during build, but here I already restricted a lot of the data (before the data feature restriction the per-arch data size was 28MB, even more ridiculous).

I planned to experiment with the separation later (it should be easy but then its ICU so nothing is easy with that library), but as FlorisBoard uses more space than your per-app limit for your repo, I will immediately work on it. I will notify when I have some results!

Btw thanks for keeping the latest APK even if it exceeds the limit currently, this is very kind of you!

**Comment by IzzySoft** [comment]
Thanks @patrickgold! Well, that's awkward (the spell checking requiring more space than everything else together – guess that's why it's called "spell"? :speak_no_evil:). I guess the option to ship spell checking separately does not exist (I'm thinking of the tons of language packages available for AnySoftKeyboard)?

Until you find a solution, don't feel too much pressed with this. As indicated, I'm ready to make exceptions when they cannot be avoided as long as it's reasonable. So better take the safe road than the fast one, please.

We'll stick to one version in my repo for now – and should you somehow manage getting the size down to 15M or below, it's a tiny switch I can toggle to allow for more. I mainly wanted to make sure it was no accident that has been missed. Good to know you're on it – so best luck!

**Comment by Glitchy-Tozier** [comment]
> I'm thinking of the tons of language packages available for AnySoftKeyboard

Yeah, let's please try to avoid that outcome!

**Comment by IzzySoft** [comment]
I hadn't in mind to ask for "tons of language packages" for Florisboard :laughing: – just the fact that separation is possible. That way they even could be updated independently – and e.g. a minor update in the app wouldn't mean a download of xx MB. Just thinking aloud, not directing :wink:

**Comment by Glitchy-Tozier** [comment]
Still afraid 😖
I managed to push ASK's implementation out of my mind for quite some time, and now it's back!

How do "commercial" keyboards tackle this issue? Are they just enormous or do they simply do their spellchecking on some server? (Wouldn't make much sense because they also work offline.)

**Comment by patrickgold** [comment]
> I guess the option to ship spell checking separately does not exist (I'm thinking of the tons of language packages available for AnySoftKeyboard)?

AnySoftKeyboard's language pack are the dictionaries which are added per pack, in FlorisBoard's case the core functionality itself uses so much space (without any pre-shipped dictionaries at all). Also I try to have every privacy-friendly functionality in the core app to avoid an extension mess just to enable some features. I think the main issue is that hunspell/nuspell isn't really designed for mobile devices but it is ported and storage isn't an issue on desktop devices (Nuspell is very small but one of their dependencies - ICU - is a massive package).

> Until you find a solution, don't feel too much pressed with this. As indicated, I'm ready to make exceptions when they cannot be avoided as long as it's reasonable. So better take the safe road than the fast one, please.

Will do but like I said I don't like the fact that FlorisBoard exceeds the limit and the APK size issue has to be resolved anyways in the near future - so it is the first thing I am currently experimenting with so I can resolve the size issue.

> How do "commercial" keyboards tackle this issue? Are they just enormous or do they simply do their spellchecking on some server? (Wouldn't make much sense because they also work offline.)

Well GBoard AFAIK is based on the original AOSP keyboard (at least their App ID and their manifest indicate so), but has since then been heavily modified in both adding well implemented and performing features but also a lot of data collection. The dictionary problem is solved by just having full network access and downloading the dictionaries (but like I said this isn't even the problem with the current APK size issue). Gboard I think uses the word lists in the dictionary files and user dictionary combined with some magic (machine learning maybe?) to make spell checking working (although the spell checker is sometimes a separate system app and thus not included in the Gboard APK size).

**Comment by patrickgold** [comment]
I experimented with reducing the APK size and #1082 showcases the first outcome: I fiddled around with the data feature filter, checked what Nuspell really needs from the ICU data and was able to cut down the per-arch size for ICU by about 5MB. This means the APK size is at about 26MB instead of 36MB, which is a huge leap forward.

After pushing the draft commits I then tried to extract the data into data archives (so I don't need per-arch ICU data files), but for now this didn't work out that well, will experiment more with it tomorrow, Should this also work, I can further cut down the APK size by a few MB while re-adding support for x86 and x86_64 (which I temporarily disabled to keep the current APK's size smaller). I still have to do some testing if I didn't remove too much ICU data, but the first tests on my devices are really promising that everything still works perfectly. Will update you tomorrow with further results.

**Comment by IzzySoft** [comment]
Thanks Patrick! That sounds really promising. And with 26M the APK would be well within the limits again already – though it would still mean keeping a single version only. Keeping my fingers crossed for "stage 2" then (re-adding the other archs while still reducing/keeping size by using data archives) :crossed_fingers:

**Comment by patrickgold** [comment]
Quick update: like I predicted extracting the ICU data sounds simpler than it really is. I am currently generating and compiling successfully with an arch-independent data archive file and have been able to bring down the APK size to ~16-17MB for now (without x86/x86_64). It still crashes in runtime tough for non UTF-8 dictionaries (so pretty much every non-Latin dictionary), so I need to see why it does that and then everything should be set.

The question is if I even re-add direct support for x86 and x86_64, considering the fact that these arches are only used for all Android Auto devices, some Smartwatches and the desktop emulators (all of these aren't really targeted by FlorisBoard). All phones run either arm or arm64, so the primary target devices are fully covered. Re-adding support for x86/x86_64 would add about 5MB to the 16MB APK size, son unsure if it is worth it.

**Comment by IzzySoft** [comment]
Full ack to the arch question – that's why I take the armeabi builds on bigger splits (covers 90%+ of devices, as most ARMv8/64 devices support armeabi as well. Maybe simply point that out in the Readme and see if requests are there at all then; if not, it's perfectly fine to leave x68 out as then it's obviously not needed.

Good luck to get the ICU separation done without resulting crashes! :crossed_fingers:

**Comment by patrickgold** [comment]
What I could also do is to provide 2 APKs: one for arm/arm64 and one for x86/x86_64. The first is what is used for the app store releases and your repo, the second is only available in the GitHub release section and would allow for installation of FlorisBoard in an emulator. Thus the size is not an issue as these are separated. I dunno if I will do this though, as it means increased build time on my side.

**Comment by IzzySoft** [comment]
Not a bad idea to keep in mind, should the need arise. If you keep that door open, you can use it when requested :wink: If it comes to that, we should talk about file names – to make sure my updater fetches the right file.

**Comment by patrickgold** [comment]
I finally was able to get the dynamic loading of an ICU data archive up and running. I had to re-add break iteration tables to the ICU data archive, else Nuspell sometimes produces garbage corrections (is a 3MB increase sadly). The final APK size for now is 18MB for debug builds and ~16MB for beta/release builds, which is muuuuuch better than the current 36MB :)

I will do some other bug fixes related to spell checking and then release beta07. This means some time this week the new smaller APK should be in your repo and FlorisBoard does not exceed the limit anymore :)

There's still room for improvement though - this requires the next-word dictionary problem to be solved. When this is added, I can probably reduce the APK size by further 1-2 MB and then we will be able to keep 2 versions of the APK again.

As for x86(_64) support, I will for now just don't support it at all and should there ever be a desire then work on adding it either in the core APK or as a separate build. In case I make separate builds I will make sure to get back to you so you pull the correct APK for your repo.

Thanks again for your support and that you temporarily kept FlorisBoard even though it was my fault that I exceeded the storage limit, really appreciate it!

**Comment by IzzySoft** [comment]
That's great news, thanks! Can't wait to set it back to 2 versions – which I can do once the next release gets down to 16M per APK or less (especially if I know following versions will get below 15M again – as you saw, a temporary exceeding the limit is OK).

As for the x86 build, should it come, I'd suggest using the terms `_arm` resp. `_x86` in the file names, so I can set the updater to ignore `/_x86/i` or match only `/_arm/i` (RegEx). Both would make sure the x86 won't be accidentally fetched – and matching `/_arm/i` would even allow you adding other APKs I shouldn't fetch accidentally, if needed.

Thanks for your quickly tackling the issue, Patrick! And I gladly provide Florisboard with my repo, plus my support is gladly given. Especially with a cooperation as good as yours :smiley: :green_heart:

**Comment by patrickgold** [comment]
@IzzySoft Sorry to bother you again, but I have some questions regarding the F-Droid build servers and also have to inform you about the app size (again)

*First the app size, which affects the beta releases on your repo:*

I have to temporary re-add a Flictionary for word suggestion, which means after beta09 today the app size is expected to grow in beta10 by ~1.5MB from 15.5 to 17MB. This change is really important so I can make a stable release without breaking the old word suggestions feature. This means that we should only keep 1 APK from now on to respect your repo limit. In 0.3.14's development I will additionally add an alternative Settings UI library, which will additionally some 100 kB, so setting the limit to 1 APK is even more important. In 0.3.15 (that's a bit of time away though) the Flictionary and another huge json file will be dropped and if everything goes to plan we will be back at the 15MB mark. I just want to make sure that I don't increase and use up too much space again after the ICU thing, so I am informing you in advance :)

*Now my questions to the official F-Droid build servers:*
- Since the last stable build I've added git submodules (and are linked in the default `.gitmodules` file). Do these git submodules get initialized automatically or is there something else to do so this happens? This is important for the ICU part when compiling the app.
- I am currently using locally pre-cross-compiled ICU shared libraries in FlorisBoard [see here](https://github.com/florisboard/florisboard/tree/master/app/src/main/jniLibs), because they take quite some time to compile (at least on my mid-tier laptop where I compiled the currently included so files in jniLibs) and Windows users else could not build FlorisBoard at all.  
  AFAIK the policy for F-Droid apps though is to compile everything from source on the build servers, so should these ICU shared libraries be re-built on the servers or should the pre-built libraries be used? I have the [build script](https://github.com/florisboard/florisboard/blob/master/app/src/main/cpp/icu4c/floris-cc-icu4c.sh) { and internally [this script](https://github.com/patrickgold/icu4c-android/blob/ff5c585a438ba3b94199f95fc0eb0d569178a1c3/cc-icu4c.sh) } for Linux ready, but I don't know how well it works with the F-Droid build server environment (especially NDK tools and the NDK compilers and if the ICU tool will find them). Even if it works though, the build time will drastically increase. Asking here before I do anything stupid :)

Thanks in advance for your answers and your support!

**Comment by IzzySoft** [comment]
Thanks for informing me! As the change of **apk size** is temporarily, and per-APK stays well below 20M, consider this a temporary exception and we'll keep 2 APKs available in my repo. FlorisBoard is really worth that – so consider this exception valid until you scratch the 18M. I'd get into some technical difficulties if a single APK exceeds the 32MB limit, though – but that's not the case here anymore. Let me put a marker into MaintainerNotes for this – done. Uh-oh. Count this as compensation for me forgetting to increase to keeping 2 versions last time :see_no_evil:

**Git submodules:** adding those if there were none before requires an update to the build recipe (adding `submodules: true`). It's currently not set for FlorisBoard, so we will have to do that for the first version needing it (subsequent versions will then inherit this setting). Remind me when you have tagged that version, so we either are faster than checkupdates adding the new section, or fix what it has set up.

**Pre-compiled libraries:** correct, they are not permitted by F-Droid. But they could be set up as `srclibs` at F-Droid if they can be built separately (ideally via their own repo), or integrated in the "general build" e.g. as submodules. For the correct approach better ask one of the team experienced with build stuff, I'm not a dev and thus only know this by hear-say. Btw: `srclibs` would have the advantage that they can be shared by multiple apps – so if you think this could be the case, go for that.

Now, I need to ask how far FlorisBoard got. Is it already "production ready", so I could replace the existing keyboard on my FP2 and still have swipe (ah, you call it "glide typing") support? That would save me from using that proprietary Google lib. I don't have "extravagant needs", just need a stable keyboard with swipe support and EN/DE layout/dict (btw, where does it get its dicts from?). Going by the Readme, I should be safe trying even the dev version from my repo, right? Woah, what do I see there: "Clipboard manager/history"? Awesome, really need to give it a go…

**Comment by patrickgold** [comment]
> Thanks for informing me! As the change of apk size is temporarily, and per-APK stays well below 20M, consider this a temporary exception and we'll keep 2 APKs available in my repo.

If that works for you then we will go for this :)

> FlorisBoard is really worth that

:heart: 

> so consider this exception valid until you scratch the 18M. I'd get into some technical difficulties if a single APK exceeds the 32MB limit, though

Normally I should not scratch 18MB, but if I do I will inform you! Getting as high as 32MB def won't happen anymore, ICU's been tamed :)

> Git submodules:

Is it possible for me to locate and edit the build recipe to add this flag? If so then I'd add it now by myself (the stable release is min 2 weeks away still).

> Pre-compiled libraries

Ok I thought correct then that pre-compiled things are a no-no. ICU can easily be built separately in its own repo. I just need to include this repository as a git sub-module in the "main" app, as I need the output of it to successfully compile the app. I see though that srclibs seems to place the libs automatically during build which may fail with the FlorisBoard environment, will see. Where would be a good place to ask for this? fdroid/fdroiddata issues maybe? I'd then continue taking care of it.

> Now, I need to ask how far FlorisBoard got. Is it already "production ready"

This really depends what your needs are and to what degree the "difficult" features must be perfected. In general the latest beta builds are more stable than ever, thanks to the folks in my community who continuously provide new bug reports and help trying to resolve them. Stable version 0.3.13 will be very stable (as opposed to the buggy 0.3.12), so in terms of stability really good.

What you mention specifically and how well it is implemented:
- **Glide typing/Swiping**: X-yl did put in a lot of effort and this feature works really well, although only for English atm. This is because it relies on the underlying word suggestions dictionaries, see next point
- **Word suggestions**: Also English-only currently and use the old algorithm sadly + many bugs. Per [feature roadmap](https://github.com/florisboard/florisboard/blob/master/README.md), 0.3.14 reworks the outdated settings and adds the extension core. 0.3.15 uses the extension core for dictionary management and adds a new suggestion algorithm in C++, this time available for many Latin-based languages (including German). With this glide tying magically will detect German words too! Dictionaries will come from me or will be self-generate-able, because there's no standard format for this.
- **Spell checking (the integrated red lines below words in text fields)**: Works really well, the latest debug builds miss the Smartbar integrations though, but I'll add them before stable 0.3.13. All languages you can possibly find Hunspell dictionaries for in the Internet can be used, suggested source is Mozilla's addon store. This works because many open-source software including Firefox use Hunspell as spell checking (even Google uses it now), Hunspell is also fully open-source, so this is ideal to use.
- **EN/DE layout**: well supported since the start, so no problem here

So personally I'd say for you it is probably "production ready" in 0.3.15, but it's up to you when you want to give it a go :)

**Comment by IzzySoft** [comment]
> Is it possible for me to locate and edit the build recipe to add this flag?

You remember "that YAML file" when your app got added to F-Droid? That's the one. In the fdroiddata repo, `metadata/dev.patrickgold.florisboard.yml`. And the single line needs to go into the first build block requiring it. Had it been v0.3.12, this is what it had to look like:

```yaml
  - versionName: 0.3.12
    versionCode: 43
    commit: v0.3.12
    subdir: app
    submodules: true
    gradle:
      - yes
```

Just the one line added in the right place (order of fields *is* important, so it must come after `subdir`).

> Where would be a good place to ask for this? fdroid/fdroiddata issues maybe?

That's of course a good place. You could also ask on IRC/Matrix, or in the forum. Should you end up with an answer suitable for [our FAQ](https://gitlab.com/fdroid/wiki/-/wikis/FAQ), we should add it there – a short sum-up of which variant is best suited when would be good to have, and you're neither the first nor the last raising this question I'd bet.

> What you mention specifically and how well it is implemented:

Thanks for summing this up for me, Patrick – much appreciated! And I share your conclusion: 0.3.15 should be where all my "real needs" are covered. As the device I have in mind for this is currently not yet my daily driver, I might give 0.3.14 or even 0.3.13 a try and see it grow. That will solve a long-standing issue for me: up to now I usually side-loaded the proprietary IME lib to get slide-typing support and had a bad conscience at that. Thanks to FlorisBoard, that won't be needed any longer then.

Should I set up a "replacement list" one day, I guess the two of us already have an idea what will fill for the keyboard :smile: Currently, that list only exists in my head and is cited on-demand. Might be the case again tomorrow with my talk at Digitalcourage (going by your location you're a German speaker – so should you be interested: 6 pm CEST [online in this BBB room](https://bbb.imaginaerraum.de/b/dam-7mx-6xd), topic is privacy on Android and how users can enhance it for themselves – more [details here](https://izzy.codeberg.page/android_resources/)).

**Comment by patrickgold** [comment]
> You remember "that YAML file" when your app got added to F-Droid? That's the one.

Ahhhh build recipe = metadata for app :facepalm: Of course I know where to edit that one xD  
Will add it there in the next two weeks, but will wait for the ICU thing

As for the ICU thing, I will clean up and move the ICU build stuff to a separate repository, then ask on the forums (seems nice there on a first look). Should anything helpful come up with the pre-built srclibs, then I will sum it up for the FAQ.

The other alternative I consider is to improve the compile time and just build it every time the app builds on F-Droid. The metadata allows for the `build` field to be set to a command, which seems to be the perfect place to build external dependencies from source. As the build servers run on Linux I gather, the build script should<sup>TM</sup> run and compile. Will see. If I do this I may set up a local fdroidserver instance and test out the build process, because based on experience custom ICU builds don't work first try and require many trial&errors nagging on your sanity.

> Should I set up a "replacement list" one day, I guess the two of us already have an idea what will fill for the keyboard smile 
Currently, that list only exists in my head and is cited on-demand.

:)

I am also on my way to de-google myself but am not as advanced as you are. Begun de-googling/de-microsofting (is this even a word?!) about 1 1/2 year ago, and also have such replacement-list in my head :) It is going way better on the desktop and I am Linux-only for about 6 months now. On Android I currently replace closed-source apps with open-source apps, step by step, but still a few apps either come from Google or require the Play Services. F-Droid helps a lot in finding alternatives, but some apps aren't really replaceable or a replacement is yet to be found for me.

> my talk at Digitalcourage

Sounds interesting, so I might join in to listen :) And yes, I am natively speaking German, so this shouldn't be an issue.
