### ISSUE TITLE
Remove unnecessary text in readme

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1081]
There are no dates, therefore this text should be removed.

![Screenshot_20210718-105343_GitHub.jpg](https://user-images.githubusercontent.com/59611881/126076842-9a6ebfd4-d754-482d-a381-f6fe2829099f.jpg)

If you see this issue, Patrick, what were the dates originally? Would be interesting to know!  :)

**Comment by patrickgold** [comment]
> There are no dates, therefore this text should be removed.

They could be removed I agree but on the other hand should I ever add a date to something this sentence is true again, so I dunno on that one.

> If you see this issue, Patrick, what were the dates originally? Would be interesting to know! :)

Well well well :) The v0.4.0 milestone was originally scheduled for end of February, but I soon realized that's impossible... So I moved it back to end of March, then April, then OOM and some other issues completely obliterated the timeline and here we are. I gave up on setting any dates because it is virtually impossible for me to say when v0.4.0 will be ready. Spell checking is relatively well going at least and after improvements and Smartbar integration will be parts of the v0.4.0 release. The biggest headache for the v0.4.0 milestone currently are the word suggestions, because I am still unsure what format to use etc. Besides of that it is a lot of bug fixing (mainly vibration/haptic feedback and pretty much everything which has something to do with the delete key). As my plan is to make the beta public on GPlay with the v0.4.0 release, I want FlorisBoard to be in a state where it is decently running, without a sh*tload of bugs and crashes, to avoid a bad first impression on the GPlay store and to also build on a good foundation for the future major versions of FlorisBoard.

**Comment by Glitchy-Tozier** [comment]
> They could be removed I agree but on the other hand should I ever add a date to something this sentence is true again, so I dunno on that one.

I still would like to suggest at least putting `<!-- asdf -->` around them. This way no useless text is visible, but it can be restored easily if needed.

> Well well well :)

That's what i thought 🤣
On the other hand, that february deadline may actually turn out to be accurate. Let's just not mention the year!

> The biggest headache for the v0.4.0 milestone currently are the word suggestions, because I am still unsure what format to use etc.

Should you need any company thinking about something, just @ me  :)

**Comment by patrickgold** [comment]
Above commit removes the marked text and also adds a note regarding the current naming scheme of versions.

> On the other hand, that february deadline may actually turn out to be accurate. Let's just not mention the year!

:)

> Should you need any company thinking about something, just @ me :)

Will do, thanks for your great help around here :)

**Comment by Glitchy-Tozier** [comment]
Looks great!

> Will do, thanks for your great help around here :)

It's a pleasure!  :)
