### ISSUE TITLE
Private Clipboard (Clipboard manager)

### ISSUE THREAD

**Issue by ChaoticHub** [florisboard/florisboard#113]
I know that android has protected it's clipboard a lot better than in the past, though I think it would be very nice to have florisboard with it's own clipboard separate from the system. 

Sadly, not sure of any current open source projects that have this feature. I currently have an app that does this, would be cool to just be built into the keyboard. Maybe with a history of it's own like other issues reference.

**Comment by patrickgold** [comment]
Thanks for the suggestion!

I like your idea, because the Android system clipboard's privacy is a complete joke. It is very simple for an app to just silently read the clip data, and this does not even require a permission in the Android manifest... 🤔 

So containing the clip data within FlorisBoard is definitely a good idea privacy-wise. I will probably chain this feature request together with the clipboard history (#60), as it makes the most sense from the development side.
