### ISSUE TITLE
[UX] Preview vibration settings on force/duration values change

### ISSUE THREAD

**Issue by KaKi87** [florisboard/florisboard#1173]

**Comment by patrickgold** [comment]
Thanks for your proposal! With "preview" do you mean that a vibration in the strength/duration of the current slider value while moving is played?

**Comment by KaKi87** [comment]
Precisely, yes. Thanks

**Comment by patrickgold** [comment]
Will add it to the settings UI rework for 0.3.14!

**Comment by patrickgold** [comment]
Above linked PR finally addresses this feature request and adds a preview for the vibration strength/duration every time you finish a drag gesture on the slider. Note that tapping on the slider causes an invalid state to be dispatched, this is a bug in the compose library itself and will eventually be fixed by them (see https://issuetracker.google.com/issues/181415195).

Also do note that the preview of the vibration behaves a bit strange when FlorisBoard is not the default keyboard. I do not really know why but at least if FlorisBoard is the default the correct vibration is done as the preview. This change will be parts of the 0.4.0-alpha03 release. Thanks again for suggesting!
