### ISSUE TITLE
Suggestions freeze app

### ISSUE THREAD

**Issue by another-sapiens** [florisboard/florisboard#1181]
#### Short description
Enabling the experimental feature "Display suggestions" freezes the app after writing anything.

#### Steps to reproduce
1. Enable suggestions
2. Try to write something
3. App will freeze
4. You can unfreeze it by force-closing the app, re-opening it and disabling suggestions.

#### Environment information
- FlorisBoard Version: v0.3.13-beta10
- Install Source: F-Droid 
- Device: Samsung A10s 
- Android: 10, Stock

It also happened on v0.3.13-beta9. I haven't tried it on other recent versions.

**Comment by patrickgold** [comment]
beta11 and beta12 add some restrictions for word suggestions. These mean either your phone gives enough Java heap size and word suggestions work or word suggestions don't work but FlorisBoard at least doesn't crash. This issue is well known and thus I will close this issue to keep the list of issues clean!

**Comment by another-sapiens** [comment]
Thanks for clearing it up
