### ISSUE TITLE
Remove/Shorten Implemented features section in README.md

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1195]
This big list of many, many features.

You (Patrick) have done (and you still do) an amazing job with this app, but think no one ever reads this gigantic list.
I've never read it (except for now, in preparation for this issue). I don't think anyone else looks through those lists and goes "Hey, a keyboard that supports Caps Lock? Now I _must_ have it!"

### Suggestion:
Create  a short list of the most notable features (4-5, 6 at most). These features could be the same as the ones mentioned in #1017.

From what I can think of right now:
- Glide typing
- Word suggestions
- Themes (customizable & adapting to apps)
- An emoji-board

**Comment by Surendrajat** [comment]
@patrickgold 

> What I cannot figure out though is how to make these columns the same width...

Try increasing word count under stable.

**Comment by patrickgold** [comment]
Thanks for your feedback! I've since then finally been able to outsmart GitHub and the columns are now the same width. I've also experimented with different rows and put the track description in its own row, this makes the table look much better. Additionally I've reduced the number of words in the beta track description a bit, so the paragraphs match better.

---

<table>
<tr>
<th align="center" width="50%">
<h3>Stable <a href="https://github.com/florisboard/florisboard/releases"><img alt="Latest stable release" src="https://img.shields.io/github/v/release/florisboard/florisboard"></a></h3>
</th>
<th align="center" width="50%">
<h3>Beta <a href="https://github.com/florisboard/florisboard/releases/latest"><img alt="Latest beta release" src="https://img.shields.io/github/v/release/florisboard/florisboard?include_prereleases"></a></h3>
</th>
</tr>
<tr>
<td valign="top">
<p>Releases on this track are in general stable and ready for everyday use, except for features marked as experimental. Use this track if you only want major release updates.</p>
</td>
<td valign="top">
<p>Releases on this track are also in general stable and ready for everyday use, though crashes and bugs are more likely to occur. Use releases from this track if you want to get new features faster and give feedback for brand-new stuff.</p>
</td>
</tr>
<tr>
<td>
<p><a href="https://f-droid.org/packages/dev.patrickgold.florisboard"><img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png" height="64" alt="F-Droid badge"></a></p>
<p>

**Google Play**: Join the [FlorisBoard Public Alpha Test Group](https://groups.google.com/g/florisboard-public-alpha-test), then visit the [FlorisBoard Testing Page](https://play.google.com/apps/testing/dev.patrickgold.florisboard). Once joined and installed, updates will be delivered like for any other app.

</p>
<p>

**Manual**: Download and install the APK from the release page.

</p>
</td>
<td>
<p><a href="https://apt.izzysoft.de/fdroid/index/apk/dev.patrickgold.florisboard.beta"><img src="https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png" height="64" alt="IzzySoft repo badge"></a></p>
<p>

**Google Play**: Join the same group as in the stable track, then visit the [beta testing page](https://play.google.com/apps/testing/dev.patrickgold.florisboard.beta). The app can then be accessed [here](https://play.google.com/store/apps/details?id=dev.patrickgold.florisboard.beta).

</p>
<p>

**Manual**: Download and install the APK from the release page.

</p>
</td>
</tr>
</table>

Beginning with v0.4.0 FlorisBoard will follow SemVer versioning scheme and enter the public beta on Google Play.

## Highlighted features
- Spell checking service
- Word suggestions (currently English only and may not work on all devices)
- Glide typing (currently English only)
- Advanced theming support and customization
- Integrated clipboard manager / history
- Emoji keyboard (although lacking some features)

---

The above snippet would be my latest draft replacing the release and feature section.

@Surendrajat 

> Try increasing word count under stable.

Thanks for the tip but while you wrote the comment found another solution: setting the `td` width attribute to `50%` does the job.

**Comment by Glitchy-Tozier** [comment]
I was going to ask whether GitHub really doesn't permit width=50%. Great to hear it worked out.

Feedback (the points that could be improved):
1. I think in the English language you'd use `in general are stable` or `generally are stable`  instead of `are in general stable`.
2. It seems redundant to mention that "it's stable" thing in both columns. I think it can be left out as it doesn't convey any info that separates **stable** from **beta**.
3. `…though crashes and bugs are more likely to occur.` I think we can limit this to `…though bugs are more likely to occur.`. Crashes so far have showed up in every release, regardless of stable or not. (OOM: Failed to allocate…) Plus, removing text makes the whole thing shorter.
4. In the stable-column, you wrote `Join the FlorisBoard Test Group, then visit the testing page.`, while in the beta-column you wrote `Join the same group as in the stable track, then visit the beta testing page.`. I'd suggest using the first sentence in both columns, as the second sentence is longer and requires one additional mental maneuver to understand.
Currently, after reading the second sentence, the user will need to read the first sentence anyways to find the appropriate link, so nothing is gained by using that reference.

**Comment by patrickgold** [comment]
Thanks for your feedback Glitchy. I have tried to incorporate your feedback while also trying to reduce the paragraph text altogether in the track description:

---

<table>
<tr>
<th align="center" width="50%">
<h3>Stable <a href="https://github.com/florisboard/florisboard/releases"><img alt="Latest stable release" src="https://img.shields.io/github/v/release/florisboard/florisboard"></a></h3>
</th>
<th align="center" width="50%">
<h3>Beta <a href="https://github.com/florisboard/florisboard/releases/latest"><img alt="Latest beta release" src="https://img.shields.io/github/v/release/florisboard/florisboard?include_prereleases"></a></h3>
</th>
</tr>
<tr>
<td valign="top">
<p><i>Major versions only, 1 release per 1-3 months</i><br><br>Updates are more polished, new features are matured and tested through to ensure a stable experience.</p>
</td>
<td valign="top">
<p><i>Beta versions, 1-2 releases per week</i><br><br>Updates contain new features that may not be fully matured yet and bugs are more likely to occur. Allows you to give early feedback.</p>
</td>
</tr>
<tr>
<td valign="top">
<p><a href="https://f-droid.org/packages/dev.patrickgold.florisboard"><img src="https://fdroid.gitlab.io/artwork/badge/get-it-on.png" height="64" alt="F-Droid badge"></a></p>
<p>

**Google Play**: Join the [FlorisBoard Test Group](https://groups.google.com/g/florisboard-public-alpha-test), then visit the [testing page](https://play.google.com/apps/testing/dev.patrickgold.florisboard). Once joined and installed, updates will be delivered like for any other app. ([Store entry](https://play.google.com/store/apps/details?id=dev.patrickgold.florisboard))

</p>
<p>

**Manual**: Download and install the APK from the release page.

</p>
</td>
<td valign="top">
<p><a href="https://apt.izzysoft.de/fdroid/index/apk/dev.patrickgold.florisboard.beta"><img src="https://gitlab.com/IzzyOnDroid/repo/-/raw/master/assets/IzzyOnDroid.png" height="64" alt="IzzySoft repo badge"></a></p>
<p>

**Google Play**: Join the [FlorisBoard Test Group](https://groups.google.com/g/florisboard-public-alpha-test), then visit the [beta testing page](https://play.google.com/apps/testing/dev.patrickgold.florisboard.beta). Once joined and installed, updates will be delivered like for any other app. ([Store entry](https://play.google.com/store/apps/details?id=dev.patrickgold.florisboard.beta))

</p>
<p>

**Manual**: Download and install the APK from the release page.

</p>
</td>
</tr>
</table>

Beginning with v0.4.0 FlorisBoard will follow SemVer versioning scheme and enter the public beta on Google Play.

## Highlighted features
- Spell checking service
- Word suggestions (currently English only and may not work on all devices)
- Glide typing (currently English only)
- Advanced theming support and customization
- Integrated clipboard manager / history
- Emoji keyboard (although lacking some features)

---

Thoughts?

**Comment by Glitchy-Tozier** [comment]
>Thoughts?
EDIT: Just checked on mobile and this table looks a lot better than before due to the similar text lengths on both sides.

Yeah, it looks really good in my opinion!

**Comment by patrickgold** [comment]
Great to hear! From my side the above would be my final draft, has @KLaurence any other suggestions / feedback?

**Comment by KLaurence** [comment]
The recent draft looks great, overall.

For me, the readme should explain SemVer to some extent, probably by hyperlinking [its spec's summary](https://semver.org/#summary). The spec might be relatively too technical, even with the summary and how it mentions pre-releases and build metadata, but I think the summary is good as an explanation.

**Comment by patrickgold** [comment]
You are right, will add a hyperlink to the SemVer word. Thanks both of you for your feedback, above commit implements the changes into the README.
