### ISSUE TITLE
' Space bar long press' action doesn't account for long key press delay

### ISSUE THREAD

**Issue by Shizcow** [florisboard/florisboard#1205]
I noticed that when changing the long keypress delay to a much shorter delay, the 'space bar long press' option does not respect the change, and sticks to its default value. I believe the two should be linked.

Tested in the beta release.

**Comment by patrickgold** [comment]
It does take the long key press preference into account, it is just multiplied by the factor 2.5 for SPACE:

https://github.com/florisboard/florisboard/blob/92086954deecfb1fb460b2bfef6cb0ae19ba7b9b/app/src/main/java/dev/patrickgold/florisboard/ime/text/keyboard/TextKeyboardView.kt#L457-L472

This additional factor for space (and a few selected other keys) has been introduced because many users reported accidentally triggering the long press action of space bar, and after some rounds of testing and feedback we concluded that putting in this factor is the best way to go.

**Comment by Shizcow** [comment]
My bad then; thanks for the heads up!
