### ISSUE TITLE
Auto capitalize 'i' between sentence.

### ISSUE THREAD

**Issue by mohitsoni-dev** [florisboard/florisboard#1230]
When using 'i' between sentences the keyboard should automatically change it into uppercase.

**Comment by nicktyke** [comment]
Auto capitalisation in general could be improved in my opinion. Some words always start with a capital eg I and all its detivatives - I'd, I'll, I've, also proper nouns like names and places. Many keyboards do (or learn) to auto capitalise and one day i'd (!) love to see this one do to.

It's an easy fix for the user with the shift key, though. My personal bugbear on this subject is that if you start a sentence, it automatically capitalises but if you partially type a word, then select it from the suggestion bar, it doesnt and you have to go back to type it in full. If a word starts with a capital - either start of sentence or use of shift key - word suggestions should be capitalised too.

Proper nouns for every language etc would be quite an undertaking but I think the "I" derivatives for English and capitalising word suggestions if the word being typed started with a capital due to sentence start or user choice with shift, would bring a decent leap in day-to-day usability.

**Comment by patrickgold** [comment]
I think you mean word suggestions. Word suggestions in the current state are garbage, in 0.3.15 I will re-write them and also improve auto-capitalization. This specific request is already tracked in #441, will close this issue as a duplicate.
