### ISSUE TITLE
Deleting words process is kinda slow

### ISSUE THREAD

**Issue by itskarim** [florisboard/florisboard#124]
The app is amazing but it's seems slow to delete something 
Florisboard

https://user-images.githubusercontent.com/52888633/103749708-25416280-5006-11eb-9556-c97b1734106c.mp4

Open board

https://user-images.githubusercontent.com/52888633/103749930-6df91b80-5006-11eb-858c-74e4a4eddc1d.mp4

**Comment by patrickgold** [comment]
Thanks for your report! The long-press delete speed is dependent on your current CPU load, so results can vary from app to app and device to device. Note though that you are still on v0.3.2 and since then there has been significant performance improvements. v0.3.3 will be out probably on Sunday, but if it is possible could you try out the latest debug artifact build (https://github.com/florisboard/florisboard/runs/1651072776) and install it, to see if this has improved both the general UX and the deletion speed? The debug artifact installs separately (as `FlorisBoard Debug`) and does not affect your "main" FlorisBoard in any way. Thanks in advance!

**Comment by itskarim** [comment]
Do i need to build the app? If yes im sorry i can't i don't have pc rn :'(

**Comment by patrickgold** [comment]
No, it is a pre-built APK, ready to install besides your main installation. Just download the APK and install it. Then you can use The debug version besides the main version.

**Comment by soo-shan** [comment]
I'm not sure about how v0.3.3 behaves but as a feature request can long pressing backspace can be used for deleting whole word at once instead of single letter. That will also increase the speed.

**Comment by patrickgold** [comment]
@itskarim Above PR allows the precise character deletion swipe to be more consistent and also to select more characters. Will be included in today's release v0.3.4!
