### ISSUE TITLE
Ability to reorder clipboard contents (atleast in internel clipboard)

### ISSUE THREAD

**Issue by imDusht** [florisboard/florisboard#1242]
Sometimes i find the need of ordering clipboard contents to better organize pinned items, i think by default keyboard gets it's clipboard from system so it can't be reordered but many here might be using internal clipboard so it could be done for that?? (and it could sync to/from the system).

**Comment by patrickgold** [comment]
Thanks for your proposal!

I think this is a bit overkill, because in the end it is a simple clipboard history and not a notepad with the ability to paste directly into the input field. By default (in the latest beta 0.3.14-beta13) it is sorted New to Old, #1373 requests to add a "Sort by" for Old to New optional sorting.

The system clipboard does only hold the latest item and does not preserve the history at all, so the only way for me to even know the history is the internal clipboard history database. Also the clipboard history groups the pinned items on top and also makes a "Recent" group, so very new items are always up in the scroll view.

Based on above explanation I think I will reject this proposal, I hope you understand!
