### ISSUE TITLE
Enable word suggestions for other languages

### ISSUE THREAD

**Issue by the-voidl** [florisboard/florisboard#1244]
Is there a plan for enabling other dictionaries than English? What about the internal Android one?

I'd like to participate in improving the suggestions and/or predictions for the German language.

**Comment by cpontvieux-systra** [comment]
I can help with French. Can we use what is used on openboard?

**Comment by patrickgold** [comment]
Word suggestions are a massive thing which will be addressed in 0.3.15, not any earlier. When doing so I will automatically add support for all Latin-based langauges (like with spell checker). To keep the list of issues a bit cleaner I will close this issue thus.

> I can help with French. Can we use what is used on openboard?

Not really, because FlorisBoard uses another dictionary format. I can only confirm this 100% though when I get to implement word suggestions in 0.3.15, maybe I will switch to support the AOSP dictionary format.
