### ISSUE TITLE
Cursor leaving the input field

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#125]
It is possible that you can make the cursor move out of the input field by using the keyboard's navigation keys, or the space bar swiping gesture. You can then probably see that some other, nearby element has been selected, as if the cursor moved into the close environment and triggered it, e.g. the app's enter button's pressing effect (the shade/ripple effect) gets triggered. I hope my description of the situation is clear enough 😅

**Comment by patrickgold** [comment]
Thanks for the report! This is due to the fact that I am sending emulated hardware arrow keys, which have this effect. If I switch to the proper InputConnection method of moving the cursor, this will cause problems with single digit number fields and such. So I currently do not know how to solve this problem, but I will add it to my todo list!

**Comment by tsiflimagas** [comment]
Oh, I see it's a tricky one. Well, really not much of an issue (to me at least), yet, if a workaround comes up, it'll be a nice. Thank you!

**Comment by patrickgold** [comment]
Above PR fixes the behavior that the cursor could leave the input field. This is done as there's a way to differentiate between raw input editors like Termux (which get hardware-emulated arrow keys) and "normal" apps, where the official methods provided by the input connection are used.

**Comment by tsiflimagas** [comment]
Ahh, so you did it! Thank you very much, this further improves the experience for me, and generally I believe. You're great 😊
