### ISSUE TITLE
"Swipe to delete" not triggering immediately in "try out your setup" field

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#1252]
#### Short description
Describe the bug in a short but concise way.

If you write something in the new "try your setup" field and swipe on delete button to erase it, either nothing will happen or cursor will jump to the start of the text. If you first delete one character and then swipe, it will work properly. This seems like an issue in the "swipe to delete" feature and not in the field, since it doesn't happen with Gboard.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

#### Environment information
- FlorisBoard Version: 0.3.14-beta01
- Install Source: GitHub
- Device: Xiaomi Redmi note 8 
- Android: 11, Custom rom

**Comment by patrickgold** [comment]
Thanks for your bug report on the new Settings UI! I've investigated into the issue and the problem affects way more than just the delete swipe.

From what I gather the IME core is not the issue, but the implementation of the TextField itself. It seems that it does not support the ExtractRequest API yet, which means cursor/text updates fail to be recognized by FlorisBoard, creating invalid states for the logic (suggestions, current word, delete swipe, cursor position, etc).

As the TextField is supplied by the relatively new Jetpack Compose UI library, I highly suspect that the bug comes from that library. Will assign it to the current preference rework and will see if either I can patch the bug or wait for the library to improve things.

**Comment by patrickgold** [comment]
```
2021-09-14 22:11:11.177 27125-27125/dev.patrickgold.florisboard.debug W/RecordingIC: requestCursorUpdates is not supported
```

I think that Logcat line is the culprit of this bug. The "Try out your setup" box is the only text field where this line appears (apart from some raw input method editors but that's expected).

**Comment by tsiflimagas** [comment]
It seems like they did some work on it(?). Now it's almost fine for FlorisBoard (cursor moving gestures don't work immediately after changing from another keyboard). Now it's buggy only for simple keyboard (it has swipe to delete and swipe to move cursor too), from the keyboards I've tried (not that it should really matter, this is meant to be used with FlorisBoard).

**Comment by patrickgold** [comment]
Still don't know how to fix this issue and the bug has not been resolved on the Jetpack Compose side yet. Either I have to find some hacky solution or leave it as it is for stable 0.3.14, will let this issue open but remove it from the Settings rework project.

**Comment by tsiflimagas** [comment]
By `deaf3295` the "Try out your setup" field works fine. While compose library was updated to a much newer version, the log message you indicated still occurs which, I guess, means that it still remains to be fixed in the library, but since the behaviour in the app is fine and library bugs aren't really your business to fix, I think this can be closed.
