### ISSUE TITLE
Enable Seedvault encrypted backups

### ISSUE THREAD

**Issue by PandaCoderPL** [florisboard/florisboard#1324]
In my opinion it would be good idea to let users backup FlorisBoard application using [Seedvault](https://github.com/seedvault-app/seedvault). [Here](https://github.com/grote/Transportr/commit/4dc38f429f75909a088d8bd8a5b3b5ddd8030f71) you can see example of how such backup option could be implemented in privacy-respecting way. More details about it [here](https://github.com/seedvault-app/seedvault/wiki/FAQ#why-do-some-apps-not-allow-to-get-backed-up). Thank you in advance.

**Comment by IzzySoft** [comment]
I also wonder why FlorisBoard has opted out from backups, so not even `adb backup` can be used. Implementing [your plans from a year ago](https://github.com/florisboard/florisboard/issues/272#issuecomment-769683325) would solve both, @patrickgold :wink:

**Comment by patrickgold** [comment]
> I also wonder why FlorisBoard has opted out from backups, so not even adb backup can be used. Implementing your plans from a year ago would solve both

Simple reason: I didn't really prioritize this feature and the 0.3.13->0.3.14 rework of pretty much everything would have meant that these backups would not be compatible with each other.

I am currently though locally playing around with allowing the auto backup option in the Manifest (+ fullBackupContent xml file), which I will probably push a draft debug build tomorrow. This means that then `adb backup` and probably also Seedvault would be usable for backups.

**Comment by IzzySoft** [comment]
> would have meant that these backups would not be compatible with each other.

Ah! OK, that reason I do understand. But then, one usually backs up APK+data, so the match should be there (at least with Seedvault – with `adb backup` the default indeed is to skip the APK). Btw, AFAIK Seedvault makes use of the "fine-grained backup settings" if you need to exclude pieces.

> I will probably push a draft debug build tomorrow

I'm still looking forward to the v0.3.15 you recommended me (no pressure – just stating that I do still follow :wink:). I was using the latest F-Droid build for a while, but it didn't always work as I'd wanted it to (no complaints, I was aware it wouldn't, from our discussion before I installed). Now that I've done a fresh setup and, due to no-backup-permitted would have to configure FB anyway, I think whether I should instead use the pre-release builds from my repo. There's always the default keyboard, should difficulties arise…

**Comment by patrickgold** [comment]
> But then, one usually backs up APK+data, so the match should be there (at least with Seedvault – with adb backup the default indeed is to skip the APK).

That's correct,the APK is included in Seedvault and can be included in `adb backup`, in which case backup may have made sense earlier on too.

> Btw, AFAIK Seedvault makes use of the "fine-grained backup settings" if you need to exclude pieces.

I know, it is possible to define backup_rules. Just a bit annoying that I have to write and maintain 2 versions, because with Android 12 the rules syntax has changed.

> I'm still looking forward to the v0.3.15 you recommended me

Yeah I am trying my best to get things done, I must say though that the preference rework also updates the keyboard logic itself and brings a new custom theming engine, which was not planned for 0.3.14, because doing it now saves me quite a lot of time in the long run, so I accepted that 0.3.14 development would take longer.

Be aware though that version numbers have changed (does not really change anything else on the time scale):
- 0.3.14 (current betas): Preference and keyboard logic rework
- 0.3.15: Hotfix bug fixes for preference rework
- 0.4.0: Word suggestions, also updating the versioning scheme to advance faster (`0.a.b`, where `0` indicates that this project is not a stable product yet, `a` are major releases and `b` are bug fixes). This means 0.4.0 would be the version to look out for, in February I begin with the first alpha builds for 0.4.0.

> I think whether I should instead use the pre-release builds from my repo

Would make sense because if you have to configure everything from scratch the beta releases from your repo already set up everything to be in the new format and will be compatible with 0.3.14 and higher.

**Comment by patrickgold** [comment]
Above linked PR #1490 enables support for Android's auto backup. As I do not own a device running a ROM with Seedvault I cannot confirm if it works fine with Seedvault as well, but in general the backup works in my tests I've done (tested with `adb backup`).

**Comment by IzzySoft** [comment]
> because with Android 12 the rules syntax has changed.

And they don't even recognize the "old" format for compatibility reasons? Oh my… My Fairphone (mostly used with F-Droid for testing) just reached 11. My current main driver is stuck on Nougat. My personal one is on Oreo (would need to be clean-flashed and reconfigured for Pie). No idea when I'll be going to see 12…

> saves me quite a lot of time in the long run

Then it's the right thing to do, full ack. And I see the 0.3.15 I was waiting for now moved to 0.4 (ah, you even say so yourself) – good to know :wink:

> Would make sense because if you have to configure everything from scratch the beta releases from your repo already set up everything to be in the new format and will be compatible with 0.3.14 and higher.

Yes, but could I transfer that to the F-Droid build in the end (e.g. via export/import) – as backup/restore won't accept it due to signature changes? Otherwise my choices would be to depend on your providing APKs for my repo forever – or I'd have to setup from the scratch once more.

> As I do not own a device running a ROM with Seedvault I cannot confirm if it works fine with Seedvault

OK, convinced me. Please let me know when that PR makes it into a build available via my repo, I'll then test with Seedvault: Install the app, change some configuration, make sure it was backed up, uninstall, re-install, and see if my settings were restored.

**Comment by patrickgold** [comment]
> And they don't even recognize the "old" format for compatibility reasons? Oh my…

Yes and no? I dunno, I kinda find the Android documentation on auto-backup a little bit confusing. [Here](https://developer.android.com/about/versions/12/behavior-changes-12#new-format) they state that the new configuration format is used on A12+ if it is present, else the old one is used. [Here however](https://developer.android.com/guide/topics/data/autobackup#include-exclude-android-11) (or like pretty much all blue boxes on that page) they state that all apps targeting SDK 31+ MUST use the new format, the old one will be ignored. So I don't really know what's correct here, maybe I will try it out on an emulated Pixel running A12.

> No idea when I'll be going to see 12…

Me neither, less because of their backup syntax decisions I didn't even know about until yesterday but because of the massacre they did in the notification screen (like why soo much padding and so less space for actual content and the controls for WiFi etc??!). Nope I think I will wait for Android 13, hoping they revert some of these horrible horrible design decisions.

> Yes, but could I transfer that to the F-Droid build in the end (e.g. via export/import) – as backup/restore won't accept it due to signature changes? Otherwise my choices would be to depend on your providing APKs for my repo forever – or I'd have to setup from the scratch once more.

Via auto-backup I honestly don't know, but I am currently locally working on an internal Backup & Restore feature as an addition to auto-backup. It will allow you to back up all of FlorisBoard's data (except the databases for clipboard history etc.) in a ZIP file, save it wherever you please and restore it in another installation, not locking you in to the track (so pretty much interchangeable between stable, beta and debug builds). Note that these ZIP files are not signed nor encrypted though, but if you just want to quickly switch tracks locally this method is more than sufficient and will work in your case once you switch to stable.

> OK, convinced me. Please let me know when that PR makes it into a build available via my repo, I'll then test with Seedvault: Install the app, change some configuration, make sure it was backed up, uninstall, re-install, and see if my settings were restored.

Thanks, will do!

**Comment by IzzySoft** [comment]
> I kinda find the Android documentation on auto-backup a little bit confusing.

Only that one? I always wondered how developers find out what they need to know. Just try to figure what permission is meant for what, where it's needed for and where not, and what other implications there might be…

> apps targeting SDK 31+ MUST use the new format

Which means breaking backup/restore for everyone else. Great – especially considering how long it takes until a new version is really "widely available" for the end-user. I'd understand that limitation when speaking about minSdk, but not with targetSdk.

> I think I will wait for Android 13, hoping they revert some of these horrible horrible design decisions.

Wouldn't be the first Android version to skip, IIRC :speak_no_evil:

> Via auto-backup I honestly don't know

No, that I've implicitly ruled out already (I won't be tampering with the signature protection – though I know it's possible). But now that you mentioned your internal backup method, you finally convinced me "going beta" with the release mentioned. I bet that export/import will be ready before reaching the point I'd switch back to the stable channel (F-Droid.org) – I'm trusting you to have updates available via my repo until then. There are some other apps I use via my repo instead of F-Droid, despite of being available in both places (Catima for example), so FlorisBoard could easily fit into that category :smile:

**Comment by IzzySoft** [comment]
Yay, thanks Patrick!

**Comment by patrickgold** [comment]
Backup is now merged (both automatic and manual #1498). I will now work on the theme editor, which was the main objective for beta09 (before I ventured off into adding backup) and then make the beta release, so for you to actually test this out you'll have to wait for next week. 

Thanks again for your help and support on everything, really appreciate it!

**Comment by IzzySoft** [comment]
Looking forward to that – and I gladly do what I can :smile: And hey, that manual one looks good – I fully trust it will cover my needs when (or if?) switching between your build and F-Droid's one day :+1:

**Comment by patrickgold** [comment]
@IzzySoft Took me waay longer than I wanted to but I finally finally finished the theme rework and published both the new stylesheet editor and backup goodies (beta09). If you want you can now try out Seedvault with FlorisBoard and give me feedback how well it works (or doesn't), really appreciate your assistance here!
