### ISSUE TITLE
High Battery Usage

### ISSUE THREAD

**Issue by angriness-sleek** [florisboard/florisboard#136]
This is in a 20 hour discharge period from 90% to 5%. The total typing time was 50 mins, and i have not opened the FlorisBoard app, just the keyboard and typed with it on another app:
![Screenshot_20210109-003626_Settings](https://user-images.githubusercontent.com/62484249/104054541-3ac0b300-51e5-11eb-9c91-f8d5c197c2c7.png)
Here is AnySoftKeyboard in a different test occassion:
![IMG_20210109_004127_104](https://user-images.githubusercontent.com/62484249/104054638-6479da00-51e5-11eb-9caf-3fc7d67a4e4e.jpg)

**Environment information**
- FlorisBoard Version: 
- Install Source: F-Droid
- Device: Mi A2
- Android version, ROM: 10, LineageOS

**Comment by D3SOX** [comment]
I also observed this on OxgenOS 11. I sometimes get this notification from the system (even when I'm not currently using the keyboard):
![battery](https://user-images.githubusercontent.com/24937357/104055274-c559e000-51ee-11eb-8407-f932dd82a92f.png)
But it hasn't happened for a while now (Maybe because I'm currently using a self-compiled version from master)

**Comment by patrickgold** [comment]
@angriness-sleek This issue was most likely due to the fact that the keyboard did severe overdrawing, which has been fixed and merged into master (see 710e7ca ), but has not yet made it to the release versions. This is also most likely the reason why @D3SOX 's self-compiled version does not have this issue anymore. I will let this issue open until you can confirm after the next release that it has been fixed on your device.

**Comment by patrickgold** [comment]
Above PR is the corresponding pull request which fixed a lot of performance issues, both in overdrawing and in popup UI rendering.
