### ISSUE TITLE
Setting suggestions

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1361]
Change the "keyboard" section name to layout and move the sound & vibrations to a dedicated section.

Main reason: the section name "keyboard" is not very descriptive.

**Comment by patrickgold** [comment]
I do not know which version you are on, but in 0.3.14-beta05 the preferences look a lot more organized than before and in general I like the current structure and naming.

The problem I see with your renaming proposal is that sometime in the future you will be able to customize and configure layouts in a separate screen, so renaming the "Keyboard"-screen will cause a lot of confusion then.

The Sounds&Vibration screen has its own screen in the latest beta builds, but are purposely not in the main list (to avoid cluttering the main list too much).

Sadly because of above points I will reject your feature proposal, but you can still answer and give additional input/ideas to this topic in this thread if you want, maybe I will pick it up and implement it.
