### ISSUE TITLE
Letter-keys can be accessed in Clipboard-manager/Emoji-screen

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1394]
#### Short description
I did some double-clicking, again :)
Not an important bug, just a fun 'un.

#### Steps to reproduce
1. Hold the enter-button
2. While still holding the enter-button, click on a letter-key.
3. Yay, you're on another view while still having a popup active!

#### Environment information
- FlorisBoard Version: 0.3.14-beta05 (61)
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

https://user-images.githubusercontent.com/59611881/141317080-5e529369-2b23-41f0-9d11-ebf118f49b94.mp4

**Comment by patrickgold** [comment]
Stop breaking my poor popup views xD :)

As I am currently fully re-implementing the keyboard UI in Jetpack Compose (#1370; that's why the current beta release takes sooo long), I will also completely redo the popup implementation. I will try my best to make it Glitchy-safe this time, but only beta06 will tell if I managed to achieve it :)

**Comment by Glitchy-Tozier** [comment]
> I will try my best to make it Glitchy-safe this time, but only beta06 will tell if I managed to achieve it :)

We'll see ;)

In this case, should we close this issue?

**Comment by patrickgold** [comment]
Yes I think so, because I remember seeing this bug mentioned earlier. Also actually beta07 will be a better test for this, because in the upcoming beta06 release there will be no emoji implementation. (beta06 is a demo and test if the new keybaard UI in JC works across different devices)

**Comment by Glitchy-Tozier** [comment]
Got it, I'll hold back until beta07!
