### ISSUE TITLE
Settings menu graphical issue

### ISSUE THREAD

**Issue by ZenerDeveloper** [florisboard/florisboard#1415]
#### Short description
Going into the about menu and going back causes the menu items to shift down following the test box animation.

#### Steps to reproduce
1. Scroll to the bottom
2. Tap about
3. Go back
4. The menu has shifted down slightly

https://user-images.githubusercontent.com/80724816/143965814-46ff4b98-1839-47a5-972c-1e49cd7bbbd0.mp4

#### Environment information
- FlorisBoard Version: 0.3.14-beta06
- Install Source: F-Droid
- Device: Samsung Galaxy S10+
- Android: 11 OneUI 3.1

**Comment by patrickgold** [comment]
Thanks for your bug report!

This is happening because the preview field collapses for the about screen, thus the main screen layout is being pushed down wile the screen fade animation is happening. Upon returning, the preview field is shown again but the scroll position will not reset.

As this issue is only really relevant and noticeable when you go into the About screen, I think I will leave it as it is (the effort required to fix this minor graphical inconsistency is too much compared to the outcome and effect). Hope you can understand!
