### ISSUE TITLE
Workaround for clipboard history bug

### ISSUE THREAD

**Issue by suhan-paradkar** [florisboard/florisboard#1441]
I just saw the known issues section of v0.3.14-beta07 and I guess we can workaround the display state bug by adding and removing a `NULL` object to the clipboard history on boot....

I currently am yet to figure out the repo structure, but will pull up a PR if I figure it out...

**Comment by patrickgold** [comment]
That's exactly what I also tried to do as a workaround. The problem is that Room (the database library responsible for storing the clipboard history) is smart and doesn't fall for adding a temp clip item and removing it again, it just ignores it.

The current debug builds of beta08 have a new Room library version, and initial tests showed that I wasn't able to reproduce the clipboard history known issue of beta07 anymore. If you want you can either download the artifact of #1440 or compile the prefs-rework-8 branch and test out if this is also fixed for you.

**Comment by suhan-paradkar** [comment]
Well... Then I will be closing this issue since it's been solved...
