### ISSUE TITLE
dictionaries not used for spellchecker

### ISSUE THREAD

**Issue by TheFooI** [florisboard/florisboard#1454]
Using a German and an English layout but only the english dictionary is being used for suggestions in both languages.
installed dictionaries are:

British English Dictionary (Marco Pinto)
en-GB | 3.0.0 | mozilla_firefox

German Dictionary
de-DE | 2.0.6.1webext | mozilla_firefox

**Comment by tsiflimagas** [comment]
Do you mean the suggestions generated by the system, or the ones generated by FlorisBoard? If it's the latter, then currently FlorisBoard doesn't support any other languages for suggestions. Also, suggestions have been disabled in 0.3.14-rc versions since the current implementation has many issues, and will be replaced by a new one in 0.4.0 milestone.
