### ISSUE TITLE
Crashed unexpectedly

### ISSUE THREAD

**Issue by KalusVP** [florisboard/florisboard#1467]
![Screenshot_20211223-144330_FlorisBoard](https://user-images.githubusercontent.com/57546470/147248859-5731a9a4-6c5f-4ad5-83c2-477497832ccf.png)

#### Environment information
- FlorisBoard Version: 0.3.13 (56)
- Device: Samsung SM-G950F
- Android: 9 (cn=P sdk=28)

#### Features enabled
```kt
smartbar = true
suggestions = true
suggestions_clipboard = true
suggestions_next_word = true
glide = false
clipboard_internal = true
clipboard_history = false
```

#### Attached stacktrace files
<details>
<summary>1640258146786.stacktrace</summary>

```
java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 0 free bytes and 0B until OOM, max allowed footprint 268435456, growth limit 268435456
	at android.os.Parcel.obtain(Parcel.java:2967)
	at android.os.Binder.execTransact(Binder.java:718)

```
</details>

**Comment by Glitchy-Tozier** [comment]
Thanks for your bug report!

The crashes you experience are OutOfMemory issues, which are caused by word suggestions. The current workaround is to disable word suggestions if they cause trouble and wait for version 0.3.15, where Patrick will re-implement them to make sure this specific crash does not occur again.

**Comment by Glitchy-Tozier** [comment]
(I closed the issue due to it being a duplicate of #1268)
