### ISSUE TITLE
App blinks constantly

### ISSUE THREAD

**Issue by andureas** [florisboard/florisboard#1475]
#### Short description
When I open FlorisBoard app, it starts blinking out of nowhere and does not stop until closed.

#### Steps to reproduce
1. Open FlorisBoard application.
2. Wait 2-3 seconds for the blinking to start.

#### Environment information
- FlorisBoard Version: 0.3.13
- Install Source: F-Droid
- Device: Redmi Note 10 Pro
- Android: 11, Stock

https://user-images.githubusercontent.com/96786668/147586082-900d3b26-0feb-4e65-ab69-60288989b758.mp4

**Comment by andureas** [comment]
Also, the dark (night) theme isn't working since two days.

**Comment by patrickgold** [comment]
Thanks for your bug report! To be honest, I haven't seen this particular bug at all until now, but what I know is that FlorisBoard and Xiaomi ROMs on Android 11/12 don't like each other (especially since the last month or so, so it seems like an Xiaomi update was rolled out which introduced this issue). Do you by any chance have system dark mode enabled?

**Comment by andureas** [comment]
System dark mode is off. Also, from today, the typing has been lagging. I mean, the words are not displayed in real time as I type.

**Comment by patrickgold** [comment]
Are you able to reproduce this issue in the latest beta release (installs separately)? I use a completely different UI library in the betas, so this could improve (or worsen) things in this regard.

**Comment by andureas** [comment]
No. All issues mentioned above have been resolved in the latest beta release.

**Comment by patrickgold** [comment]
Thanks for confirming!
