### ISSUE TITLE
text delete issue

### ISSUE THREAD

**Issue by 3abdooo** [florisboard/florisboard#1501]
deleting text by continuing pressing the delete button, deletes a few letters and then stops, sometimes only select some letters.
####################
beta7 and beta8
##################

samsung galaxy s7 LineageOS 17.1 with microg

**Comment by reszkojr** [comment]
This happens because of the delete swipe gesture. When holding the delete button, the user can still make a micro-swipe and the keyboard will think this is a swipe gesture and stop.

A way of fix this would may be setting a "canSwipe" boolean to "false" everytime the user is holding the delete button.
