### ISSUE TITLE
Add a Clipboard History button on smartbar 

### ISSUE THREAD

**Issue by dude-shah** [florisboard/florisboard#1503]
Add the history button so clipboard items are quickly accessible ..

**Comment by dude-shah** [comment]
> There's this button:
> ![Screenshot_20220114-082925_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/149468527-0235266c-e469-4c94-addc-18a985bd9139.jpg)
> ![Screenshot_20220114-083114_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/149488564-f99d7c4a-d46e-41be-8782-bc3a283be5cd.jpg)
> Are you proposing something different?
> 

> There's this button:
The Button you used to popup extra smartbar buttons , are not available in 0.3.13, what version are you using.

> Are you proposing something different?
There are extra button on smartbar that i dont use like emoji's button (i have emoji button near space key) 
If its possible make it like we can choose what button should be in smartbar.

Thank you.

**Comment by Glitchy-Tozier** [comment]
1. The bright keyboard is the beta-version.
2. The screenshot of the dark keyboard doesn't contain the clipboard-manager-icon, I apologize for that.
That being said, it IS possible to use the clipboard-manager in v0.3.13. You can find the option to enable it in the "keyboard"-tab of your FlorisBoard settings (sry for the german screenshots):
![Screenshot_20220115-080946_FlorisBoard.jpg](https://user-images.githubusercontent.com/59611881/149613060-b7952cb0-6b03-407d-9d8d-b2b992123e60.jpg)

**Comment by dude-shah** [comment]
Can you tell when is next stable release coming ...
I know beta release are coming fast and more often but It says stable release every 1-3 months , its been 5 month since last stable release(0.3.13).

**Comment by Glitchy-Tozier** [comment]
I know, it has been a long time. If I had to guess, I'd say it's 1-2 more months until the next update, but I'm not sure. It heavily depends on how difficult the remaining changes are and on how much time Patrick is able to put in.

In case you're interested, [this is the to-do-list](https://github.com/florisboard/florisboard/projects/1) for the settings-redesign (which is the main purpose of v0.3.14). [This](https://github.com/florisboard/florisboard/blob/master/ROADMAP.md) is the plan for the next version and the ones after it.

That being said, like I already mentioned, you *can* enable clipboard history in v0.3.13, as seen in my previous screenshot.

**Comment by patrickgold** [comment]
> Can you tell when is next stable release coming ...

The problem with 0.3.14 is that it reworked the preferences (that's a lot of work) AND the keyboard logic/UI had to also be adapted to accommodate the new backend logic. Implementing this stuff takes time sadly, especially when done in my free time.

As for when the next stable release is coming out, I aim for mid-February, depending how well the theme editor progress goes and how tricky it is to fix emojis and glide typing.

> It says stable release every 1-3 months

Yeah that's something which I will adjust to probably 1-6 months, because that's the range what it really is.

As for the original intent of this issue, this is already implemented in the latest betas, so I will close this issue. You can of course still reply in this thread. Also thanks @Glitchy-Tozier for providing the steps for 0.3.13, really appreciate it!
