### ISSUE TITLE
signal messenger carriage return missing?

### ISSUE THREAD

**Issue by CondomsPreventCoinkydinks** [florisboard/florisboard#1525]
#### Short description

small issue. enter sends text instead of starting new line in message box inside signal messenger chat. anysoft keyboard doesn't behave this way. possible to change or add a carriage return input in symbols? see pics. sometimes green button shows return but still sends message instead of starting new line.

replicate:
send message in signal. try to start a new line in message box. compare to anysoft kb.

#### Environment information
- FlorisBoard Version: latest
- Install Source: F-Droid
- Device: samsung note9
- Android: 9

![Screenshot_20220127-091014_Signal_1](https://user-images.githubusercontent.com/68381290/151328931-396e5f5a-698c-4c77-887a-31f7a843e7e9.jpg)

![Screenshot_20220127-090834_Signal_1](https://user-images.githubusercontent.com/68381290/151328989-360ce289-fda0-4e33-8ae5-e42c91a649a3.jpg)

**Comment by patrickgold** [comment]
Thanks for your bug report!

I just tested this in the latest beta build (beta08) and was not able to reproduce this issue in Signal, I was able to add a new line instead of sending the action. Is it possible for you that you install and test out the latest beta build in this regard? (It will install separately and will not touch your main installation).

**Comment by CondomsPreventCoinkydinks** [comment]
thanks. i tried with the latest beta version and had the same prob. then tried the stable and anysoft KBs again, BOTH didn't work i.e. sent messages instead of starting a new line.

so i went to signal's setting and the send option was enabled! unless I'm losing my marbles, i didn't change this recently, but when i switched it back, all 3 keyboards now entering new lines. so, issue sorted. sorry to have wasted your time.

i hope you and AnySoftKeyboard can team up and give us an Anyfloris KB. both are excellent IMO but i imagine it's tougher competing with google keyboard on your own.

**Comment by patrickgold** [comment]
> so i went to signal's setting and the send option was enabled! unless I'm losing my marbles, i didn't change this recently, but when i switched it back, all 3 keyboards now entering new lines. so, issue sorted. 

Ok seems like the option may have reset with a Signal update, but if it works now then this is resolved.

> sorry to have wasted your time.

No worries, I am here to try to resolve issues with my keyboard :)

> i hope you and AnySoftKeyboard can team up and give us an Anyfloris KB. both are excellent IMO but i imagine it's tougher competing with google keyboard on your own.

I mean I am always open to collaboration but on a technical side I see many problems, just because our code bases could not be more different (Java vs Kotlin, Android XML vs Jetpack Compose, Shared prefs vs custom datastore, LatinIME based vs fresh start, ...). But you are right, it sometimes can be tough to compete with the high quality standards of GBoard alone, maybe someday there will be a collab.
