### ISSUE TITLE
Delete after glide typing should delete the whole word

### ISSUE THREAD

**Issue by TheHawaiianKoala** [florisboard/florisboard#1541]
#### Short description
Using the latest beta, after glide typing outputs a word, tapping the delete key only deletes one character, it used to deleted the whole word in v0.13.3

#### Steps to reproduce
1. Glide type some word
2. Tap delete key
3. Only the last character is deleted

#### Environment information
- FlorisBoard Version: v0.13.4beta09
- Install Source: Fdroid
- Device: OnePlus 7T
- Android: 11

**Comment by stephenhawk8054** [comment]
I second this, this is so important to me

**Comment by TheHawaiianKoala** [comment]
I have pointed it out on the dicussion about [v0.3.14](https://github.com/florisboard/florisboard/discussions/1235#discussioncomment-2148960)

**Comment by Penguin-Guru** [comment]
Very much agreed.

**Comment by soulmist7** [comment]
This is a huge issue for all of us, because glide typing often misunderstands the word trying to be swiped. 

In addition, I am finding that in the latest version (0.3.14(75)) often times swipe typing does NOT put a space in front of words if you manually typed the letters to that last word. This is a new bug that wasn't there in the last version.

**Comment by patrickgold** [comment]
Thanks for your bug report!

Above linked PR fixes the issue, by default the delete key deletes the glided word when pressing delete after the glide input. Will be released in 0.3.16-beta01.
