### ISSUE TITLE
Show glide trail for normal gestures

### ISSUE THREAD

**Issue by BrudiBanani** [florisboard/florisboard#1543]
Make a toggle in preferences to show/not show glide trail for normal gestures when glide typing is deactivated.

Would be a cool feature in my opinion.
Thanks for considering it :)

**Comment by Glitchy-Tozier** [comment]
Personally, I think this might be confusing for users, as there would be no visual distinction between performing a gesture and using glide typing.

**Comment by BrudiBanani** [comment]
That is why i proposed to allow switching it on/off via switch in preferences and only if glide typing os deactivated.
Maybe i could not make that clear in first place. Sorry

**Comment by Glitchy-Tozier** [comment]
No worries, your proposal was clear. I just thought I'd voice my thoughts on the idea in general.  :)

**Comment by patrickgold** [comment]
Thanks for your proposal!

Personally I do not like this idea too much (even optionally), because the glide trail is a distinctive element of glide typing, and I haven't seen it being used anywhere else. A "normal" gesture is always invisible, at least in the apps/keyboards I know and use. (If you have an app which does that though feel free to share it with me, so I may get inspired by its implementation)

Additionally from a technical perspective I am also not too happy because glide typing and gestures, as unified as they may look like from a user perspective, are completely different and independent things in the keyboard logic, thus it would further complicate things with regards to render a normal gesture's trail.

With above reasoning I think I will reject this proposal, I hope you can understand!
