### ISSUE TITLE
[BUG] Keyboard lagging on a more recent kernel

### ISSUE THREAD

**Issue by Midou36O** [florisboard/florisboard#1588]
#### Short description
The keyboard lags on a more recent kernel [this mostly affect custom kernels]

#### Steps to reproduce
1. Flash eureka kernel
2. Type fast on a note keyboard
3. Notice the lag
4. enjoy != True

#### Environment information
- FlorisBoard Version: 0.3.14-beta11 (67)
- Install Source: F-droid
- Device: Samsung Galaxy A30s
- Android: 11, OneUI 3.0

#### Media:
Old kernel:

https://user-images.githubusercontent.com/45198486/154856320-ac338aa5-47d8-42f1-8697-68d5ecda21c4.mp4

New kernel:

https://user-images.githubusercontent.com/45198486/154856277-95c148f5-f98c-43d9-a3e4-a87944f9b454.mp4

**Comment by tsiflimagas** [comment]
Thanks for your report. The problem about latency between typing and input is known, so I don't think it depends on anything else other than the keyboard itself (not that there couldn't be concurrent causes). Are you sure you never noticed any such lag previously? The reason why you noticed it after flashing another kernel, I think is that it's still early after boot or you've just not used FlorisBoard yet, so system hasn't optimized it yet@. At least for me, when I cold start FlorisBoard, it lags for a while, and after that period it works normally.
Even if it really was a problem related to the new kernel though, then I'm pretty sure that this would not have to be any of FlorisBoard's concerns, since you're using an aftermarket piece of software, the quality of which can't be ascertained here.
With these said, I suggest you to try observing if you're experiencing the known issue I mentioned in the first paragraph (thus observe if the lag goes away after a while).

**Comment by Midou36O** [comment]
Thanks for responding. I have been using FlorisBoard for 5-6 months now, i'm pretty sure it isn't really a problem of optimisation, as of the cold boot case, the old kernel runs florisboard with no lag at all (right after BFU), but to make sure i did wait for 30 minutes and the same issue still occurs.

**Comment by tsiflimagas** [comment]
I forgot to mention that the lag issue was introduced in version 0.3.14-beta07, so if you recently jumped on the latest builds, you may didn't have enough time to notice it.
You can try something to kinda fix the issue. Try running `adb shell pm bg-dexopt-job dev.patrickgold.florisboard.beta` over adb or `pm bg-dexopt-job dev.patrickgold.florisboard.beta` on your phone if you happen to have root access, force restart the app and see if it works normally. If this works, then I'm pretty sure your issue is the known one.

**Comment by Midou36O** [comment]
Running that command doesn't change anything :P

**Comment by lawson85** [comment]
> Running that command doesn't change anything :P (Force restarted the app too)

This explains it and maybe you need to apply it to all apps: https://github.com/KelvinCrag/Optimizer

Have you followed steps at dontkillmyapp.com just in case there's a setting on your device causing issues?

**Comment by Midou36O** [comment]
I did the steps and applied the patch to all the apps, actually i realised termux does not suffer from input lag, only other apps and the system UI

**Comment by Midou36O** [comment]
For reference:

https://user-images.githubusercontent.com/45198486/156885105-d0488e4a-0eb6-4ce1-a4bc-ffc4fb21544b.mp4

You can see termux's terminal does not suffer (little to no lag) while the text field does have lags.

**Comment by Midou36O** [comment]
Recently went back to florisboard and it seems that the bug have been fixed. (no latency so far!) So i will close this issue unless this happens again. 
(Same kernel and same device as when i reported the bug)
