### ISSUE TITLE
Navigation bar for settings preferences

### ISSUE THREAD

**Issue by GoRaN909** [florisboard/florisboard#1634]
Hi @patrickgold i like to use this great full feature keyboard with a nice modern material UI/UX style i suggest to this project to use bottom navigation bar like we had on old version of FlorisBoard it will be great if you implement it again to the new UI here is a good library to use if you wanted to re-implement navigation bar like before.

This is two good library: Kotlin programming language

1- [Chip Navigation Bar](https://github.com/ismaeldivita/chip-navigation-bar)

2- [Smooth Bottom Bar](https://github.com/ibrahimsn98/SmoothBottomBar)

Some screenshots of library :) 

1- Chip Navigation Bar: This library is support both Vertical and Horizontal direction

Horizontal: 

<img width="350" src="https://github.com/ismaeldivita/chip-navigation-bar/raw/master/art/h.gif"/>

Vertical:

<img width="350" src="https://github.com/ismaeldivita/chip-navigation-bar/raw/master/art/v.gif"/>

2- Smooth Bottom Bar:

<img width="350" src="https://cdn.dribbble.com/users/1015191/screenshots/6251784/snapp---animation.gif"/>

**Comment by tsiflimagas** [comment]
One of the main points of the settings UI rework was to switch away from the bottom bar to a list. A bar couldn't contain all those elements. So, if I'm not wrong in this, I don't see this happening.

**Comment by patrickgold** [comment]
Thanks for your feature proposal!

The bottom navigation bar from 0.3.13 was one of the things which I wanted to purposely remove due to several reasons in 0.3.14:

a) It obstructs me from having the bottom "Preview your setup" field
b) Material guidelines state that a bottom navigation should not be used in the settings of an app, and FlorisBoard's app part is purely settings.
c) FlorisBoard offers so many options that a bottom nav bar just provides too less space to fit enough categories in there which make sense.

If I wanted to I could have included it again, the UI library (Jetpack Compose) offers great support for it already.

Which above reasoning I will reject the proposal, hope you understand!

**Comment by GoRaN909** [comment]
Oh now i knows the reason why you not using bottom navigation bar anymore in new UI thans for replying i understood 😶
