### ISSUE TITLE
AMOLED dark keyboard theme removed in 0.3.14

### ISSUE THREAD

**Issue by regaldude** [florisboard/florisboard#1702]
#### Short description
The AMOLED dark theme has been removed in 0.3.14

I have classified this a bug because the option was available in previous version and there is still an option to change settings theme to AMOLED dark.

#### Steps to reproduce
1. Update to 0.3.14

#### Environment information
- FlorisBoard Version: 0.3.14
- Install Source: Fdroid
- Device: Pixel 4a
- Android: 12

**Comment by tudos4** [comment]
Same for me i used an amoled themed borderless keyboard setup. I dont know how should i create a theme and i cant find the the setup i just mentioned in the default settings so i stuck with the greyish, bordered keyboard

**Comment by serebit** [comment]
Hopefully they'll get added back, I worked pretty hard on those themes.

**Comment by patrickgold** [comment]
All themes are still there, don't worry: https://github.com/florisboard/florisboard/tree/master/app/src/main/assets/ime/theme

Some just have not been ported over to the new extension+stylesheet format yet, thus they don't appear in the Theme Selection UI.

**Comment by patrickgold** [comment]
This issue is thus not only relevant for the AMOLED themes but also for the other missing themes. Primary reason is that themes were pretty volatile in the late beat releases and the feature API was not stable yet. As it is relatively stable now, I can port over all themes.

**Comment by tudos4** [comment]
> This issue is thus not only relevant for the AMOLED themes but also for the other missing themes. Primary reason is that themes were pretty volatile in the late beta releases and the feature API was not stable yet. As it is relatively stable now, I can port over all themes.

Thx that clears things up then i think i wait till they get ported.

**Comment by patrickgold** [comment]
Above PR is the working PR for re-adding the old default themes into the FlorisBoard core. Note that "Floris Black" was renamed to "Floris Pure Night", but other than that not too much should have changed.

The private mode rule has been ignored while porting, because it does not exist anymore. @serebit As you've created the Floris Black/Pure Night themes, could you have a look at them through the debug artifact if you notice any incorrect colors? Thanks in advance!

The GBoard themes may also be re-added, but not 100% sure yet, as they were not correct to begin with due to some limitations of the old engine. It may actually be easier to create those from scratch to match the current GBoard style.

These themes will be parts of tomorrow's 0.3.15-rc01 release and in a few days 0.3.15 stable.

**Comment by serebit** [comment]
Tested both, they look good to me!
