### ISSUE TITLE
Merged two clipboards together.

### ISSUE THREAD

**Issue by Pranab009** [florisboard/florisboard#1705]
Merged two clipboards together.
Normal press for last copied word
Long press for open clipboard.
Two clipboard buttons are confusing.
Please add this feature.

![Screenshot_20220326-172533_1](https://user-images.githubusercontent.com/65340361/160239428-899cd4c9-4747-4541-ac8f-65a8545eceac.png)

**Comment by tsiflimagas** [comment]
I'm not very sure about this. To me its quite straight forward the way it is now. Having a gesture, on the other hand, which won't have any indication, thus it will be hidden, is more confusing.

**Comment by Pranab009** [comment]
Actually one time I don't know about space bar swipe and delete key gesture.
Many things are hidden in many apps or everywhere.
If you want then add tour guide.

**Comment by tsiflimagas** [comment]
Nope, it's not the same. Those gestures are specifically configured in settings by users themselves. There's nothing hidden about them.
Except if the gestures you suggest are also added in the settings, which could be considered a bit of redundancy imo.

**Comment by patrickgold** [comment]
Thanks for your proposal!

I am not really convinced on this idea, because both are often needed, and nobody expects them to do something else when long pressing when within the Smartbar. Also these two icons use the Material standard icons, the one without something in it is the paste button (and that icon is really present throughout all apps), the other accesses the clipboard manager/history.

>  If you want then add tour guide.

UI should mostly be self-explainable. I know that FlorisBoard's UI has some corners where I need to improve feature discoverability and ease-of-use, but your proposal would be a step back in my efforts on that.

**Comment by Pranab009** [comment]
Ok.
Thanks for your reply.
Actually I see this feature in openboard.it depends on you ,add or not.
Otherwise your app is tooo good.👍
Work on it.

**Comment by patrickgold** [comment]
Yes OpenBoard does also have a clipboard history and it uses exactly the icon I also use. Just that it does not have a separate paste button.

**Comment by patrickgold** [comment]
I think I will reject this proposal, just because it makes no sense to me. When the Smartbar gets the ability to customize the button order and button visibility you can reorder the buttons to your likings.
