### ISSUE TITLE
Space bar ghost inputs sometimes

### ISSUE THREAD

**Issue by Takokeshi** [florisboard/florisboard#1706]
#### Short description
Space bar inputs ghost if your finger even just *slightly* drags onto the space bar while typing, resulting in no space bar input actually happening despite pressing it. It might only happen with space bar gestures disabled but I don't use those so I couldn't say.

#### Steps to reproduce
1. Install and use FlorisBoard 0.3.14
2. Disable spacebar gestures
3. Type with it for a while

#### Environment information
- FlorisBoard Version: 0.3.14
- Install Source: GitHub
- Device: Pixel 4a (5G)
- Android: 12.1, GrapheneOS

**Comment by tacohitbox** [comment]
Similar issue with
- Install source: F-Droid
- Device: Pixel 4
- Android: 12, Stock
- FlorisBoard Version: 0.3.14 (75)

**Comment by patrickgold** [comment]
Thanks for your proposal! I see where you are coming from and this a mix of both the gesture thresholds not being correct for your device, the space bar being ultra sensitive to gestures to allow for smooth cursor movements AND it ignoring "No action".

The third can easily be fixed, the second maybe a little bit but not too much and the first is a mystery, because it is absolutely difficult to find the best device screen density to threshold converter, which works for every device out-of-the-box.

Note that you could play around with the gesture thresholds in the gesture preferences and maybe it improves your situation, I cannot guarantee it though. Placing on the gestures bug list.

**Comment by Takokeshi** [comment]
Ahh sorry, I thought I had mentioned it. but tweaking gesture thresholds doesn't actually help, they don't make a difference whether they're all the way to the right or all the way to the left.

**Comment by patrickgold** [comment]
Ok that's unfortunate. I will try to add the "No action"-fix into the soon tbd 0.3.15 release though, so at least this part is fixed for you quickly.

**Comment by patrickgold** [comment]
Above commit fixes the "No action" being ignored by the space bar, and making a space bar swipe while space bar gestures disabled will now result in a normal space insertion.

As the gestures being buggy are tracked in other issues I will close this issue as fixed. Will be released in 0.3.15-rc01 tomorrow. Thanks again for reporting!

**Comment by tacohitbox** [comment]
Thank you for fixing it!

**Comment by Takokeshi** [comment]
Works beautifully ❤️
