### ISSUE TITLE
Can't restore backup data.

### ISSUE THREAD

**Issue by Pranab009** [florisboard/florisboard#1707]
#### Short description
Describe the bug in a short but concise way.

#### Steps to reproduce
1. Go to 'Setting'
2. Click on 'Advance'
3. Scroll down to 'Restore data'
4. Select 'Merge... or Delete...'
5. Select 'one option'
6. See 'file picker'
7. See 'can't show any option'

![Screenshot_20220326-175918_1](https://user-images.githubusercontent.com/65340361/160242469-ad20459e-649c-43ec-8f0b-25a859dfb753.png)
#### Environment information
- FlorisBoard Version:  0.3.14 (75) 
- Install Source: F-Droid
- Device: micromax in 1
- Android: 10,Stock

**Comment by tsiflimagas** [comment]
What's the extension of that file? Does its filename end with .zip?

**Comment by Pranab009** [comment]
Yup.
Here it is.
"backup_dev.patrickgold.florisboard_75_1648285554278.zip"

**Comment by patrickgold** [comment]
That's an issue in your system file picker. I explicitly state I want a file of MIME type `application/zip` in the file contract request, seems like it is unable to map that to `.zip` somehow.

This is supposed to help selecting files (and normally it works fine because you cannot just select an image for instance), but seems like I need to remove this restriction again.

**Comment by patrickgold** [comment]
I cannot really confirm the bug but know how to fix it for devices like yours, so I will still apply the `bug-confirmed` label

**Comment by patrickgold** [comment]
Above commit relaxes the media type restriction and now uses `*/**`(=all files). Thus after I release 0.3.15-beta02 later today you should be able to import backup archives again.
