### ISSUE TITLE
Copy and select all not working in dialog

### ISSUE THREAD

**Issue by rancidfrog** [florisboard/florisboard#1713]
Version 0.3.15-beta01
When using fx file explorer, in rename dialog the options to copy and select all do not function:
![](https://i.imgur.com/4M62Ltc.jpg)
I was renaming file,
![](https://i.imgur.com/JD1t7XI.jpg)

**Comment by Glitchy-Tozier** [comment]
Thank you for your bug-report!

Do the options activate themselves if you manually deselect and then reselect the text?

**Comment by patrickgold** [comment]
This could very well be another issue with the target app reporting incorrect cursor positions. Like Glitchy asked, would be interesting to see if manual selection changes trigger anything here.

**Comment by rancidfrog** [comment]
No.
Unlike in chrome based browsers, the workaround by deselecting or clicking arrow keys does nothing.
Select and copy are unchanged.
But, the pop up system copy paste does appear.
![](https://i.imgur.com/REbKRtC.jpg)
If I cut using the popup, paste works on floris, but select all and copy remains unselectable.

**Comment by patrickgold** [comment]
With the latest improvement in debugging tools I just discovered that FX File Explorer identifies itself as a raw input editor, which means no rich text services nor selection nor composition is possible:

![image](https://user-images.githubusercontent.com/19412843/167508819-71980733-15f0-4860-9e99-1800099d57a3.png)

Relevant EditorInfo delivered to the IME (FlorisBoard):

```
2022-05-10 00:28:04.886 9192-9192/dev.patrickgold.florisboard.debug I/FlorisImeService: onStartInputView() - restarting=false info=android.view.inputmethod.EditorInfo
    packageName: nextapp.fx
    ---
    inputType: class=0x00000000 variation=0x00000000 flags=(none)
    imeOptions: action=IME_ACTION_DONE flags=(none)
    privateImeOptions: (null)
    ---
    actionId: IME_ACTION_UNSPECIFIED
    actionLabel: (null)
    contentMimeTypes: []
    extras: (null)
    hintLocales: (null)
    hintText: (null)
    ---
    initialCapsMode: flags=(none)
    initialSelStart: 0
    initialSelEnd: 4
```

Tested and confirmed also with Gboard, OpenBoard, SwitfKey, etc. This means that this is clearly an issue of FX File Explorer.

To fix this the devs of FX File Explorer must send an EditorInfo with an inputType of TEXT (or similar, just never ever 0x00000000 for a rich input field, this means NULL and indicates that this input field is very very basic, terminal-like). The other EditorInfo fields (action, initial selection, ...) are sent correctly, but this is still overwritten by the fact that the inputType is 0x00000000.

Please forward this to the devs of FX File Explorer (link them here or copy the log), so they can have a look and fix this bug. Closing as this issue is not FlorisBoard-related.
