### ISSUE TITLE
Spacebar lagging/not giving input

### ISSUE THREAD

**Issue by Avezamal** [florisboard/florisboard#1715]
Generally typing with the keyboard shows that the spacebar sometimes does NOT input, this is incredibly frustrating since it means words don't get separated, this is the only issue I've had so far, I've disabled gestures and keyboard double tap for punctuation, and it's been the same, please look into it.

How to reproduce;

Just type normally.

Android 11 , OnePlus 7T

**Comment by Glitchy-Tozier** [comment]
Hello and thank you for your bug report.
Please provide the full environment information. What version of FlorisBoard are you using?

**Comment by Avezamal** [comment]
0.3.15-beta01 (76)

**Comment by Glitchy-Tozier** [comment]
Thank you, let's see what Patrick thinks when he gets around to inspecting this issue.

**Comment by Takokeshi** [comment]
#1706

**Comment by patrickgold** [comment]
#1706 has just fixed an issue with ghost input, so when 0.3.15-rc01 comes out tomorrow could you check if this helps for your particular issue? Thanks!

**Comment by Avezamal** [comment]
You got it.

**Comment by Takokeshi** [comment]
I do believe this could be a different issue. I'm getting missed spacebar inputs intermittently still, on 0.3.15-rc1. Unfortunately I wouldn't be able to pinpoint a cause for this one :/

**Comment by Avezamal** [comment]
> #1706 has just fixed an issue with ghost input, so when 0.3.15-rc01 comes out tomorrow could you check if this helps for your particular issue? Thanks!

Still having issues unfortunately, feels less prevalent than before.

**Comment by Takokeshi** [comment]
It's weird because only the space bar has issues. None of the other buttons do this. So I guess I'd focus on what makes the space bar different, in terms of programming.

I've noticed it only really happens if you're typing fast. If I pace myself a bit then it doesn't happen too much. But if you quickly tap between letters and space bar randomly, you'll notice it skipping a lot of spaces.

**Comment by Avezamal** [comment]
Yeah and I'm a pretty fast typer I guess that's why I picked this up

**Comment by patrickgold** [comment]
> It's weird because only the space bar has issues

The delete key sometimes has similar issues to the space bar. What makes them somewhat different from the other keys is that they are mare sensitive to allow for finer control to text selection. This also means when you type fast your finger tends to slip slightly on keys and that gets picked up as gesture instead of a key press.

Still I cannot just make them just normal sensitivity and call it a day, because this would re-enable issues with too slow text selection.

It is a tricky situation and I will have to play around a lot to improve gesture interference in the space bar.

**Comment by Takokeshi** [comment]
No, that was the issue from #1706. This one happens with gestures disabled.

**Comment by patrickgold** [comment]
Ok then this bug is more like that the input logic "swallows" fast key presses, and it is most noticeable in the space bar?

**Comment by Takokeshi** [comment]
I doesn't really affect other keys, only space bar. In my case at least.

**Comment by blinkenlicht** [comment]
I have the same experience since the major update (newest relese, guestures disables, Android 9, Xperia XA2) - have tried for some time now to understand the characteristic of this lag, but it's hard to put your finger on it (lol). 
If it were a shooter game, I'd say the hitbox somehow became smaller, that's a bit what it feels like.

**Comment by Avezamal** [comment]
Has anyone figured a fix?

**Comment by blinkenlicht** [comment]
I found that if you don't define any guestures that involve the spacebar, you are typing fine.

**Comment by Takokeshi** [comment]
I specifically had gestures disabled for each four directions on the space bar, Before 1a4118d it would eat inputs anyway, after that fix left/right work properly but up/down still eat input.

**Comment by patrickgold** [comment]
I experimented a bit with this bug and detected that first the gesture detector was once again comparing pixels and display-independent-pixels, thus the gesture detection is completely fine on one device and broken on the next. This is now fixed, I hope that I did not break something else with this change.

Secondly I now adjusted the space bar behavior and increased the hitbox downwards. This means that, provided space bar gestures are disabled, no input should be eaten anymore, regardless in which direction you swipe on the space bar. The only exception is if you swipe so much upwards that you land on a character key that character will get inserted (or nothing happens rarely too, I think this happens if you enter the character touch bounds and release simultaneously).

Could some of you please try out the debug APK of above PR and give feedback how both normal gesture actions and the space bar behave now? You can get the debug APK [here](https://github.com/florisboard/florisboard/pull/1793/checks) (click on Artifacts > app-debug.apk), it will then install separately and not alter your main/beta installation at all. Thanks in advance!

**Comment by Takokeshi** [comment]
Works perfectly here, thank you for the fix

**Comment by Takokeshi** [comment]
Also sorry, I only really thought to test that the space bar worked fine with gestures disabled, only realized now that you wanted feedback on gestures as well 😬 I didn't read properly, sorry.

Left/right gestures seem to be working properly, Up gestures don't really work though (it only inputs a space no matter what.)
