### ISSUE TITLE
Removing ß from the german qwertz keyboard 

### ISSUE THREAD

**Issue by BlackWolfWoof** [florisboard/florisboard#1746]
👋I have recently switched to FlorisBoard and came from GBoard. I noticed me not hitting the bottom row of keys right because of the ß being there.
This might just be a me issue, but it would be amazing if we could either hide the ß by making a second version of the german qwertz keyboard, or hiding it all together.
I have been long pressing s to pull up the ß before so removing it from the keyboard shouldn't negatively affect germans much and people switching from gboard will probably appreciate this too.

![Screenshot_20220404-180620.jpg](https://user-images.githubusercontent.com/29355595/161586478-4afaba86-5665-4ac9-8956-208073ad9c2f.jpg)
![Screenshot_20220404-180628.jpg](https://user-images.githubusercontent.com/29355595/161586502-ed07f37a-6875-437c-be98-ec447c397de7.jpg)

Here the 2 screenshots as comparison :)

**Comment by m-koushan** [comment]
Since there is a high chance that some people are using it, I will add a second layout for it with German2 name and you can use that instead

**Comment by m-koushan** [comment]
I checked the files and find out if you select `QWERTZ` in Characters layout section instead of `German (QWERTZ)` the `ß` will be removed and you can write it with holding `S` key
no need to add new layout at all

**Comment by m-koushan** [comment]
I see, ok I will work on it

**Comment by ronidee** [comment]
> That is true, but several other keys like Ü Ä and Ö simultaneously also get removed.

That sounds awesome! But it doesn't work for me anymore in the lastest verison. 👎 I find it to be super annoying to have so many chars in a row on such slim devices like smartphones. Is there some other way to remove "äöüß" alltogether while still maintaining QWERTZ **and** the default long-press popup option to be ä/ö/ü respectively? I've set long-press delay to 150ms so I enter äöü by long pressing aou. 

For now I downgraded to the previous version. Maybe instead of the gboard layout you could simply add one option like "language specific keys" where you have a list of chars with checkboxes for which chars you'd like to enable (I'd deselect all for example).

Thanks for your awesome work!
