### ISSUE TITLE
Korean keyboard, I seem to not be able to form  ㅚ ㅘ ㅟ ㅢ ㅟ ㅘ ㅝ ㅞ

### ISSUE THREAD

**Issue by Jirafey** [florisboard/florisboard#1755]
Florisboard Korean how to form them or were they never implemented. ㅚ ㅘ ㅟ ㅢ ㅟ ㅘ ㅝ ㅞ

**Comment by Hayleia** [comment]
These were indeed not implemented. The goal was only to be able to type full syllables so you can type 외 와 위 의 위 와 워 웨 but not ㅚ ㅘ ㅟ ㅢ ㅟ ㅘ ㅝ ㅞ.
Probably not too hard to do I guess since there are already maps that describe direct compositions here? https://github.com/florisboard/florisboard/blob/master/app/src/main/java/dev/patrickgold/florisboard/ime/text/composing/HangulUnicode.kt#L20

**Comment by Jirafey** [comment]
Can I somehow download the version with this added? Or should I just wait for the update on the beta version on IzzyOnDroid? Thank you so much for such a quick fix and response, have a good day!

**Comment by Hayleia** [comment]
I think yes. Click the linked pull request above, Then somewhere at the bottom click "Show all checks" then "Details", then somewhere on the left click "Summary" and at the bottom there is "app-debug.apk" and I hope that's what you're looking for.

**Comment by Jirafey** [comment]
ㅢㅝㅘㅚㅞㅙ  You are amazing! Thanks to you we have a proper Korean private keyboard :) ありがとございます
