### ISSUE TITLE
After long time of not using emojis, It will take time for them to appear

### ISSUE THREAD

**Issue by z0xrv** [florisboard/florisboard#1770]
#### Short description
If i try not to use emojis and then use them, it will get stuck for roughly 10 seconds and then appear

#### Steps to reproduce
1. Do not use emojis for 1 hour
2. Try use emojis
3. See error, keyboard will get stuck for 10 seconds.

#### Environment information
- FlorisBoard Version: 0.3.15-rc01 (78)
- Install Source: F-Droid
- Android: 7.0

**Comment by z0xrv** [comment]
@patrickgold  is this bug addressed?

**Comment by patrickgold** [comment]
Above commit/PR should significantly improve emoji startup time, and also reworks the way, how I utilize EmojiCompat internally. Note that on old devices opening the emoji view is never instant, but speeding things up once everything of emoji is loaded is very difficult to impossible due to the complex logic behind checking emoji support and so on.

If you want, you can try out the debug artifact of above PR (installs separately) and give early feedback. I will release this fix in 0.3.16-beta03.
