### ISSUE TITLE
Use rounded icon

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#1785]
These are some places where it's necessary:
For Fdroid to display the correct icon, you have to create it yourself and place it inside metadata. [See location in my project](https://github.com/Glitchy-Tozier/githo/blob/main/fastlane/metadata/android/en-US/images/icon.png)

![Screenshot_20220413-084947_F-Droid.jpg](https://user-images.githubusercontent.com/59611881/163117080-62d6fde7-94e5-4945-ab23-3b2b0e5f812b.jpg)
![Screenshot_20220413-084814_GitHub.jpg](https://user-images.githubusercontent.com/59611881/163117091-aec06113-e2d7-4d22-bb4a-4ceda2618279.jpg)

**Comment by BloodRaven0** [comment]
Okay, not a problem at all to render a png, just tell me what shape and what resolution you want them at. Also, the main icon only or all three?

**Comment by Glitchy-Tozier** [comment]
Let's see what @patrickgold  says!  :)

**Comment by patrickgold** [comment]
I mean we can make the F-Droid icon rounded, but generally this is the job of the app store UI to make the desired rounding and shadows, see https://developer.android.com/distribute/google-play/resources/icon-design-specifications

I suspect that F-Droid does not apply above steps though because they allow for any form of icons for the apps. The biggest problem is that the Fastlane metadata is synced with F-Droid and GPlay and I need an unformatted form for GPlay, so I think I will leave the icon here as it is.

I agree though that the icon in the README title could and should be rounded and here it is the app maintainers job (so me xd) to do so. In this case we could go for rounded corners, maybe the "squircle" format (20% of icon size as rounding and 512x512 pixels image size).

**Comment by patrickgold** [comment]
I just checked Aurora Droid (alternative F-Droid client) and it for instance applies their own shape for full bleed icons. Exactly this is what GPlay does too, just a bit of different rounding size. But still, my point is that the app icon should be the base form in the metadata and the app store UI must decide the shape itself.

**Comment by Glitchy-Tozier** [comment]
I understand your reasoning.
It's a shame that F-Droid tends to ignore certain basic issues for a long time.

**Comment by patrickgold** [comment]
I agree that it's an issue in the F-Droid client, however one must also say that the whole F-Droid team has a lot of things to do and must ensure the whole thing keeps running, so making icons rounded probably isn't their main priority.

I don't even know if this has been suggested to them or if it is on purpose like it is now, so maybe we can make an issue in the fdroidclient repo and check the status on this topic.

**Comment by BloodRaven0** [comment]
[FlorisBoard_Renders_512.zip](https://github.com/florisboard/florisboard/files/8481512/FlorisBoard_Renders_512.zip)
Here, I rendered the 4 most common icon shapes (Square, Rounded square, Squircle and Round) on each version of the icon (Stable, Beta, Debug), using the latest icon, at 512x512 resolution. Hope this helps!
I got the shape templates from here: https://scribe.rip/google-design/designing-adaptive-icons-515af294c783
(just scroll down until you get to the links, I worked with the Affinity one)

By the way, I've used a bunch of F-Droid frontends, including F-Droid, Aurora Droid and Droid-ify, and not one of them enforced any icon shapes for me. In fact, most of the icons don't even load for me, it's really annoying.

**Comment by Glitchy-Tozier** [comment]
I have to admit, my post was partally motivated by another (more frustrating) problem.

If you ever wish to change your screenshots, DO NOT do something like replacing `1.jpg` with `1.jpeg` or `1.png`. Keep the file's name exactly the same.

**Comment by patrickgold** [comment]
> If you ever wish to change your screenshots, DO NOT do something like replacing 1.jpg with 1.jpeg or 1.png. Keep the file's name exactly the same.

What does happen then? Are the new screenshots not accepted / missed?

**Comment by patrickgold** [comment]
> Here, I rendered the 4 most common icon shapes (Square, Rounded square, Squircle and Round) on each version of the icon (Stable, Beta, Debug)

Perfect, thanks a lot <3

> I got the shape templates from here:

That's a good source, afaik even Google recommends using this as the designing baseline.

> not one of them enforced any icon shapes for me

Interesting. I don't know Droidify, but interesting that AuroraDroid behaves differently for you than for me. But like I said, this issue hasn't too much priority IMO, and there are other more fundamental things to implement/fix.

> In fact, most of the icons don't even load for me, it's really annoying

Yep that's also an issue and by far more annoying and fundamental. I've read through quite some discussions on GitLab and it is caused by their image library and sometimes too high server load, and probably some other issues as well. Interestingly it doesn't always happen, so the server load thing must be a pretty high factor in this problem. But to F-Droid's defense at least in the official client it has improved in the last year by a lot and they understandably just don't have remotely the resources and money to have the servers Google or some other big corporation has.

**Comment by patrickgold** [comment]
Ok that screenshot confused me so much initially. Those are both icons in the metadata for the latest release:
https://github.com/florisboard/florisboard/blob/v0.3.15/fastlane/metadata/android/en-US/images/icon.png
https://github.com/florisboard/florisboard/blob/v0.3.15/fastlane/metadata/androidbeta/en-US/images/icon.png

But I think I have a good idea what's going on here:

For the resolution diff, I think maybe Izzy is trying to save storage space by compressing images and icons, and it would make sense because Izzy's repo is hosted on his own servers and storage space is expensive. Also the resolution part is consistent across all clients, stable sharp and beta compressed, so this is repo-dependent.

Then the rounding diff is a very very mean bug: I think that Droidify calculates rounded corners not in percentage (10% for instance), but in raw pixels. This means it expects icons to be 512x512 pixels and defines the wanted border radius as a constant. The stable icon is the expected size and its corners look good. Then there's the compressed beta icon, which may only be 64x64 (guessing here, but you get the point). But it still uses the raw pixel radius constant of the 512x512 assumption, processes this on the bitmap and then displays it. The result: above screenshot.

The rounding is not repo-dependent and only done in the Droidify client afterwards, because in the official F-Droid client you can clearly see that both beta and stable are squares.

Note that above is the idea based on my previous fun experience with such bugs, but it could also be something entirely different.

**Comment by Glitchy-Tozier** [comment]
> What does happen then? Are the new screenshots not accepted / missed?

Oh, they are accepted. All of them. You'll be stuck with the old screenshots next to the new screenshots for as long as the bug isn't fixed. (Which hasn't happened during the last few years)

See Githo in Fdroid for an example.

**Comment by Glitchy-Tozier** [comment]
Well, I think I can close the issue.

**Comment by patrickgold** [comment]
> Oh, they are accepted. All of them. You'll be stuck with the old screenshots next to the new screenshots for as long as the bug isn't fixed. (Which hasn't happened during the last few years)

Ah I see now, that's very good to know but understandably really bad for you. Interestingly on the browser the old screenshots are just 1x1 pixels, and thus you don't see the old ones. On the F-Droid client app however, well, they are annoyingly really duplicate.

**Comment by Glitchy-Tozier** [comment]
> Interestingly on the browser the old screenshots are just 1x1 pixels, and thus you don't see the old ones.

Yep, I changed them to 1x1 pixels in an effort to hide the old screenshots. It's interesting that the app ignores them and still uses the old screenshots instead of the 1x1s

**Comment by patrickgold** [comment]
> Yep, I changed them to 1x1 pixels in an effort to hide the old screenshots. It's interesting that the app ignores them and still uses the old screenshots instead of the 1x1s

Ah so it was you who made them 1x1, thought it was some kind of hacky delete by the F-Droid metadata server.

I now also know why the images where duplicate, try clearing the cache of the client and your 1x1 images will be big white boxes... This bug is not only present in the official client, but in all of the alternatives as well. The only place where it is correctly delivered is on the F-Droid website, where it is a peaceful 1x1 and not noticeable.

**Comment by Glitchy-Tozier** [comment]
> Ah so it was you who made them 1x1, thought it was some kind of hacky delete by the F-Droid metadata server.

Yeah, it was my hacky doing.

> I now also know why the images where duplicate, try clearing the cache of the client and your 1x1 images will be big white boxes... (I am not sure but I think the screenshot base color is white and it upscales one transparent pixel on a white background)

Interesting, you're right.

Btw, what exactl, is an app's cache as opposed to the app's storage?

**Comment by patrickgold** [comment]
> Btw, what exactl, is an app's cache as opposed to the app's storage?

Each app has an app data dir, and in that there's a structure similar to below's:

![image](https://user-images.githubusercontent.com/19412843/163266067-e0353fde-64b8-44dd-b4fe-0abb10463f08.png)

So if you clear the cache, everything in `cache` and `code_cache` gets deleted, all other directories are considered storage.

Also cache=temporary and on low disk space the system will delete the cache of unused apps by itself, the storage part is considered permanent unless you uninstall or clear the app storage.

> I think the "increase key hitboxes according to the most probable next letters"-idea would be a good thing to tackle once word suggestions are back in place.

I agree, smart hitboxes would def be cool. But one thing at a time :)

**Comment by patrickgold** [comment]
Also something related to the original request: The app icon in the README.md is now rounded-corner, after trying all 4 different renders out I decided the rounded-corners one looked best. Again thanks for the renders BloodRaven0!
