### ISSUE TITLE
I cannot set the number row to other then arabic or arabic western i miss the numbers 

### ISSUE THREAD

**Issue by Niklasw99** [florisboard/florisboard#1820]
#### Short description
Describe the bug in a short but concise way.

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

#### Environment information
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android:

**Comment by tsiflimagas** [comment]
When opening an issue, you should fill in all the required information, and describe the problem extensively enough under the dedicated field. Title is not the place to put all the text you intend to, it's just the title, otherwise others have a hard time to get what you want to report.
About your issue, I don't know why this is happening. There are many different number row layouts available. Do you only see two options? And are you sure you're looking at the right option?

**Comment by patrickgold** [comment]
Closing as this issue template was not filled out and based on the title I cannot really pinpoint nor reproduce any incorrect logic/UI. If any new info can be provided we can re-open this issue.
