### ISSUE TITLE
Hold shift to capatalize

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#1834]
#### Short description
Hold shift to capatilize does not work since version 0.3.16-beta01

#### Steps to reproduce
1. Long press on shift
2. Capitals show briefly, but go away when I let go of shift

#### Video

https://user-images.githubusercontent.com/50382414/167293837-0eb7f14f-eae7-4003-be6c-d35ffba1a0b5.mp4

#### Environment information
- FlorisBoard Version: 0.3.16-beta01
- Install Source: f-droid
- Device: Xiaomi Mi 9T Pro
- Android: Android 10 (lineageos without google)

**Comment by BurnyLlama** [comment]
This is also the case on my OnePlus 6 running stock ROM. Android 11.

**Comment by patrickgold** [comment]
Thanks for your bug report!

Above commit/PR fixes the issue, there was conflicting logic in the shift long press logic which resulted in the shift to cancel instead of finish correctly. Will be released in 0.3.16-beta02.

**Comment by patrickgold** [comment]
> Nice work!

Thanks!

> A little thing I noticed is that on custom themes, when enabling caps lock, the shift key symbol doesn't change colour (it does on built-in ones).

Yes I am aware, this is because of commit https://github.com/florisboard/florisboard/pull/1832/commits/afc6f21a6a17f8f24ae8b97ede4f44cc9ccb9887 in #1832, where I renamed the old `InputKeyMode` to `InputShiftState`. For themes `mode` got changed to `shiftstate`, thus rules with the old modes name don't color correctly for the new shift state system.

As I don't really have a migration option to auto-change custom themes this is something which needs to be manually done, sadly (by re-selecting the correct shift state in the rule editor dialog for the caps fg color). This is the only change theme-wise in 0.3.16 however, so in the end not that tragic.
