### ISSUE TITLE
[Feedback] Telex Composer for Vietnamese

### ISSUE THREAD

**Issue by quyleanh** [florisboard/florisboard#1841]
#### Description
Feedback for Telex Composer for Vietnamese keyboard implemented in #1797 
Since @thanhhocse96 use the brute force table for checking, there will be some cases which is not considered. I will try to test and list up in this issue.

#### List of missing cases

* Normal mark tone
Oiư --> Ơi
Phucs --> Phúc
Phưcs --> Phức
Did --> Đi
Đưcs --> Đức
Vọư --> Vợ
Đêù --> Đều
Lucs --> Lúc
Qúa --> Quá

* Change the tone
Sàngs --> Sáng
Hỏì --> Hòi
Hảf --> Hà

**Comment by thanhhocse96** [comment]
OK, I will do analysis for this case, and brute force all missing rules

**Comment by patrickgold** [comment]
Thanks a lot for the feedback and your efforts to further improve Telex! If you are already fixing some issues, could you also have a look at #183? The non-tonal diacritics already work perfectly fine, however I think there are some inconsistencies with the tone markings.

**Comment by thanhhocse96** [comment]
Somehow I see the implementation by using "dictionary" (sorry, I'm python user) load from JSON make our work become hard. We all must build the whole Telex dictionary, and predict all user cases to cover it. 
So my job now: I'll add the rule to change tone-marks and modify-marks.
BTW: Vietnamese is so annoyingly complicate, whatever we're native speaker or not

**Comment by quyleanh** [comment]
Should we check again the approaching method of creating brute force table?

I wonder how OpenKey check the input from keyboard to generate the correct word. Could you check on its repository? @thanhhocse96

**Comment by thanhhocse96** [comment]
@quyleanh The bruteforce approach not come from me at the first place, I've update the JSON dictionary made by @patrickgold base on issues #607 and #183.

At the moment, I'll add more rules to the dictionary, because I've just only know about Florisboard recently, so I don't know about the implementation or the model or any decisions made by the team. So the best way for us at the moment is improve the asset we have.

I'll lookup about OpenKey, LabanKey, Swiftkey to learn about their implementation, but maybe in the near future we don't have any PR about something like: "remodel the code for vietnamese telex"

**Comment by patrickgold** [comment]
> Somehow I see the implementation by using "dictionary" (sorry, I'm python user) load from JSON make our work become hard. We all must build the whole Telex dictionary, and predict all user cases to cover it.

I agree, it seems like the brute-forcing method is painful and a lot of work, and in Vietnamese also it seems like it is never ending... I think the best option would be to fix some missing cases that were reported using the existing method and make a small PR. After that we research the other IME's approaches to see if we can re-create Telex in a more dynamic way, which is not just a static dictionary.

If you need any assistance from me I will help as best as I can.
