### ISSUE TITLE
Right to Left Hints

### ISSUE THREAD

**Issue by RickyM7** [florisboard/florisboard#186]
Hints that are on keys from the middle to the right of the keyboard are shown from the right to the left. I don't know if this is the expected behavior, but if it is, please add an option to disable this and make them be shown from left to right as usual.

| RtL Hints (FlorisBoard) | Expected (Simple Keyboard) |
| :---: | :---: |
| ![bug](https://user-images.githubusercontent.com/24703825/104608632-e001de00-5660-11eb-8590-2bf37d790d05.jpg) | ![expexted](https://user-images.githubusercontent.com/24703825/104608590-d2e4ef00-5660-11eb-991f-7082b881d2fe.jpg) |

**Environment information**
- FlorisBoard Version: v0.3.2
- Install Source: GitHub
- Device: Redmi Note 4
- Android version, ROM: MIUI 11 (Android 7.0)

**Comment by patrickgold** [comment]
Thanks for your issue, Ricky! The implementation that the popup keys are aligned left / right leaning depending on the base key's position is expected. I chose to implement it this way because Gboard, OpenBoard and AnySoftKeyboard do it exactly this way, so I figured this is default behavior. Simple Keyboard seems to have different implementations for different locales, with great inconsistency even between different locales. The attached screenshot below is the `i` key's popup on Simple Keyboard with the pt-Br locale set on my device, which aligns the popup around the center...

I can of course add a toggle to change this behavior in the preferences, if you want me to. Maybe a "Left-only!, "Right-only", "Auto left/right" list preference, which allows you to set one of these values.

![Screenshot_20210114-183519](https://user-images.githubusercontent.com/19412843/104627571-7b15aa80-5697-11eb-93ee-69f692d84658.jpg)

**Comment by RickyM7** [comment]
> The implementation that the popup keys are aligned left / right leaning depending on the base key's position is expected. I chose to implement it this way because Gboard, OpenBoard and AnySoftKeyboard do it exactly this way, so I figured this is default behavior.

@patrickgold Yes, I just tested Gboard to confirm, and since that's the default behavior, it doesn't make much sense to create an option to change that. I'll close this issue now.
