### ISSUE TITLE
Smartbar Clipboard entries with url entry

### ISSUE THREAD

**Issue by jonas-w** [florisboard/florisboard#1889]
### This features does exist in the samsung keyboard and i switched from it to Florisboard, so this feature directly was on my wishlist. 
Basically the last thing in your clipboard pops up in the smart bar and if the last clip board item contains an url it will be a seperate item in smartbar.

For example this text in Clipboard: 'Look at this https://example.com'
Would look like this:
![](https://user-images.githubusercontent.com/32615971/171253798-110d9681-2a14-411d-bb14-d66df23d198f.png)
The first entry is the text in clipboard and the second entry is the url that is inside of the copied text

Having the last clipboard entry in the smartbar would be the first proposal and the second one would be some "smart" url entry

**Comment by patrickgold** [comment]
Thanks for your proposal!

Above PR adds support for clipboard item URL and Email detection. Each clipboard item is matched against a regex to filter out emails and URLs and these are added separately to the Smartbar. Note that these don't have fancy icons yet and just use the clipboard icon for now. This UI will get a new look soon anyways due to the word suggestions implementation.

Additionally within the clipboard history if a clipboard item is just purely a URL or email, it will add an icon above the clipboard item.

This change will be released in 0.3.16-rc01 soon.

**Comment by jonas-w** [comment]
Thank you very much!

**Comment by jonas-w** [comment]
Will this require the internal clipboard or also works with system clipboard?

**Comment by patrickgold** [comment]
It works perfectly fine with the system clipboard alone too (as I just suggest the last primary clip I get, and this can either be from the system or the internal clipboard if enabled).

**Comment by pacjo** [comment]
I didn't want to open another issue and this seams similar so I will ask here. 

Would it be possible to do the same for phone numbers? Like when you copy something like "Please call 34 377 00 00" it would detect "34 377 00 00" as a phone number and add it to smartbar suggestions.

**Comment by patrickgold** [comment]
Above linked PR adds phone number detection. Note that edge cases migh not be detected and that there may be some false positives, but in general the new detection system is very sophisticated. You can also play around and see the draft for the detection regex here: https://regexr.com/6qjfg

Will be released with 0.4.0-alpha02
