### ISSUE TITLE
App is crashing o x86_64 device

### ISSUE THREAD

**Issue by LeOS-GSI** [florisboard/florisboard#1892]
I'm runing LeOS-R-x86_64 OS (ungoogled Android 11). The app is crashing direct after start. Logcat isn't showing anything

**Comment by patrickgold** [comment]
That's because production builds are only compiled against `armeabi-v7a` and `arm64-v8a`, not `x86` nor `x86_64`. You can however have x86 support in production builds by compiling the app for yourself and by modifying the `build.gradle.kts` to include the `x86` and `x86_64` native static libraries too (or just use the debug builds which also supports x86, but they do a lot of debug logging and are slower than production builds).

**Comment by LeOS-GSI** [comment]
> That's because production builds are only compiled against `armeabi-v7a` and `arm64-v8a`, not `x86` nor `x86_64`. You can however have x86 support in production builds by compiling the app for yourself and by modifying the `build.gradle.kts` to include the `x86` and `x86_64` native static libraries too (or just use the debug builds which also supports x86, but they do a lot of debug logging and are slower than production builds).

Yes, that's was my idea, to build it for my own for x86_64.

My intention was only the point you on this missing feature. I think you should it include in next builds. Not all can compile it like I can/will do.

**Comment by patrickgold** [comment]
> My intention was only the point you on this missing feature. I think you should it include in next builds. Not all can compile it like I can/will do.

It takes three lines to include it in release builds, but it also almost doubles the APK size. The problem with APK size is that I cannot have a 30MB APK because then I will get a lot of complaints about the size for a very small user base that actually requires x86 support (and until now everyone who needed x86 support was tech-savy enough to compile it for themselves, so no need to think about this problem).

Although this _may_ change in 0.4.0 depending on how I implement autocomplete/word suggestions and if the underlying spell checker then does not require icu4c anymore.

**Comment by LeOS-GSI** [comment]
> That's because production builds are only compiled against `armeabi-v7a` and `arm64-v8a`, not `x86` nor `x86_64`. You can however have x86 support in production builds by compiling the app for yourself and by modifying the `build.gradle.kts` to include the `x86` and `x86_64` native static libraries too (or just use the debug builds which also supports x86, but they do a lot of debug logging and are slower than production builds).


Compile or better the floris-cc-icu4c.sh script isn't working. Til today I haven't had any issue with C compiler. But I'm sorry to say that I'm not that familiar with it. I see some clang errors in log. For example: 2 different errors with unknown argument or invalid argument. Are they from your script or is there something missing on my system. 
[config.log](https://github.com/florisboard/florisboard/files/8827980/config.log)

**Comment by LeOS-GSI** [comment]
I have build the x86_64 version and installed on my Laptop. It's working, but ... the OneHand mode doesn't work. Any idea how I can activate OneHandMode in landscape ?

If you want, I can share the x86 apk 


By the way, you can split the apks with this commands in build.gradle

`  splits {

    // Configures multiple APKs based on ABI.
    abi {

      // Enables building multiple APKs per ABI.
      isEnable = true

      // By default all ABIs are included, so use reset() and include to specify that we only
      // want APKs for x86 and x86_64.

      // Resets the list of ABIs that Gradle should create APKs for to none.
      reset()

      // Specifies a list of ABIs that Gradle should create APKs for.
      include("x86", "x86_64")

      // Specifies that we do not want to also generate a universal APK that includes all ABIs.
      isUniversalApk = false
    }
  }
}`

**Comment by patrickgold** [comment]
Sorry for the late reply.

> I have build the x86_64 version and installed on my Laptop. It's working, but ... the OneHand mode doesn't work. Any idea how I can activate OneHandMode in landscape ?

That's on purpose, because at the moment I only designed the UI for one-handed mode for portrait. Support for this in landscape will come when I so the landscape/tablet UI optimizations.

> By the way, you can split the apks with this commands in build.gradle

Ok that's true and I may do so after 0.4 if I keep ICU4C that causes this in the first place.

**Comment by patrickgold** [comment]
As for the original purpose of this issue, it is now resolved IMO, so if you don't have anything to add we can close it.
