### ISSUE TITLE
Gboard symbols

### ISSUE THREAD

**Issue by Archeix7** [florisboard/florisboard#1954]
Hi, you can add symbols like in gboard, there are more of them and so familiar

![IMG_20220713_095906_533](https://user-images.githubusercontent.com/51048550/178671287-88411ec1-3941-446b-bc79-c7e3b37b32b6.jpg)
Gboard

![IMG_20220713_095958_842](https://user-images.githubusercontent.com/51048550/178671331-ba636b7c-5b37-4ebb-8f76-a2bed78b2196.jpg)
Floris

**Comment by tsiflimagas** [comment]
How did you get hinted symbols on the top row in Gboard? For me it only shows them for the two bottom rows.
Other than that, that's because the symbols layout you use has only two rows on symbols and the third one is the number row. To achieve what you seek for, you can use the "Western (Additional Symbols)" symbols primary layout.

**Comment by Archeix7** [comment]
"How did you get hinted symbols on the top row in Gboard"
Idk, i ask friend make screenshot his gboard

"Western (Additional Symbols)"
Thank you
