### ISSUE TITLE
changable emoji style

### ISSUE THREAD

**Issue by vixpr** [florisboard/florisboard#1965]
UI to change emoji style in "Emojis" section. (Like Apple's or Telegram's emojis)

(idk if this is possible in a privacy-respecting way tho)

**Comment by patrickgold** [comment]
There is no emoji font style change option because it makes little sense. If you have a cool looking custom emoji style in the emoji keyboard and the app does not support it or uses another font, it is pretty much useless.

As such, FlorisBoard is automatically adapting its emoji style either to the app if it uses EmojiCompat (this allows an app to switch out the emoji style and FlorisBoard uses this) or to the system font, thus for most app the emoji style is in sync with the target app emoji style (one exception is WhatsApp for instance, but haven't found a solution for this and I don't think there is one).

So if you want a different emoji style you must switch out the system font, if your ROM supports this.

I hope you understand this technical limitation. If you can provide examples where it still makes sense for such toggle considering above limitations, I can reconsider this.

**Comment by patrickgold** [comment]
Yup it seems pretty much impossible, also because a lot of big company's emoji fonts are proprietary and thus I cannot use them at all. I will mark this proposal as rejected, should there ever be a way to adapt (what I don't think tbh) I will reopen this proposal though.
