### ISSUE TITLE
Allow switching between most recent and most frequent emoji

### ISSUE THREAD

**Issue by kleinarne** [florisboard/florisboard#1975]
The recent emoji panel provides quick access to the emoji that were recently used, and if the number of emoji shown is not too small, it shows all frequently used emoji, preventing me from having to dig through the other emoji panels.

However, with each emoji that I use, its sorting order gets changed around again, making it hard to find a specific emoji on that panel.

Switching the panel's sorting order from "most recent" to "most frequent" would dramatically reduce that problem, since it would result in a much more static order.

**Comment by patrickgold** [comment]
Thanks for your suggestion!

That's an interesting take on the recents panel and I haven't thought of this yet. I must say I really like the idea a lot (as a toggle-able or set-able mode besides the current mechanics). This requires a data structure rework of the `media__emoji_recently_used` preference though, as it currently does not store any data about the frequency of an emoji.

Adding to the list of emoji proposals.

**Comment by patrickgold** [comment]
Above linked PR adds both the features to pin emojis and to manually reorder emojis if set to manual order. While not 100% the feature you were asking for, this should resolve your issue of constantly changing emoji positions.

Adding a mode for sorting my most frequently used is not directly possible, because there are a lot of edge cases on emoji adding etc, which is not easily solvable and also in many cases do not make sense.
