### ISSUE TITLE
Configurable position or offset

### ISSUE THREAD

**Issue by ellul-ezra** [florisboard/florisboard#20]
Nice keyboard! Thanks for your work. An option to adjust the positioning and allow offsetting to accommodate curved screens would be nice. As it is, screen curvature cuts off a little of the lower left and lower right buttons. Cosmetic issue mostly.

**Comment by patrickgold** [comment]
Thanks for the positive feedback and the suggestion! I will definitely look into it next week, a fix for it should be in the next release (v0.2.2).

**Comment by patrickgold** [comment]
Above commit adds an option to define a bottom offset which allows to basically 'push' the keys up by the defined length so the curvature of the screen does not touch the key. May require a few tries before you get the perfect value for your device, but is the best solution I've come up because one can't read out the exact dimensions of the corners, only display cutouts like notches. Will be included in the next release (v0.2.2).

**Comment by ellul-ezra** [comment]
Wow, fab, look forward to trying it out in the next version. Thank you!

-------- Original Message --------
