### ISSUE TITLE
no space inserted after the previous word when glide typing

### ISSUE THREAD

**Issue by necropolina** [florisboard/florisboard#2007]
#### Short description
A space used to be inserted between words when glide typing, but that hasn't been the case since updating to 0.3.16

Forexample,thisiswhathappens.

#### Steps to reproduce
Unsure if this is unique to me or just a bug in this version.

#### Environment information
- FlorisBoard Version: 0.3.16
- Install Source: F droid
- Device: Pixel 4a 5g
- Android: Android 12/CalyxOS 3.7.0

**Comment by necropolina** [comment]
I see some related issues for swiping after single character inputs but for me it just isn't happening at all.

**Comment by patrickgold** [comment]
This has been reported by a few select users and this bug is different from the 1-letter space bug, which I introduced only in 0.4.0-alpha01. Until now I haven't really been able to find a common denominator or the source, and for me this bug is not reproducible on any of my devices, which makes it difficult to fix.

If possible, could you test the 0.4.0-alpha02 release from the IzzyOnDroid F-Droid repo (installs separately besides stable) to check if you can still reproduce this bug? Quite some stuff has changed since 0.3.16 in the spacing logic, thus it would be interesting to know.

**Comment by Factavi** [comment]
I am on a Pixel 5a and also have this problem. Using glide typing, no space is entered, and new words will "stack" on top of each other (e.g. "lookslikethis"). I tried switching to alpha04 and the issue is still present. It happens with default options as well as changes in language and layout. 

(Loving this app! Thank you!)

**Comment by necropolina** [comment]
Confirmed that 0.4.0-alpha02 fixes my issue.

**Comment by tsiflimagas** [comment]
Thank you both for confirming!
