### ISSUE TITLE
Poor switch divider visibility in settings ui

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#2032]
#### Short description
I just noticed the switch divider in the settings and it's a quite nice addition, but at the moment it's a little hard to discern. Well, it could be looking somewhat different on another screen, so you may want to check for yourself. For me, it looks okayish on white and dark themes, though it could still be more distinct, but on AMOLED dark I can't see it almost at all. I'm not sure if it's the color or the width that should be changed. By the way, I do realize it has to look discreet, so I'm proposing just a subtle change, nothing exaggerated. 

#### Steps to reproduce
1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

#### Environment information
- FlorisBoard Version: 0.4.0-alpha03
- Install Source: GitHub
- Device: Xiaomi Redmi note 8
- Android: 12.1, custom

**Comment by tsiflimagas** [comment]
I just wondered whether I should have opened this issue in the Jetpref repo🤔

**Comment by patrickgold** [comment]
Thanks for your bug report!

I have noticed this too that the divider is not that much noticeable in some conditions, don't really know why this happens because in general I just assign the color from the MaterialTheme as per Material specs. Either the FlorisBoard app theme is misconfigured or something else is wrong.

> I just wondered whether I should have opened this issue in the Jetpref repothinking

No this repo is okay, as the JetPref lib doesn't actually set the color but derives it from the app's MaterialTheme, in this case the FlorisAppTheme, and that's where the issue originates from I think.

**Comment by lm41** [comment]
Fixed with https://github.com/patrickgold/jetpref/pull/8
