### ISSUE TITLE
License Choice?

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#209]
I saw that the license used is the Apache License 2.0.
What was the thought-process behind this? What is the advantage over using something like the  GPL-3.0 License?

**Comment by Glitchy-Tozier** [comment]
(Also, an off-topic question that just interests me: Am I correct that patrickgold is the owner of FlorisBoard and that RickyM7 is just a very motivated guy who is awesome enough to do this in his free time? Or is FlorisBoard structured differently?)

**Comment by patrickgold** [comment]
My main reasoning was that that basically the whole Android ecosystem uses Apache 2.0 (of course there are apps that use different licenses), but especially the system components and the OS itself is just 100% Apache 2.0. GPL-3.0 was indeed the initial license FlorisBoard used but was changed very early to Apache 2.0, as I was not happy with the restrictions and legal complexity the GPL-3.0 license brought with it. Also I like the freedom of Apache 2.0, you can basically do whatever you like, as long as you give attribution to the original author and source.

> (Also, an off-topic question that just interests me: Am I correct that patrickgold is the owner of FlorisBoard and that RickyM7 is just a very motivated guy who is awesome enough to do this in his free time? Or is FlorisBoard structured differently?)

Yes, I, patrickgold, am the owner, lead dev, maintainer, etc. of FlorisBoard and do this project in my free time. RickyM7 is an awesome person whom I do not know personally but who has helped me **a lot** in testing debug builds of PRs and gave me many many suggestions to improve FlorisBoard  (and I assume he also does this fully in his free time).

Hope that I could answer your question!

**Comment by Glitchy-Tozier** [comment]
Yeah, perfect, thank you for the answers!

If you at some point have the time to tell me what the restrictions are that GPL-3.0 has, I'd be interested to hear them.
I thought this was _THE_ open-source license and everything else is more restrictive. I may have been wrong though.

**Comment by patrickgold** [comment]
Disclaimer: I am not a lawyer nor a license specialist, all of the points below are what I **think** I know about licenses:

- One of the most permissive licenses is the **MIT license**. Basically you allow for everyone to take your code, modify it and use it in either open-source of closed-source (commercial) projects, as long as somewhere in the Apps about screen it is mentioned that this product uses code (modified or not) written by you. This license though does not protect you from patent claims or anything, but if the app of the person who used your code crashes and there's some damage, you cannot be held accountable for anything.
- Then there's **Apache 2.0**. the coolest one in my personal opinion. It is almost as permissive as the MIT license, but you are protected from patent claims and such by others. Like in MIT, everyone can use your code in open- and closed-source (commercial) projects and you must be attributed as well as a copy of the Apache 2.0 license must be shipped. And it still protects you from any warranty claims, so you are 0% accountable for any damage your code does if it has a security bug or whatsoever.
- Then there's the **GPL-license** family, which I do not know that much about, but is far more restrictive for users who want to work with your code. Everyone who uses GPL-licensed code (this includes yourself too) has to include a full copy of the source code with the binary release. Which is a great idea but you just ship so much bigger file sizes of releases just because of this. GPL licenses were very popular years ago but its usage has gone down I think due to companies refusing to use GPL licensed FOSS libraries due to much risk they get a legal lawsuit because they may have incorrectly specified/attributed something.

The order of licenses in which you can and cannot use them as libraries is as follows:

`MIT > Apache 2.0 > LGPL > GPL 3.0`

where a project licensed in X can only take the the licenses specified left of it, not right of it. So FlorisBoard cannot include a LGPL or GPL licensed library, but any Apache 2.0 or MIT licensed library.

I hope I could explain the license topic to you and I got everything right.

**Comment by Glitchy-Tozier** [comment]
Understood.
I always saw the restriction of GPL as a good thing as it seemed to help open-source spread.

However, I can see how this also could be viewed as a bad restriction, closing doors.



Thank you for the explanation, I'll close this issue now. :)
Of course I'll read any further comments, should they appear.

**Comment by TPS** [comment]
@Glitchy-Tozier If you're interested, https://choosealicense.com/ is [an open-source](https://github.com/github/choosealicense.com) resource "curated by GitHub" to answer many questions re: OSS licensing.

**Comment by Glitchy-Tozier** [comment]
Thank you, I'll look at it!  :)

**Comment by BHydden** [comment]
> The order of licenses in which you can and cannot use them as libraries is as follows:
> 
> `MIT > Apache 2.0 > LGPL > GPL 3.0`
> 
> where a project licensed in X can only take the the licenses specified left of it, not right of it. So FlorisBoard cannot include a LGPL or GPL licensed library, but any Apache 2.0 or MIT licensed library.

I noticed FlorisBoard is still licensed as Apache 2.0 but implements a library [nuspell](https://github.com/nuspell/nuspell) which uses LGPL 3.0 which you say here is not allowed. 

Are there any plans to change the license for FlorisBoard or else replace nuspell with an alternative library that comes under Apache or MIT?

**Comment by TPS** [comment]
@patrickgold _Is_ `nuspell` being removed for licensing incompatibility, or _other_ reasons?

**Comment by patrickgold** [comment]
> Is nuspell being removed for licensing incompatibility, or other reasons?

I mean the license issue with Nuspell is a gray area IMO, thus I am trying to get rid of that gray area. But I also had technical problems with encoding problems and using Nuspell (or any external spelling-only library) means that you must have 2 separate languages per language (one for suggestions and one for spelling), which sucks in the long run. So the decision for the Nuspell removal is a mix of different factors.
