### ISSUE TITLE
Make popup-hints slightly more pronounced

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#213]
Most of the hints I can see and interpret. However, in the bottom line symbols get difficult to differentiate:
- `*`, `"`, and `'` just look like three points with varying sizes.
- `:` and `;` aren't easy to differentiate either.
- `-` also kind of looks like a point at the first glance.

The same issue exists in dark mode.
For all those hints you need to stop, stare, and move closer to the screen to see what you are going to input.

I know the colour can be changed in the settings.
However, I think it would be a good idea to make them just slightly darker by default.
(And brighter in dark mode)

This shouldn't bother people because when they activate hints, I think the are ready do _actually see_ the hints.

**Comment by Glitchy-Tozier** [comment]
The same issue exists in the dark mode.

**Comment by patrickgold** [comment]
I think your issue is more visible for smaller devices. I have a OnePlus 7T, which has a fairly big screen, and absolutely have no problem in distinguishing the hints from one another.  Though I agree the `"` and `'` symbol are near identical. If I compare my implementation to Gboard's in terms of how it is drawn, Gboard makes the hint a tad bigger (I think at least) and the hint label is bold.

Maybe I can improve the hints by
a. improving the contrast (like you suggested)
b. make the hint label bold

I will place this on my todo list!

**Comment by Glitchy-Tozier** [comment]
Thank you.

Yes, bigger screens probably have an easier time with this. But even with my Samsung Galaxy S9 (Not that small of a device) I have a hard time.

I would say Those two options are great, but we should consider a third option:
1. improving the contrast
2. make the hint label bold
3. increase the font-size of the hint label

The best combination in my opinion is a mix of 1. and 3., but it's probably best to try out different approaches.

Also, if you're looking for inspiration, another great example of how to do it is OpenBoard.

**Comment by patrickgold** [comment]
I've experimented with some combinations and went for a mix of 1. and 3. This is what it looks like:

Old | New
---|---
![Screenshot_20210131-153229](https://user-images.githubusercontent.com/19412843/106387496-4f562c80-63da-11eb-82d9-aed4f7ce1b53.jpg) | ![Screenshot_20210131-153250](https://user-images.githubusercontent.com/19412843/106387501-52e9b380-63da-11eb-82d5-0c109ae036a9.jpg)

What do you think of this?

**Comment by Glitchy-Tozier** [comment]
Way better!!
I still think that the main offenders aren't perfect, but i'm not sure what to suggest.

- Enlarging everything even further is no good, as it makes the big symbols way too large.
- Selectively making some symbols bigger than others also seems weird.

**Comment by patrickgold** [comment]
I've tried making the labels bold but that doesn't look good either. The only thing which I can now do is to make the font-family of the hint labels mono-space, which makes the characters more wide:

![Screenshot_20210131-161904](https://user-images.githubusercontent.com/19412843/106388874-b840a300-63e0-11eb-9466-74106ccc26c3.jpg)

Event though the font-family of the normal label and the hinted labels now aren't the same, I think this is the best style for the hinted labels.

**Comment by Glitchy-Tozier** [comment]
OOOOOHHHH!!  Yes, this is amazing!!  :)

By far he most legible!

(If i could complain about one thing, it would be the fact that the `@` is distorted. I'll take that any day of the week if I get those pretty `'`, `"`, `*`, etc. in return)

**Comment by patrickgold** [comment]
This is because the `@` key has to be squashed together to fit in a monospace unit. As a dev who has seen too many squashed together `@`s while coding, there's nothing wrong for my eye :) Still, I think we will have to live with this as all other characters are way more distinguishable now and this is by far the best output. Will push the implementation commit soon.

**Comment by patrickgold** [comment]
Above commit adds the new style as seen in above screenshot. Will be released with v0.3.6 either today or tomorrow. Thanks again for your help!

**Comment by Glitchy-Tozier** [comment]
> and this is by far the best output.

I absolutely agree, good job thinking of that!  :)

**Comment by Glitchy-Tozier** [comment]
It's WAY better now  :)
