### ISSUE TITLE
Don't make "Selected Design:" a button if it doesn't do anything.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#214]
Don't make **the thing below "Selected Design:" where you can see the currently used design** a button if it doesn't do anything.

**Comment by patrickgold** [comment]
You are right this UI was not my greatest creation :) This is also the reason why v0.3.3 has completely replaced the old theme UI (I assume you are still on v0.3.2), where such a thing does not exist anymore.

**Comment by Glitchy-Tozier** [comment]
I see :)
Should I close this then or wait until the update?

**Comment by Glitchy-Tozier** [comment]
And yes, v0.3.3 hasn't arrived in F-Droid yet, which is why I'm stll using v0.3.2.

**Comment by patrickgold** [comment]
>  Should I close this then or wait until the update?

You can close it, as it is resolved IMO.

> And yes, v0.3.3 hasn't arrived in F-Droid yet, which is why I'm stll using v0.3.2.

Np, just wait for the F-Droid update for v0.3.3, we are in no hurry :)

**Comment by Glitchy-Tozier** [comment]
By the way, I'm amazed at how organized you implemented the new theme-settings!

**Comment by patrickgold** [comment]
Thanks for the feedback, glad you like the new Theme Settings! :)

Btw, just so you know, you currently cannot add key specific style overrides because I f*cked up in the UI input validation. This is fixed though in v0.3.4, which I will push this evening. v0.3.4 also contains a link to [this wiki entry](https://github.com/florisboard/florisboard/wiki/Using-the-new-Theme-Editor) which better explains the rather complex theme editor better. The update should arrive on Saturday or Monday as you are getting it now via GPlay.
