### ISSUE TITLE
Add monochrome icon 

### ISSUE THREAD

**Issue by xmha97** [florisboard/florisboard#2159]
Please support the Themed Icon.
https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming

![Screenshot_2023-02-20-16-34-26-740_de.mm20.launcher2.release.jpg](https://user-images.githubusercontent.com/23485114/220116753-f5be5411-0cbc-46b8-9a25-c05cda46ef9d.jpg)

Thanks.

**Comment by M00NJ** [comment]
I implemented this, but haven't been able to test it, because of the building issues mentioned in #2218. In case anybody else wants to have a go at it here are the monochrome icon files I created:
![ic_app_icon_monochrome(mdpi)](https://github.com/florisboard/florisboard/assets/82398591/887464e7-79ad-4295-b598-25fb1225fdb9)
![ic_app_icon_monochrome(hdpi)](https://github.com/florisboard/florisboard/assets/82398591/e9b180d1-fb97-4cdc-bf83-0b43c440ea24)
![ic_app_icon_monochrome(xhdpi)](https://github.com/florisboard/florisboard/assets/82398591/1694b347-0a94-42e6-918e-723ad74d8900)
![ic_app_icon_monochrome(xxhdpi)](https://github.com/florisboard/florisboard/assets/82398591/3752240e-c201-445f-ade5-e61b81ca9e32)
![ic_app_icon_monochrome(xxxhdpi)](https://github.com/florisboard/florisboard/assets/82398591/ccd983a1-4b0c-463e-b65e-85fa9bfe9068)

**Comment by klaurence** [comment]
To add to this issue, I wanna point out that the non-monochrome Florisboard icons use colors to distinguish between types of versions.

In the logo's flower, debug versions use orange, alpha/beta versions use green, and stable versions use both. It might be helpful to visualize this, if possible, in the monochrome icons.

| Version | Logo | Link in the repository |
|---|---|---|
| Debug | ![](https://github.com/florisboard/florisboard/raw/master/app/src/main/ic_app_icon_debug-playstore.png) | [app/src/main/ic_app_icon_debug-playstore.png](https://github.com/florisboard/florisboard/blob/master/app/src/main/ic_app_icon_debug-playstore.png) |
| Alpha/beta | ![Test](https://github.com/florisboard/florisboard/raw/master/app/src/main/ic_app_icon_beta-playstore.png) | [app/src/main/ic_app_icon_beta-playstore.png](https://github.com/florisboard/florisboard/blob/master/app/src/main/ic_app_icon_beta-playstore.png) |
| Stable | ![Test](https://github.com/florisboard/florisboard/raw/master/app/src/main/ic_app_icon_stable-playstore.png) | [/app/src/main/ic_app_icon_stable-playstore.png](https://github.com/florisboard/florisboard/blob/master/app/src/main/ic_app_icon_stable-playstore.png) |

**Comment by lm41** [comment]
Monochrome icon support can be solved in different ways. 
1. Different alpha levels, so that you can distinguish the versions
2. Replace the space bar with the respective flavor name for beta and debug versions
(3. Possibly combine both)

**Comment by lm41** [comment]
See #2364
