### ISSUE TITLE
Vibration on Button-Press doesn't work.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#217]
Just nothing happens.
Yes, it _is_ activated in the settings.

**Environment information**
- FlorisBoard Version: v0.3.3 (Also existed in v0.3.2)
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version: 10

**Steps to reproduce**
1. Install Keyboard 
2. Set it up
3. See error

**Comment by tsiflimagas** [comment]
Perhaps you've turned it off in your system. Maybe check that. Here it works fine.

**Comment by Glitchy-Tozier** [comment]
Thank you for the idea. How/where can i check this?

**Comment by tsiflimagas** [comment]
Hmm, I don't know how your rom is configured, but I guess you can check in sound settings, accessibility settings, and also in the customizations section, in case you're on a custom rom.

**Comment by Glitchy-Tozier** [comment]
I use the default thing that came with my Samsung phone.
I tried un-muting the phone and i doubke checked whether vibrations were turned on in florisboard.
Nothing worked though.

**Comment by tsiflimagas** [comment]
Then maybe there's a special case with your phone or system. Patrick should be able to figure it out.

**Comment by Glitchy-Tozier** [comment]
Figured it out!
It was some weird preference buried within the settings.

![Screenshot_20210121-110515_Settings.jpg](https://user-images.githubusercontent.com/59611881/105335680-a557f280-5bd8-11eb-8666-2043d12dd8eb.jpg)

Closing this issue now.

**Comment by Glitchy-Tozier** [comment]
Also thanks for the help!  :)

**Comment by Turbotomate** [comment]
I would like to reopen this issue as it is still a thing in my opinion.
I am also using Samsung One UI and therefore have the same settings as in the picture above. The marked "Berührungsinteraktionen" needs to be activated in order to receive haptic feedback when using Florisboard. But this setting toggles a lot more haptic feedback in the system which i do not want to have activated. As one can see in the screenshot, "Samsung Tastatur" (Samsung keyboard) has its own category in the vibrations menu and therefore you can activate its vibration without activating it for the whole system interactions.
I think it would be better to implement the vibration in a way, that florisboard pops up with its own category in the vibration settings, like Samsung keyboard does.

**Comment by Glitchy-Tozier** [comment]
I guess let's reopen this then and see what Patrick thinks!

**Comment by patrickgold** [comment]
@Turbotomate Above draft PR adds an option to ignore the system haptic/audio enabled state, thus allowing for haptics in FlorisBoard while the rest of the system does not have them enabled. I cannot integrate that option so nicely though like Samsung does, because I am a third-party keyboard and cannot influence this part of the system settings UI.
