### ISSUE TITLE
Shift doesn't work when writing fast

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#227]
**Environment information**
- FlorisBoard Version: 0.3.4
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: One-UI 2,5, Adroid 10

**Steps to reproduce**
1. Quickly type any key and then shift
2. Shift won't be activated in some cases

(Mainly happens to me with `delete&space  → shift`, but it can also happen with letters and enter)

**Comment by patrickgold** [comment]
Thanks for the report! This has something to do with my effort to cancel out invalid double-press actions I introduced in v0.3.4. I will look into it.

**Comment by Glitchy-Tozier** [comment]
Almost suspected that. I couldn't find the old bug however

**Comment by patrickgold** [comment]
Relevant issue for double-press bug: #170

**Comment by patrickgold** [comment]
This bug really annoys me: all the great work of #1822 with reworking and fixing soo much and this little bug here continues to survive all my extermination attempts. The main problem is that the shift key is the only key to do its thing on down instead of up, which messes up the order if shift follows another key immediately.

**Comment by Glitchy-Tozier** [comment]
That's weird.
One thing that might help you when testing is that speed does not even play a role.

1. Letter key-down
2. Shift key-down
3. Letter key-up
4. Shift key-up (the only speed-constraint is that you need to release shift before long-tap triggers caps-lock)

**Comment by patrickgold** [comment]
> One thing that might help you when testing is that speed does not even play a role.

Thanks for the hint, that's true and I also noticed that today while working on another shift issue. I still have vast problems with fixing this issue though, because I have an idea for a fix but it somehow causes keys to suddenly be eaten if shift+character is pressed at once, which is sub-optimal xD

> Edit: Why does the shift-key need to get activated on key-down?

Because else the UI does not update quickly enough and due to the fact that with the latest progress in #1832 you can now hold shift and type uppercase only while pressed, then it goes back to lowercase (like the real shift key on PC). This needs caps lock on shift long press to be disabled though in the prefs, else you end up with caps lock after releasing your finger.

**Comment by Glitchy-Tozier** [comment]
1. How did you fix the issues? :)
2. Should we close this issue, then?

**Comment by Glitchy-Tozier** [comment]
1. I see
2. Got it!
