### ISSUE TITLE
Dictionary and Wikipedia Search

### ISSUE THREAD

**Issue by seniorm0ment** [florisboard/florisboard#2270]
Not sure if this is possible, or even handled by the keyboard.
But coming from my e-reader, the feature I wish I could use daily is to be able to highlight a word, and quickly see the definition, as well as search to the wikipedia page.

For example, if I am reading an article and I see the word "Flower", I can highlight it as if I am going to copy it, then click Definition, and see the definition overlayed on the screen.
Or click Wikipedia and have it take me to the wiki page for Flower.

**Comment by tsiflimagas** [comment]
I guess you're referring to the respective Android function.
![IMG_20230928_033917](https://github.com/florisboard/florisboard/assets/45879751/98861fc4-7e87-43a7-a545-5a6e324e6861)
To be honest, I don't think this is to be done by or inside FlorisBoard. For definition, it would the job of a dictionary app, and for Wikipedia of their own app. I kinda see why you think FlorisBoard could do so, since keyboards do process words (in regard to spell checking and next word prediction), and some even have inline translation, but I think this is quite different, and it's not something to actually be done by the keyboard. The keyboard can't have definitions of words, so it will just redirect you to some place with word definitions, same goes for Wikipedia. That's why I suggest that dedicated apps should perform these actions. Moreover, I don't actually know if it's possible from technical aspect.
That's my take on this. I'll let Patrick, though, review this and give his opinion, as he may have a different view on it.

**Comment by patrickgold** [comment]
I have to agree with Kostas on this that this is not the job of FlorisBoard to perform. I am aware that some fancy keyboard apps might have such an option, however FlorisBoard does not and will not have the Internet permission in its core APK, so this proposal is not implementable. Closing thus.
