### ISSUE TITLE
Popup for "a" in "es" popup mapping shows "@" as main option despite it being set as "á" in es.json

### ISSUE THREAD

**Issue by edwoldenberg** [florisboard/florisboard#2316]
#### Short description
Language is set to English (UK) QWERTY with es popup mapping with western primary and secondary symbol layout.

As far as I can tell from [the es popup mapping json](https://github.com/florisboard/florisboard/blob/master/app/src/main/assets/ime/keyboard/org.florisboard.localization/popupMappings/es.json) the default popup for "a" should be "á", but it shows as an "@".
![image](https://github.com/florisboard/florisboard/assets/46819535/fe61bc07-30c6-4ed0-9f26-450d0cf11971)

#### Steps to reproduce
1. Set keyboard layout to English (UK) QWERTY with es popup mapping
2. Keep "a" key pressed

#### Environment information
- FlorisBoard Version: 0.3.16
- Install Source: Google PlayStore
- Device: Asus Zenfone 9
- Android: Android 13

**Comment by klaurence** [comment]
Your settings might be prioritizing `a`'s hinted symbol instead of its primary accent -- in this case, the @ symbol instead of á.

Please check your settings by going to `Settings > Keyboard`, clicking the body (not the toggle) of the `Hinted symbols` setting, and choosing any option other than `Hint is prioritized`.
