### ISSUE TITLE
Rename Emoji-Button Options.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#246]
Thank you for adding the option to disable the emoji-button!

That being said, I think renaming  some of the options would be a good idea.

![Screenshot_20210127-094831_FlorisBoard.jpg](https://user-images.githubusercontent.com/59611881/105989319-3cbdb980-60a1-11eb-8ae8-df605c4b3c85.jpg)

The biggest problem I had was... I didn't quiete understand what those options even meant. So here's some ideas for renaming things:
#### Improvements:
1. Change "Key Switch Mode" to something like "Emoji-button Settings"
**Reason:** This actually tells users what we're changing the options for.
2. Rename the Options to something similar to those:
  - "No Emoji-Button"
  **Reason:** Nobody knows what the so called switch is.
  - "Default (Emoji-Button)"
  **Reason:** The "Switch" bothers me.
This is the standart-option, right? The Default should probably be at the top of the list.
  - I don't think most users understand what internal vs system mean. So if this is how it works, i suggest renaming the two language switch options to something like "Switch Language" and "Switch Keyboard-App"
  - Rename the last option in accordance to what the previous options are called (after renaming them)

**Comment by patrickgold** [comment]
Thanks for your improvement suggestion! I realized that the "Switch key mode" string wasn't the most clear when some translators hit me up to ask me what exactly "Switch" means here. At first, most think that "Switch" means to actually switch sth. instead of a "Switch key" as a button. So yeah, I definitely agree with you that I should change this. The problem is, I am not satisfied by the label "Emoji-button mode" because an emoji button which can be set to switch languages? Makes no sense to me as a user. I expect the emoji button to go to the emoji mode and no more. The same problem arises with "language key mode", but in the other direction.

There are some alternatives I have thought of, although I am not sure how good they are:
- "Primary utility button mode"
- "Primary action button mode"
- "Utility key mode"
- "Space bar utility key mode" (to indicate its the key next to space bar)
- ?

As for the different options, I have also thought about new strings (same order as in screenshot):
- "Never show"
- "Emoji key"
- "Language switch key"
- "Keyboard switch key"
- "Dynamic emoji  / language switch key"

This preference defaults to the "Dynamic emoji  / language switch key" setting.

**Comment by Glitchy-Tozier** [comment]
> The problem is, I am not satisfied by the label "Emoji-button mode" because an emoji button which can be set to switch languages? Makes no sense to me as a user.

I think the main goal should be to let the user know what button we're even talking about.
And I can not think of anything that meets this requirement better than "**Emoji-Button Functionality**"

(Assuming the emoji-button is the default.)
If I was looking for the settings for the button that has an emoji on it and helps me input emojies, i'd look for settings with "emoji-button".

This is why it would take me (and indeed took me) a few scroll-throughs to actually find the correct setting with the options you listed.


> As for the different options, I have also thought about new strings (same order as in screenshot):

Those definitely sounds better!
Further suggestions:
1. Like I said, label the default as such. 
(this could also be helpul to back up the naming, should you decide on something 'emoji-button'-related)

2. Regarding "Never Show" I really think something containing "Disable Button" or "Hide Button" would be better.
**Why?** For some reason "Never Show" really makes me think that other options may "Somethimes Show". Which boosts my confusion.

3. The "Switch"-buttons are way better, but I'd rearrange the words in a way that sounds more like an action. (in line with what the Top-button om your list says.)
Switch Language
Switch Keyboard-App

(I added the "-App" because I think there needs to be a clear way to tell the user that he might switch apps)

**Comment by patrickgold** [comment]
> I think the main goal should be to let the user know what button we're even talking about.

I agree that this is the main issue right now and this is also what needs to be fixed.

The problem is "Never show" and all other options will never fit together nicely, as "Never show" is a statement and all others should be actions. So new idea: split this up into two preferences like so:

```
  Show utility button                   --o

  Utility button action
  [the selected action]
```

The first one is a simple toggle which will enable or disable the utility button. The second one is a list preference, which lets you select the action for the utility button. The list pref will only show if the toggle is set to ON.

The actions are then as follows (same order as screenshot, but without "Never show"):
- "Switch to emoji view"
- "Switch to next language"
- "Switch to next keyboard app"
- "Dynamic switch to emoji view / switch to next language" [Default value]

> Like I said, label the default as such.

I disagree here because throughout all list preferences of FlorisBoard the default value is not highlighted, why so exactly for this preference? Also, when you first see the preference, you will see what it is set to, so I think this shouldn't get an extra `[Default]` label.

>  And I can not think of anything that meets this requirement better than "Emoji-Button Functionality"
>  If I was looking for the settings for the button that has an emoji on it and helps me input emojis, I'd look for settings with "emoji-button".

I kinda agree with you that when first looking into the preferences you might search for "emoji button", because this is what Gboard also uses to call this. I just want to find a uniform name for this button, which is kinda easy to recognize in the Settings and which is a term fitting both "language switch" and "emoji button". "Utility button" is my current favorite for a uniform name for this, but I am unsure what I'll end up using.

**Comment by Glitchy-Tozier** [comment]
> The problem is "Never show" and all other options will never fit together nicely, as "Never show" is a statement and all others should be actions.

That is true. "`Hide Key`" and "Disable Key are actions though.

> The first one is a simple toggle which will enable or disable the utility button. The second one is a list preference, which lets you select the action for the utility button. The list pref will only show if the toggle is set to ON. This eliminates any confusion which arose with "Never show".

I really like this idea, actually!
The only inconsistency I see is that in other settings (swipe actions), you _do_ show the disabling option present in the popup-list.
Other than that… go for it!  :)


> The actions are then as follows (same order as screenshot, but without "Never show"):
•    "Switch to emoji view"

Doesn't "emoji **view** sound weird to you? I'd never call any keyboard "a view". How about "`Switch to Emojies`"?


> •    "Switch to next language"
•    "Switch to next keyboard app"
•    "Dynamic switch to emoji view / switch to next language" [Default value]

Sounds great! The only thing I'd optimize is to make the text as short as possible. (long settings and tons of line-breaks are annoying, especially if only like 3 words fit into each line.)
What do you think about those?
```
•    "Switch language"
•    "Switch keyboard app"
•    "Dynamic: Switch to Emojies / Switch Language"
```


> I disagree here because throughout all list preferences of FlorisBoard the default value is not highlighted, why so exactly for this preference? Also, when you first see the preference, you will see what it is set to, so I think this shouldn't get an extra [Default] label.

Good point. Let's not do that, then.

(((Yessss! Der erste Englischfehler den ich finde!! xD   Im Deutschen passt "…, wieso also ...?", im Englischen macht man das aber glaube ich nicht. ;)  )))


> "Utility button" is my current favorite for a uniform name for this, but I am unsure what I'll end up using.

That sounds pretty well. And if you go for the new idea you brought up in your last comment, i don't see an issue in using this.  :)

**Comment by patrickgold** [comment]
> The only inconsistency I see is that in other settings (swipe actions), you do show the disabling option in the popup-list.
Other than that… go for it! :)

I agree with you that the swipe actions have disabled as an action, though there are quite a few enable/disable toggles already in the Keyboard Settings tab, which makes this less inconsistent IMO.

> Doesn't "emoji view" sound weird to you? I'd never call any keyboard "a view". How about "Switch to Emojies" or "Go to Emojies" ?

Ok granted I named that one from an Android dev side's perspective, where "view" makes perfectly sense, as every single UI component is a `View` :) I think I'll go for "Switch to emojis".

> Sounds great! The only thing I'd optimize is to make the text as short as possible. (long settings and tons of line-breaks are annoying, especially if only like 3 words fit into each line.)
What do you think about those?

Sound good to me! The shorter the better, especially because of the fact that it still has to look good on smaller devices too.

> (((Yessss! Der erste Englischfehler den ich finde!! xD Im Deutschen passt "…, wieso also ...?", im Englischen schrebt man in diesem Kontext "..., why so ...?" aber nicht, glaube ich. ;) )))

(((Noooo xD Ich muss dir hier aber leider Recht geben, das schreibt man im Englischen tatsächlich nicht so, hab grad nachgesehen. Wieder was dazugelernt! :) )))

> Sounds swell. And if you go for the new idea you brought up in your last comment, i don't see an issue in using this. :)

Perfect, then I think I will end up using this as the name for this key!

**Comment by Glitchy-Tozier** [comment]
> Every single one of your English answers

Okay, sounds great!  :)


(((
> das schreibt man im Englischen tatsächlich nicht so, hab grad nachgesehen.

Gut, das bestätigt zu wissen, danke fürs nachschauen!
)))
