### ISSUE TITLE
Add support for official Addons Store

### ISSUE THREAD

**Issue by patrickgold** [florisboard/florisboard#2468]
### Feature idea

This is a direct preparation for the upcoming official Addons Store, which in the future will be the main hub for official and community created themes, layouts, language packs, etc.

As FlorisBoard is a privacy-focused keyboard and we thus cannot add the NETWROK permission to the app, we have to get creative on how to easily install stuff from the Addons Store. Thus the idea is to display and manage the Addons Store as a website inside the user's browser, and when the user wants to install a new addon, they can simply download the extension file and then open it, which will trigger FlorisBoard's file handler defined in the Manifest and redirect this to the extension import screen.

- [x] Add file import handler for `.flex` files
- [x] Add share import handler for `.flex` files
- [x] Add user-readable error messages for common errors
- [x] Add measures to protect the integrity of the app
  - [x] Prevent ZIP bomb attacks
  - [x] Prevent large file size attacks
  - [x] Prevent file/path name max length attacks
  - [x] Prevent relative parent path expansion overwrite attacks (e.g. `$zip/../../files/prefs.json`)
  - [x] ... more? ...
- [x] Add support for update status detection 
- [x] Add UI for managing installed addons easily within the app UI

Important is that the Addons Store never has direct control, it can just suggest to install/update an extension, the final decision is done by the user from within the import handler app UI. Removal of addons MUST be done from within the app UI.

Initial goal is that theme extensions are supported, later on also keyboard extensions. With v0.5 support for language packs will be added.

In parallel to this efforts the Addons Store itself will be publicly beta-tested by @4H1R, who kindly offered his expertise writing the Addons Store for this project too. This issue is intended to stay open for a few PRs and beta releases.

Any feedback/idea proposals for this are highly appreciated, just comment down below!

**Comment by patrickgold** [comment]
> Would this include (existing & new) languages/layouts, also? That'd help keep the APK free from stuff a paticular user may not use.

Yes, the addons store is a mix of community and official content and in the future new languages and layouts will be added this way. Some important languages and fallback layouts will always be present in the APK though, also for now some languages that require custom logic not representable yet with json/xml files or plugins (e.g. Chinese, etc.)

> Also, this might need some tuning to not run afoul of F-Droid rules, since these addons aren't themselves being published there as APKs. Maybe reach out to current F-Droid repo folks?

That's a good point actually, thanks for pointing this out. In essence addons in the way FlorisBoard plans to support them are exclusively json/xml/dictionary files that are parsed and NEVER exectuable code or script files, so it shouldn't be an issue, especially because for themes the manual import mechanism that works the same as the addons but less convenient is already present in the current F-Droid version. But I will still reach out to them on GitLab or their discussion forum just to make sure.

**Comment by Glitchy-Tozier** [comment]
Interesting idea! I see, you've stuck with `.flex` ;)

I've been wondering about how to let users know there's an update to their installed addons. It seems difficult to do since Florisboard cannot (and should not) access the internet. What could be done, however, are the following:

1. When opening the store from a link generated within Florisboard, add installed packages and their installed version as URL-parameters. The store could then read those and suggest updates where necessary. This option works well when manually opening the store.
2. To "automatically" get notified of updates, we could include a list with the current packages' names and versions in the apk on every new release of Florisboard. Then, Florisboard could compare that list to the installed addons' versions. If the installed version numbers are older than what is shown in the list, suggest an update to the affected addons. This nicely synergizes with the first idea (pass the out-of-date packages as parameters).
  - Of course, if there's >thousands of addons, such a list could become too big. Thus, I suggest listing _the X most recently updated_ packages instead of all of them.

**Comment by patrickgold** [comment]
There are multiple ways this can be done without FlorisBoard accessing the internet:

FlorisBoard could expose its own uri scheme, lets use `fladdons://` as an example. With this, the addons store can then query e.g. `fladdons://list?installed` and retrieve this list in the body response in the format `addonid:version`. Same goes for just querying a single addon if its installed and which version. I am not sure though if I will do it this way, your idea sounds also intriguing but could have its own problems in the future.

Regarding your second point, I dislike linking FlorisBoard releases to addons versions, I don't know that just does not sound like a clean solution to me.

Also some additional thought must go into how we handle the fact that there may be both FlorisBoard and FlorisBoard Beta present on a system?

**Comment by TPS** [comment]
> Also some additional thought must go into how we handle the fact that there may be both FlorisBoard and FlorisBoard Beta present on a system?

In parallel to that, handling release/beta/nightly/canary/whatever versions of the _addons_ themselves?

**Comment by lm41** [comment]
> Also some additional thought must go into how we handle the fact that there may be both FlorisBoard and FlorisBoard Beta present on a system?

If two applications register an intent filter with the same content, the user is prompted to select one of the apps. I wouldn't implement any custom logic at all, but leave that to the android system (and the user).

**Comment by Glitchy-Tozier** [comment]
(Not sure where to post this issue, I decided to come here)

Both on Android and PC, when visiting https://beta.addons.florisboard.org/ using either Brave or Firefox with strict privacy settings, they may remove the cookies-dialog. This leaves the page-blocking semitransparent ...
```html
<dialog id="cookies" class="modal modal-open modal-bottom md:modal-middle"><form method="dialog" class="modal-box space-y-4 h-4/5 md:h-auto"> ... </dialog>
```
-element on-screen, preventing users from interacting with the website.

Not sure what to do about this, but it seems like a pretty serious issue to me, especially since many users of FlorisBoard will probably have their settings turned up.

How to reproduce:
1. Download Brave Browser and don't change anything
2. Visit the store (https://beta.addons.florisboard.org)

**Comment by 4H1R** [comment]
Hi and thank you for reporting issue to us @Glitchy-Tozier 

The issue should be fixed now
Could you revisit the addon stores and check again?

**Comment by Glitchy-Tozier** [comment]
Yep, works perfectly 👍🏻
