### ISSUE TITLE
add switch button to previous keyboard without confirm

### ISSUE THREAD

**Issue by zpcol** [florisboard/florisboard#26]
![PhotoGrid_Plus_1603192442964.jpg](https://user-images.githubusercontent.com/69243210/96579523-3204c300-1301-11eb-8bbf-f387ec5a417f.jpg)

**Comment by patrickgold** [comment]
Do you propose a button to switch between subtypes **within** FlorisBoard or do you propose a button to switch to the previous/next IME **on system level** (keyboard from another app developer)?

**Comment by zpcol** [comment]
this for example, switch back previous keyboard.

https://github.com/Kunzisoft/KeePassDX/blob/a027c76af3e4054a52f33a47e1f35c70138e71df/app/src/main/java/com/kunzisoft/keepass/magikeyboard/MagikIME.kt

![2020_11_04_21 02 00](https://user-images.githubusercontent.com/69243210/98121090-67a0d300-1ee1-11eb-9015-813c1b90e47f.jpg)

**Comment by rancidfrog** [comment]
There is already a keyboard button:
![](https://i.imgur.com/ygvzgMG.png)

This is probably an android os setting

**Comment by patrickgold** [comment]
@rancidfrog I am not sure if this button shows on older versions of Android, but one can bring the same dialog up by long-pressing the space bar. OP I think requested a separate button back to the previous keyboard, which sense I don't really see, as FlorisBoard isn't a IME for specific tasks like selecting a password or a GIF to insert but a text keyboard...

**Comment by rancidfrog** [comment]
I think bringing up 'choose input method' should be enough.

In either case, does the code actually work in the way proposed?

```
private fun switchToPreviousKeyboard() {
        var imeManager: InputMethodManager? = null
        try {
            imeManager = getSystemService(Context.INPUT_METHOD_SERVICE) as InputMethodManager?
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                switchToPreviousInputMethod()
            } else {
                window.window?.let { window ->
                    imeManager?.switchToLastInputMethod(window.attributes.token)
                }
            }
        } catch (e: Exception) {
            Log.e(TAG, "Unable to switch to the previous IME", e)
            imeManager?.showInputMethodPicker()
        }
```

**Comment by patrickgold** [comment]
@rancidfrog Yeah this code looks pretty good and would work. Nevertheless it is more of a question why I should implement such button in the first place. If you want to switch from FlorisBoard you can just long press the space bar or press the keyboard icon in the navigation bar and you'll be able to choose the IME you want to switch to.

**Comment by darhma** [comment]
@patrickgold first of all thanks for the work you are doing, this keyboard is really good and with each update it gets better, congratulations.

Currently you can go to the emoji keyboard in three different ways (with the key next to the spacebar, from the smartbar or with long press enter), other keyboards (like simple keyboard and openboard) instead of the emoji switcher next to the spacebar have a switcher for the previous keyboard. In my personal use case, this is useful when using a password manager keyboard (I don't use the navigation bar and the only way to switch between keyboards is to long press the spacebar, but I have several keyboards enabled and always looking for the password manager keyboard is a bit annoying). Maybe if you don't want to change the current layout you can just add a "switch to previous keyboard" swipe gesture, as has already been done with the "switch to previous subtype" swipe gesture. Or add an option to choose which switcher to use in the key next to the spacebar (emoji/previous keyboard).

**Comment by patrickgold** [comment]
@darhma Ah I see in this use case a switch to previous keyboard gesture/button would make sense, I get it now. The problem is that I don't have any space left for a dedicated button, but I can definitely implement a gesture for previous / next subtype on a system level. I will add it to my todo list, just don't know yet when I will implement it!

**Comment by darhma** [comment]
@patrickgold thanks for consider to add this feature. I would like to share just a couple of idea on how to add it: 

1 with a swipe up gesture from spacebar to switch to previous keyboard 

2 substituting one of the two keys for the emoji with a key to switch to previous keyboard (I think that having two keys to switch to the emoji keyboard is redundant):

![](https://i.imgur.com/6uqSJc8.png)

I'm not a developer and I'm sorry I can't contribute directly with some code, anyway I hope to have given some useful hints.

**Comment by patrickgold** [comment]
@darhma Thanks for your input, I really appreciate it!

> 1 with a swipe up gesture from spacebar to switch to previous keyboard

This would make sense, as long-pressing opens the switcher dialog, and swipe up quick-switches back to the previous keyboard. I really like this idea 👍 

> 2 substituting one of the two keys for the emoji with a key to switch to previous keyboard (I think that having two keys to switch to the emoji keyboard is redundant):

The thing is the emoji button next to space bar is only visible as long as you have 0 to 1 subtypes defined. As soon as you have 2 or more a language switch button (to quick-switch to the next FlorisBoard subtype) will be shown, making the enter emoji button important for accessing the emoji view.

> I'm not a developer and I'm sorry I can't contribute directly with some code, anyway I hope to have given some useful hints.

You definitely have! :)
