### ISSUE TITLE
Serbian layout and localization

### ISSUE THREAD

**Issue by GrbavaCigla** [florisboard/florisboard#270]
I would like to add Serbian cyrillic and Serbian latin layouts. Also I want to translate the app. I used crowdin in the past.

**Comment by GrbavaCigla** [comment]
I started translating Serbian on crowdin. Still don't know how to add a layout

**Comment by patrickgold** [comment]
Thanks for translating FlorisBoard into Serbian and for considering to add a Serbian layout to FlorisBoard!

For layout creation, see https://github.com/florisboard/florisboard/blob/master/CONTRIBUTING.md#adding-a-new-keyboard-layout--dictionary-for-locale

**Comment by GrbavaCigla** [comment]
I made python script to automate codes for labels in `app/src/main/assets/ime/text/characters/`

```python
import json
from sys import argv

if len(argv) != 2:
    print(f"Usage: {argv[0]} FILE")
    exit(1)

with open(argv[1], "r") as file:
    layout_json = json.load(file)
    print(layout_json)

for i, row in enumerate(layout_json["arrangement"]):
    for j, key in enumerate(row):
        ch = key["label"]

        layout_json["arrangement"][i][j]["code"] = ord(ch)


with open(argv[1], "w") as file:
    json.dump(layout_json, file, ensure_ascii=False)
```
I copied qwerty.json and changed the labels, this script adjusted `code` value for each label.

Should I include it? If yes, where?

**Comment by GrbavaCigla** [comment]
I started translating using crowdin. Discussion moved to #275.

**Comment by svvvst** [comment]
> I started translating Serbian on crowdin. Still don't know how to add a layout

@GrbavaCigla I am trying to add a new layout...could you explain how to modify the config files after the json files are complete?

**Comment by GrbavaCigla** [comment]
Looking at the files and my changes at #275, seems like they changed it without updating the docs. I found something resembling old config here: https://github.com/florisboard/florisboard/blob/master/app/src/main/assets/ime/keyboard/org.florisboard.layouts/extension.json, but better ask @patrickgold because I am just speculating.

**Comment by patrickgold** [comment]
The docs aren't updated yet because the theme rework is not completed yet and for stable it would still be the correct docs, just not for beta.

https://github.com/florisboard/florisboard/tree/master/app/src/main/assets/ime/keyboard and its sub-directories define all core layouts, popup mappings etc., which are included in the app APK and which are all in the new format. If you write a layout which should be included in the core assets then you need to modify 1, 2 or all of the extensions of above link, if you write a custom extension then you can pack the layout, mapping, currency set etc in one archive and distribute it as a flex archive.

**Comment by Zokii0** [comment]
Could you add â and ô in sr.json popup mapping?
