### ISSUE TITLE
Backup suport

### ISSUE THREAD

**Issue by overlord8** [florisboard/florisboard#272]
please add option to backup all settings, words, layout data to sdcard.
Thank you

**Comment by patrickgold** [comment]
Thanks for your suggestion! I think the primary goal would be to add support for the default Android backup solution, which is currently disabled. I will add this to my todo list.

**Comment by ungubajue90k** [comment]
It would be very good if the backup function can also backup and restore individual functions.

An example I just want to save the learned suggestions and Languages & Keyboard layouts under "Typing" and later transfer the backup file them to another Android device and restore them. The file name format because of File Manager app should also be logical. Maybe also add the timestamp also additionally as file name.

**Comment by pokegamer5547** [comment]
> It would be very good if the backup function can also backup and restore individual functions.
> 
> An example I just want to save the learned suggestions and Languages & Keyboard layouts under "Typing" and later transfer the backup file them to another Android device and restore them. The file name format because of File Manager app should also be logical. Maybe also add the timestamp also additionally as file name.

Yep i agree, also i think if it works like this would be great:
1: backup (with optional checkboxes to select what you wanna backup like learned words suggestions, settings, etc.
2: after selecting them, florisboard should make a backup file but before exporting it it should give two options. "Share" and "save". Just Save is ofc useful when we want to restore quickly but since this data can contain learned data, i would like to share the file to app like openkeychain and encrypt it and then export it using that instead for little more safety.

**Comment by billie80** [comment]
I regularly use adb backup and hopefully in the near future [seedvault](https://github.com/seedvault-app/seedvault). So it would be great if backups with allowBackup in the Manifest would be enabled. The [fullBackupContent](https://developer.android.com/guide/topics/manifest/application-element#fullBackupContent) element even allows for fine grained control over which files are subject to backup. There it is possible to in- or exclude files as well as forcing an encrypted backup. The [developer guide](https://developer.android.com/guide/topics/data/autobackup) contains very useful information about this topic.

**Comment by patrickgold** [comment]
Above linked PR #1490 enables support for Android's auto backup. I successfully tested this locally but it would be best if some of you can test out if the backup works correctly for the debug build, so I can get a bigger picture if I need to adjust some rules or if something else is incorrectly configured. Thanks in advance!

**Comment by billie80** [comment]
Great could also only test this with adb backup now.
I am not sure but is Android S (12) really required? My device is at Android 10 currently and it may take while until it receives an update to Android 12. In the other bug you state that this is only due to a change in syntax for Android S. So I guess it also works for older versions?
Another thing, in the pull request summary you state that the user dictionary is excluded but in the commit it is included. I guess this was not intended because I think it makes sense to include the dictionary.

**Comment by patrickgold** [comment]
Thanks for testing it out!

> I am not sure but is Android S (12) really required? 

Nope auto-backup is supported on all Android versions FlorisBoard also supports, so A6-A12 atm.

What I meant in the other bug is, that until A11 (inclusive) [this](https://github.com/florisboard/florisboard/blob/52031d682603d1568530c67464bc00fea2669b05/app/src/main/res/xml/backup_rules.xml) is the syntax for backup rules, since A12 [this](https://github.com/florisboard/florisboard/blob/52031d682603d1568530c67464bc00fea2669b05/app/src/main/res/xml-v31/backup_rules.xml) is the syntax for the rules. This means I have to maintain two versions of the file as I support A6-A12. But I also do not expect to change this file too often so it does not pose a problem in the end.

> Another thing, in the pull request summary you state that the user dictionary is excluded but in the commit it is included. I guess this was not intended because I think it makes sense to include the dictionary.

Interesting. In my tests adb backup straight out refused to include the user dictionary, for you it auto includes it. Does the user dictionary fully work after restoring? As I haven't gotten the database to export I wasn't able to test how it works after importing it again. As for what's better, I stated in the PR that the user dictionary is excluded because I couldn't get it to work, but if it works I will of course support backing up the user dictionary.

**Comment by billie80** [comment]
Sorry was not able not test it until now. I said "could" :-)
I only read the pull request commit summary your changes and the two bugs referenced.
The first two points I understand, thanks for confirming.
Regarding the dictionary. In the backup rules you include floris_user_dictionary.db so I was under the impression it is included and works. This is why the mentioning in the summary about it not being included confused me. 
Maybe I find the time to test it in the next days. Then I will report back especially regarding the database. According to the docs it should work however.

**Comment by billie80** [comment]
I just had the time to test the new backup functionality. It seems that encrypted ADB backup only contains the APK and a _manifest file.
The In-App backup only backs up the installed dictionaries, the jetpref_datastore which probably should contain the settings does only contain a few (6) settings.
If I can provide more specific information please let me know.

**Comment by patrickgold** [comment]
> I just had the time to test the new backup functionality. It seems that encrypted ADB backup only contains the APK and a _manifest file.

That's not good, which Android version are you on?

> The In-App backup only backs up the installed dictionaries, the jetpref_datastore which probably should contain the settings does only contain a few (6) settings.

The jetpref_datastore only contains settings you manually changed (default values are not written), so as long as you have only changed 6 settings this is correct.

**Comment by billie80** [comment]
I am on Android 10. The contents of the backup are the same independent of using a password or not.

Pretty sure I changed a lot more settings. I just looked into the App and recognized all settings were set back to default. 😟 Don't know how this could have happened!? I changed some settings again and it seems they are indeed included in the backup. Still curious why the previous settings disappeared.

**Comment by patrickgold** [comment]
> I am on Android 10. The contents of the backup are the same independent of using a password or not.

Hmm pretty modern Android version, should work with it normally. I need to look more into this when I have more time.

> Pretty sure I changed a lot more settings. I just looked into the App and recognized all settings were set back to default. worried Don't know how this could have happened!?

This was a bug in the first betas, but after a fix never seen or reported by the initial reporters and me ever again. Did you by any chance try out the restore feature as well? Maybe there's a bug which caused the reset...

**Comment by billie80** [comment]
> Hmm pretty modern Android version, should work with it normally. I need to look more into this when I have more time.
That would be great!
> This was a bug in the first betas, but after a fix never seen or reported by the initial reporters and me ever again. Did you by any chance try out the restore feature as well? Maybe there's a bug which caused the reset...
I only tried the backup functionality and then inspected the contents. This is with beta09 btw, but I guess it is the only released version including backup support.

**Comment by billie80** [comment]
> This was a bug in the first betas, but after a fix never seen or reported by the initial reporters and me ever again. Did you by any chance try out the restore feature as well? Maybe there's a bug which caused the reset...
Probably not the right place but as I mentioned it here first. With the latest beta14 all settings were reset to the defaults again.

**Comment by billie80** [comment]
> The jetpref_datastore only contains settings you manually changed (default values are not written), so as long as you have only changed 6 settings this is correct.

Actually it is like this. Preferences are saved if they ever deviated from the default. Meaning if a value is "false" as a default, it is not saved initially. If it is changed to "true" then it will be saved. If switched back to "false" it is still saved with current value "false".
Would'nt it make more sense to only save the setting if it currently deviates from the default? Or save all settings independent of the default because currently they will end up there anyways.
