### ISSUE TITLE
Readability issues in landscape mode

### ISSUE THREAD

**Issue by CendonArc** [florisboard/florisboard#289]
**Environment information**
- FlorisBoard Version: 0.3.5
- Install Source: F-Droid
- Device: Huawei P20 lite
- Android version, ROM: Android 9, EMUI 9.1.0

**Steps to reproduce**
1. Go to a messaging or note-taking app (e.g. Signal, Telegram, DeltaChat, Orgzly,...)
2. Switch to landscape mode
3. The writing interface will be fully transparent and reduce readability significantly
4. The text will be black, independent of the theme and background

Personally, I've always preferred for the landscape mode to use the app's native writing interface just like in the portrait mode.
This way it wouldn't interfere with the interface of the app and look more natural.

![florisboard_landscape_screenshot](https://user-images.githubusercontent.com/16612053/106384238-13b36680-63ca-11eb-99c5-1752f2201ced.jpg)

**Comment by patrickgold** [comment]
Thanks for your bug report! This is indeed a bug in the latest release version (v0.3.5), but has since then be fixed in #276. Will be released with v0.3.6 either today or tomorrow.

> Personally, I've always preferred for the landscape mode to use the app's native writing interface just like in the portrait mode.
This way it wouldn't interfere with the interface of the app and look more natural.

If the native app's UI or the keyboard extract UI is shown in landscape is determined by the target app and not by FlorisBoard. Some apps like Signal don't properly adjust their landscape input UI, so they request the keyboard to show this extract edit UI.
