### ISSUE TITLE
[Question] How to disable tablet full screen ?

### ISSUE THREAD

**Issue by KaKi87** [florisboard/florisboard#291]
Hello,

I need to get rid of that blinding white full screen tablet input, how can I do this ?

Thanks.

**Comment by patrickgold** [comment]
What exactly do you mean with "blinding white full screen tablet input"? If possible, could you send a screenshot so I can visualize the problem?

**Comment by KaKi87** [comment]
![](https://i.goopics.net/Ak37q.png)

![](https://i.goopics.net/LN2EQ.png)

**Comment by patrickgold** [comment]
Ah you mean the extract edit UI. In v0.3.6 (which is expected to release today or tomorrow), the extract edit UI is now designed to match the keyboard style, so either day or night theme. Why the extract UI is showing even though you are on a tablet is because the target app is requesting this via a flag and FlorisBoard just relies on this currently. I will add this to my tablet UX enhancement todo list so this shouldn't happen.

**Comment by KaKi87** [comment]
Well, the keyboard I was using before FlorisBoard had an option in settings to disable it completely, do you think you could add this too ? Thanks

**Comment by patrickgold** [comment]
I definitely can, will add this to my todo list.

**Comment by KaKi87** [comment]
Thanks !

**Comment by KaKi87** [comment]
F-Droid is stuck on v0.3.5 :/

**Comment by patrickgold** [comment]
Yeah I know but I just can't do anything to speed up that process, it is just that F-Droid is very slow in adapting updates...
