### ISSUE TITLE
Wider raw input editor detection

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#302]
As the detection between raw input and input connection (is this the name) methods works great for the spacebar gestures, I wonder if it would be possible to apply the same on the rest of the areas where it can be applied. These are the arrows on the smartbar, and the navigation view (I just made up a name for that, I mean the keyboard view with the four arrows and the text selection options). I hope I'm not missing any.

**Comment by patrickgold** [comment]
Thanks for your suggestion! Yes, a wider raw input editor detection would definitely be great. Though the arrow keys have the problem that even some "rich" input editors require hardware arrows instead of using the input connection (verification PIN input fields for instance in Signal). When using the input connection, I am unable to delete text beyond a single input field, even though that is basically what I would have to do for such number inputs. (See #64) So I am kinda stuck with using only hardware emulated arrows. I will add this to my todo list, I'll see what I can do.

**Comment by tsiflimagas** [comment]
Ah, I see. Sometimes I almost feel bad to have so much no idea about the code side. I can have some ideas in my head, but no clue about how possible, hard or easy could they be😅. Yet, really not much of a problem, this works great for spacebar gestures, where it's most important I'd say.

**Comment by tsiflimagas** [comment]
It seems that in 0.3.8 arrows aren't able to make the cursor leave the input field any longer. I wonder if this happened collaterally by some of the changes or was actually intentional.

**Comment by patrickgold** [comment]
> It seems that in 0.3.8 arrows aren't able to make the cursor leave the input field any longer. I wonder if this happened collaterally by some of the changes or was actually intentional.

At the time of implementation it was rather accidental, I've rewritten the EditorInstance code which sends hardware simulated keys to target apps and it now includes a flag that it came from a soft keyboard, thus it seems that this prevents the arrow from actually leaving the textfield. For normal textfields, this is a good thing, though I am unsure it it broke the verification number input fields.

**Comment by tsiflimagas** [comment]
Sorry for delaying to respond. Since the result at the moment is the one desired by the issue, I'll close it for now and will reopen it if something changes in this respect (since it will may happen).
