### ISSUE TITLE
Utility-Button: improve settings.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#306]
Version 0.3.6
![Screenshot_20210203-095203_FlorisBoard.jpg](https://user-images.githubusercontent.com/59611881/106722016-ba377b80-6605-11eb-91cb-ee853c14ad73.jpg)

1. "Wechseltaste" ist schon komisch.
Not sure what else to call it though.
2. Please remove the last backslash of the last option.

**Comment by GithbUser** [comment]
![Screenshot_20210203-144432789](https://user-images.githubusercontent.com/75420364/106724622-cc51f380-65de-11eb-91d9-68ee151a5339.jpg)

2.last backslash is not in English 
Maybe language or device related

**Comment by Glitchy-Tozier** [comment]
Thanks a lot, GithbUser!

Yeah, it might be German only

**Comment by patrickgold** [comment]
Thanks for your bug report! This issue is a localization issue and if you want to, you can contribute to this yourself over at Crowdin. I didn't translate this string myself, but yeah at first I would also have trouble finding a good German word for "utility key".

All utility key strings for German can be translated here (you need to be signed in with a Crowdin account for this link to work properly): https://crowdin.com/translate/florisboard/42/en-de?filter=basic&value=0#q=utility_key

Crowdin project of FlorisBoard: https://crowdin.com/project/florisboard

**Comment by patrickgold** [comment]
@GithbUser Unrelated question: Do you know what font you are using on your device? This font looks so clean and I kinda want to try it out on my own personal device.

**Comment by GithbUser** [comment]
Sorry @patrickgold i m using default font of Arrow Os  custom rom 
I have currently asked about (font name)that in their telegram group 
Will inform you when i know
Hope you will understand
![Screenshot_20210203-182858_1](https://user-images.githubusercontent.com/75420364/106750851-c66c0a80-65fe-11eb-8fc0-8af1f452c425.png)
There is no name mentioned (besides default) in above image

**Comment by patrickgold** [comment]
@GithbUser Thanks for letting me know, really appreciate it!

**Comment by patrickgold** [comment]
I have thought about the term "Wechseltaste" and didn't find a more suitable term in German. DO you have any idea? Else I am just gonna leave it that way. The other bug with the inconsistent slash has been fixed by me.

**Comment by Glitchy-Tozier** [comment]
The best idea i have right now is to cheat and use `Utility-Taste`...

**Comment by patrickgold** [comment]
That's actually a good idea and I like it pretty much. Changed the according strings in Crowdin.

**Comment by Glitchy-Tozier** [comment]
Glad you like it.
