### ISSUE TITLE
Landscape text field always is green

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#307]
Screenshot of Github:
![Screenshot_20210203-095503_GitHub.jpg](https://user-images.githubusercontent.com/59611881/106722652-814bd680-6606-11eb-92ce-b78e731ce72d.jpg)

Maybe that's because my launcher is green and it never resets its colors.

**Environment information**
- FlorisBoard Version: 0.3.6
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Steps to reproduce**
1. Go to any app that uses triggers this text-field (Signal or Github for example)
2. Open Keyboard, 
3. Rotate device

Sometimes it seems fine. It took me two tries to make the bug work with Signal. Most of the times it's buggy though.

_______
Also, nice job on the pop-ups. They work well in landscape mode.

**Comment by Glitchy-Tozier** [comment]
Different Landscape issue: When filing a bug, turning your device sideways always make the cursor go to the title-textbox, even if you were writing the bug-description before going into landscape mode.

No idea whether this is a Florisboard-Issue though.

**Comment by patrickgold** [comment]
Hmm okay this is good that this bug happened, because it gives me a hint why #274 is still an issue even in v0.3.6.

I am setting the background color of the input view as well as the landscape editor via the `setTint()` function, which works on pretty much any device, except on yours (for whatever reason). I will investigate further why this function does not work, maybe I will resort to the `DrawableCompat` class.

**Comment by Glitchy-Tozier** [comment]
> Hmm okay this is good that this bug happened, because it gives me a hint why #274 is still an issue even in v0.3.6.
> 
> I am setting the background color of the input view as well as the landscape editor via the `setTint()` function, which works on pretty much any device, except on yours (for whatever reason). I will investigate further why this function does not work, maybe I will resort to the `DrawableCompat` class.

I was hoping that it could help us find the problem!
Weird that it's just my device though.

Oh, what I forgot to mention: This bug happened with the adapting themes enabled.

**Comment by patrickgold** [comment]
> Oh, what I forgot to mention: This bug happened with the adapting themes enabled.

Does the landscape editor background bug happen when you are not using adaptive themes?

**Comment by Glitchy-Tozier** [comment]
We're masters of editing our previous posts while the other person is writing a reply.

> It also happens when i'm using the static FlorisBoard Day - theme

**Comment by Glitchy-Tozier** [comment]
What I could try is resetting the whole app and retry it (meaning I don't ever even use the adapting themes)

**Comment by patrickgold** [comment]
> What I could try is resetting the whole app and retry it (meaning I don't ever even use the adapting themes)

It is sufficient to just disable the adaptive theme toggle. This automatically resorts to the default static themes.

**Comment by Glitchy-Tozier** [comment]
Disabled:
![Screenshot_20210203-123319_GitHub.jpg](https://user-images.githubusercontent.com/59611881/106741458-042b5c00-661c-11eb-8298-f2598685edaa.jpg)

**Comment by patrickgold** [comment]
Thanks for trying this out! So the bug seems to really be with the `setTint()` method. Will investigate into this.

**Comment by patrickgold** [comment]
Ok while this issue is not super-relevant, I got the chance to get a hand on a physical Samsung Galaxy A20e with OneUI 2.0 and Android 10. So I had to immediately try FlorisBoard out to see where FlorisBoard and OneUI don't like each other. I tried it out and at the first glance everything worked fine. Also when using adaptive themes, all the colors got correctly applied without a delay, so I still cannot figure out why the background color on your Samsung device does not get correctly applied sometimes.

Then I got to the landscape fullscreen input. And yeah, this looked completely out of place (v0.3.6 screenshot):
![Screenshot_20210204-130214_F-Droid](https://user-images.githubusercontent.com/19412843/106890592-d876a780-66e9-11eb-9506-152be2fda1cc.jpg)

~It seems to me that Samsung is using a slightly different structure (or at least background drawables) that all other Android devices for the landscape input UI, so this happens.~ I did some testing and found out, that Samsung is nasty and wants to force the Samsung Keyboard Theme on the landscape input UI of other keyboards as well. This is now fixed, here it is what it looks like now:
![Screenshot_20210204-140102_F-Droid](https://user-images.githubusercontent.com/19412843/106896353-bed95e00-66f1-11eb-840b-f4019005162a.jpg)

This as well as some other improvements in the landscape input UI will be pushed soon as a PR.

**Comment by Glitchy-Tozier** [comment]
> Also when using adaptive themes, all the colors got correctly applied without a delay

Yeah, it's super inconsistent. Sometimes it happens five times in a row, but most of the time everything works fine.

> This is now fixed, here it is what it looks like now: [picture]

That's really sexy!


Good to know that it's a samsung issue, i was starting to be confused because apparently I was the only person experiencing the bugs.

**Comment by patrickgold** [comment]
Above PR fixes and improves the landscape input UI. Will be released with v0.3.7 today. I've tested this change out on my physical Samsung Galaxy A20e where it seemlessly worked. If the themeing still makes trouble in the new version on your device, feel free to reopen this issue!
