### ISSUE TITLE
Welcome screen gets displayed in weird situations

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#310]
#### Steps to reproduce
1. Delete app-data in android's app-settings.
This basically completely reset the app, with the important difference being **that the keyboard was still activated** in the android-settings.
2. Go to some app that opens the keyboard.
3. Go to settings by long-pressing the emoji-key.
4. **You get sent straight to the settings.** No welcome-screen gets triggered!
5. Now you may set up the keyboard as you like.
6. Exit out of the app. You now have a fully functional keyboard. You've never seen the welcome-screen.
7. Open FlorisBoard the usual way.
8. **Welcome-screen gets triggered.**

Nr. 4 in combination with Nr. 8 makes me think this isn't something that should have happened.
I'm not sure what fix would make the most sense though.

#### Urgency
Fixing this shouldn't be a priority I think. It should only happen with users that do weird stuff (like I did).
Word suggestions and #227 (and others) are way more important.

#### Environment information
- FlorisBoard Version: 0.3.6
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: One-UI 2,5, Adroid 10

**Comment by patrickgold** [comment]
Thanks for the bug report! It really amazes me that there are so many unique ways to break my keyboard :)

Tbh, I didn't even think of the fact that deleting the app data still lets you into the Settings without prior being on the setup screen when using the Settings shortcut from within the keyboard itself. This is due to the fact that when you press the FlorisBoard icon in the home screen, you are actually always launching the SetupActivity and when you've already completed the setup you'll automatically redirected to the SettingsMainActivity. When using the Settings shortcut from within the keyboard, you go immediately to the SettingsMainActivity.

This bug is also reproducible after a clean install:
1. Install FlorisBoard
2. Directly go to "Device Settings" > "Language > Input" and somewhere there enable FlorisBoard
3. Click on any text field
4. Long-press the space bar or use the Android IME switch button in the bottom-right
5. Select FlorisBoard
6. Use the Settings Shortcut
7. You are immediately in the Settings

I will place this bug on my todo list to be fixed.

**Comment by Glitchy-Tozier** [comment]
> Thanks for the bug report! It really amazes me that there are so many unique ways to break my keyboard :)

It's pretty fun finding this stuff.  :)

So the solution is just to always show the welcome-screen upon first app launch?

I suggest that you maybe skip the "Activate FlorisBoard" page if it already is active.

**Comment by patrickgold** [comment]
> So the solution is just to always show the welcome-screen upon first app launch?

I'll just do the same as with the home screen launcher: Always open the `SetupActivity` and check if the `internal__is_ime_setup` flag is set. If so, immediately redirect to the Settings, else just show the setup screen with all its steps.

> I suggest that you maybe skip the "Activate FlorisBoard" page if it already is active.

I think letting it stay like it is now (that the success text is immediately there even though you didn't go to the system settings because FlorisBoard is already enabled).

**Comment by patrickgold** [comment]
Above commit fixes the bug, it now always correctly shows the welcome screen if needed. Thanks again for reporting!
