### ISSUE TITLE
Version in F-Droid not updated

### ISSUE THREAD

**Issue by sandoxy** [florisboard/florisboard#320]
Thanks for the project!

There is not the latest version of florisboard at F-Droid.

**Comment by D3SOX** [comment]
That's F-Droid's fault
It was already mentioned multiple times in other issues.
f.e. https://github.com/florisboard/florisboard/issues/216#issuecomment-764631460

You can switch to the Play Store or GitHub release if that bugs you.

**Comment by sandoxy** [comment]
I tried to find similar issues, without success. As well as I failed to find florisboard an GooglePlay.

**Comment by D3SOX** [comment]
You need to join the group, then you can sign up for it. See [the section about it in the readme](https://github.com/florisboard/florisboard#public-alpha-test-programme)

**Comment by sandoxy** [comment]
I managed to find the newest apk at github. And I can live with that solution:)

**Comment by patrickgold** [comment]
@sandoxy F-Droid is pretty slow in publishing updates. This is due to the fact that they have limited resources and build apps from the source code themselves. The time it takes for this process is something which can't be changed though by me, so I guess patience is key when getting apps from F-Droid :)

FlorisBoard is currently in Closed Alpha Testing on Google Play, meaning the app is only visible to you if you join the Google Group linked in the README. With v0.4.0, FlorisBoard will enter public beta on Google Play, which makes FlorisBoard search- and discoverable for all users without prior joining the alpha group.

Of course, getting updates from the GitHub releases page is also an option :)
