### ISSUE TITLE
Equally Space Quick Actions and Copy&Paste in Landscape Mode

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#337]
It's a little weird in the normal, vertical mode, but especially in landscape mode, the spacing is VERY different, and it's a little weird.
Screenshots:
![Screenshot_20210212-121047_Omni Notes.jpg](https://user-images.githubusercontent.com/59611881/107777677-73532f80-6d43-11eb-87fb-5dd4d1aa7efd.jpg)

![Screenshot_20210212-121021_Omni Notes.jpg](https://user-images.githubusercontent.com/59611881/107777685-764e2000-6d43-11eb-8921-72e1c6f4683f.jpg)

**Comment by patrickgold** [comment]
Thanks for reporting! That's because the clipboard-cursor toolrow is technically a KeyboardView and my KeyboardView implementation auto-scales to fit the screen. The quick actions though are just a horizontal row of buttons contained in a layout and thus don't do this. Will add this to my todo list to fix this.

**Comment by tsiflimagas** [comment]
This seems to have been solved. I don't know in which release exactly, but in 0.3.14-beta07 it looks good.

**Comment by patrickgold** [comment]
Yup 0.3.14-beta07 solved this issue. Will manually close this issue.

**Comment by Glitchy-Tozier** [comment]
Good job! :)
