### ISSUE TITLE
Discussion for dictionary providing concept (bundled, dictionary packs, etc.)

### ISSUE THREAD

**Issue by goyalyashpal** [florisboard/florisboard#339]
_Originally posted by in https://github.com/florisboard/florisboard/issues/216#issuecomment-777715675_

<details>
<summary>Patrickgold said: Word suggestions will be my next main dev goal for sure, </summary>

... alongside with importing dictionaries dynamically (import from file system). I am unsure if I make some "alpha alpha GitHub only releases" so interested persons can try this out while it is in development or if I just let people use the auto-generated debug artifacts (if they want to test out each new step). Especially at the beginning it will be very interesting to see how I implement suggestions and things in this area may change from commit to commit. My plan for supported languages is English (US) only until the basic structure and code for suggestions is there. Then I will slowly expand it to Portuguese [(Brazil)] and German, and if that works further and further until I have all languages that the dictionary source supports.

</details>

I hope the word suggestions will be additional things and not bundled in. 'cause the app size is a big premium for me. Bundling the dictionaries in will increase the size a lot (i guess), and i dont want to ditch another sooo cool app. (i already have to ditch open keyboard as its app size jumped from 24 MiB {1.3} to 40 MiB {1.4.2}

Please please please dont fall for word suggestions/dictionaries. I am sure there would be some external package for dictionaries - that people can download externally - considering this is such a common thing. Ur keyboard is one of my main keyboards (and i use F-Droid only keyboard apps) and i cant afford to ditch it. (but if size increases, i will have to)

**Comment by patrickgold** [comment]
Original response by me in https://github.com/florisboard/florisboard/issues/216#issuecomment-777895964:

Well how should I put it - it is very difficult to find a way to solve this problem without disagreeing with at least 1 side. I've got quite some feedback about this. Some people told me that they hate the way AnySoftKeyboard handles dictionaries because for everything you need you basically have to visit the app store to install it afterwards and they want to have it bundled. Others have told me that it is important that the app size stays small (including you) and that they want to be able to load dictionaries after installation.

Now there's a very elegant solution to this, if it wasn't for this: FlorisBoard is a privacy-focused keyboard and thus I've set the goal to NEVER use the `NETWORK` permission in the core app. This disables the else beautiful solution to provide a dynamic in-app "dictionary-store" which would give you ability to select and download additional dictionaries (hosted either on GitHub or some CDN) without ever leaving the FlorisBoard app.

As for the v0.3.8 release, which will wrap up Phase 1 of the suggestion implementation, the only dictionary that will be bundled in is the English (US) one and it only has a size of ~1.7MB.

For Phase 2, I will definitely look into this issue though and hopefully find a way to solve this problem while avoiding the use of the `NETWORK` permission. My ideas:

1. Solve it how AnySoftKeyboard did, with dictionary packs on GPlay and F-Droid (Personally I dislike this idea though)
2. Make a beautiful little web page which gives you the ability to download a dictionary file from the GitHub repo. Then you either go to FlorisBoard and open the file selector, select the file and import it. Or you share the downloaded file with FlorisBoard via the Android share menu. This solution is way less elegant than the inbuilt dictionary store, though way more privacy friendly.
3. ....

What are your thoughts to my ideas? If you have another possible idea, feel free to suggest it to me.

**Comment by yashpalgoyal1304** [comment]
suuuper niiiiice patrickgold :)

**Comment by yashpalgoyal1304** [comment]
thoughts:
- Separate app for each language's dictionary pack doesnt seem right.
- But having a single app for all the managing all of these seems like a good way to go.
- This can be extended to house all non-bare bones things - dictionaries, and gifs (mentioned in above comment by glitchy)
- Maybe something like global dictionaries can be figured out\
which can be used by multiple keyboards system wide (just like libraries i guess). It sure seems a bit of too much of a hassle in the beginning, but i think it can save time and space. If Keyboard devs like u, **simple board**, **open board** etc join forces to tackle dictionary tasks. Be it some file based, or app based.

**Comment by patrickgold** [comment]
Ok so now my thoughts to your thoughts:

> Separate app for each language's dictionary pack doesnt seem right.

That's what I think too.

> But having a single app for all the managing all of these seems like a good way to go.

It would be best if it was achieved somehow in the core app, but I have currently no clue how that could look like elegantly, without manually importing files. If I come up with a new concept, I will post it here.

> This can be extended to house all non-bare bones things - dictionaries, and gifs (mentioned in above comment by glitchy)

For GIFs + Stickers, I am 95% sure that it will be a separate extension pack, as these are a nice-to-have, but non-essential. Dictionaries on the other side are very essential and it should be easily accessible, so I am not sure how to handle that.

> Maybe something like global dictionaries can be figured out which can be used by multiple keyboards system wide (just like libraries i guess)

That's a pretty neat idea which sounds really nice. Though the first problem arises in the format we use: AnySoftKeyboard and OpenBoard use the AOSP Dictionary format (`.dict`), which uses inherited code from LatinIME to read those files and work with them. FlorisBoard uses the Flictionary format (`.flict`, see [format spec](https://github.com/florisboard/dictionary-tools/blob/main/flictionary.md)) and also uses a completely different codebase to parse and work with those files... I will keep this idea in mind for now, maybe sometime in the future something in this direction can be achieved :)

**Comment by kj7rrv** [comment]
Would it work to download dictionaries from a Web site and then load those?
That doesn't seem too complicated (at least to me).

**Comment by patrickgold** [comment]
> Would it work to download dictionaries from a Web site and then load those?

Would definitely be an option as I stated in my original comment.

**Comment by kj7rrv** [comment]
If you end up using that approach, would it be possible to have FlorisBoard
automatically open .flict files? (Like how the Package Installer auto-opens
.apk's)? That would allow for a Web interface as well as an app to act as a
store.

**Comment by patrickgold** [comment]
> If you end up using that approach, would it be possible to have FlorisBoard
automatically open .flict files?

I can half-way automate it. The user clicks on the download button for a Flictionary file he wants on the web page and then after finishing downloading, depending on the browser either the file name or the "Open" button has to be pressed in the download interface of the borwser. Everything else can be handled by FloirisBoard by defining a VIEW Intent for `.flict` files, which allows me to open an import interface activity.

**Comment by TPS** [comment]
I suppose the only way to make _everyone_ happy is to allow Florisboard to flexibly allow _all_ of the above (& more, as folks keep coming up w/ ideas).  I expect, _however_ this implemented, there'll _next_ be much clamoring for grammar check, then style verification, à la word processors.

@patrickgold The only thing I request, re: this, is to make sure this functionality __remains working__ long after you've moved onto other projects.  I'm still using the hoary ancient [Hacker's Keyboard](https://github.com/klausw/hackerskeyboard) — originally Android **_2.x_** — b/c of the layout (but looking for replacement, hence my lurking involvement here), & this _specific_ functionality is broken (other than US English builtin), precisely because all the official _distribution_ mechanisms are defunct.  For this reason, something like supporting _everything_ is important, as @ least some of those should remain in the (software-) far-future.

**Comment by victorbnl** [comment]
Well I think you have to have it bundled, because there are many more users that want it than folks that don't want it. Maybe you could like make two versions of the app?

**Comment by Tmpod** [comment]
I do see your point, but I am unsure that will truly be a problem. Making two versions of the app can also lead to confusion, since the user will be presented with too very similar entries on their store of choice. I believe between that and having separate apps for each language pack, the latter is preferable. A clear distinction can be made between the "actual" keyboard app and language packs, however a distinction between the keyboard app and the keyboard app + languages can get blurry.
Furthermore, you'd eventually face a problem of the app size being stupidly big because it includes **all** languages. In practise, no one will ever use all of them at once, so I don't think it makes sense to pack everything.

**Comment by yashpalgoyal1304** [comment]
It's not about "folks dont want it" - its that their devices dont support
it :( \
Dont just push ur side.

**Comment by patrickgold** [comment]
> Also I think it would be good to have some traditionnals users not especially interested in open source that take this keyboard, and for this I think it's almost required to have it bundled or they'll just say "Nah, too difficult, I'll switch back to GBoard"

The thing is, Gboard does not bundle its dictionaries, it dynamically downloads it from Google servers in the runtime and thus their APK size is relatively small wide providing a lot of dictionaries. Which is of course the most elegant solution imo, but the privacy aware users won't be happy with me here when I add the NETWORK permission to have access to the Internet...

> Well I think you have to have it bundled, because there are many more users that want it than folks that don't want it. Maybe you could like make two versions of the app?

I'd like to have 1 core APK only + extension packs for the sake of maintainability.

**Comment by victorbnl** [comment]
Just tell in the README why there's the network permission, I think it's a good reason

**Comment by patrickgold** [comment]
> Just tell in the README why there's the network permission, I think it's a good reason

I mean many devices nowadays can block internet access for specific apps, can't they? So if some user really means he does not want it, he can turn it off in the system and FlorisBoard will continue to work flawlessly. I'd definitely add it to the List of permission wiki page alongside with an explanation for the use.

**Comment by victorbnl** [comment]
Yes, I'd really prefer it over the workarounds like bundling everything or using other apps

**Comment by patrickgold** [comment]
Doing it this way allows also to add new dictionaries without updating the app, only the "dictionary-repo-cache" by hitting a refresh button within FlorisBoard.

**Comment by yashpalgoyal1304** [comment]
> I mean many devices nowadays can block internet access for specific apps

just for the records, my device doesnt allow that. But yeah, whatever feels apt to you :) \
Also, just for ur info, some apps have separate f-droid and play store version. So, that can be a way too, in case it hinders f-droid release in any way

**Comment by patrickgold** [comment]
> just for the records, my device doesnt allow that.

If Android would give the NETWORK permission just the same importance as other toggle-able permissions already on a stock level, this would be so great...

I don't think that FlorisBoard needs a separate F-Droid/GPlay version, as these are often required by other apps because of proprietary analytics or other modules, which FlorisBoard does not have and will never have. And for the NETWORK permission alone this shouldn't pose a problem.

**Comment by kj7rrv** [comment]
It seems like most people wouldn't mind NETWORK permission on a FOSS app,
since it can be easily verified that it does not track users?

**Comment by ildar** [comment]
On networking use: most users are ok with it until it sends out the user's data. And (semi-) paranoid part of any community would install firewall anyway.

On dictionary formats:
1. being able to use system dictionary is an advantage.
2. but I don't see anyone suggesting (lib)hunspell which is the de-facto standard in Linux and LibreOffice. This allows a huge variety of languages to use.

**Comment by tsiflimagas** [comment]
@ildar hunspell seems interesting. I don't know how big their dictionaries are, but I see they have n-gram word prediction. I wonder if their algorithms have anything helpful for FlorisBoard.

**Comment by pokegamer5547** [comment]
This seems like a bit controversial topic going on. But i want to give a opinion. It's true that not all phones supports network blocking but those people who are really worried about internet access can use firewall apps or those who are using VPN can use OpenVPN (or any VPN)with split tunneling feature along with "block connections without VPN" which can block internet of specific apps without disabling VPN. 
But @patrickgold , if you are thinking of going with internet approach, then please also give a option to manually import language packs/dictonaries for people like me who doesn't want internet access and can block it with VPN or firewall. And also when selecting dictonary pack in florisboard settings, please give a warning why florisboard requires internet access for those who are really concerned about it. I guess this way both side feel safe. This approach is way better than gboard since it literally requires internet for dictionaries.
Also just an extra suggestion: if possible please make english US avaialble by default in Florisboard since it's just one language pack and it's most spoken language.

**Comment by yashpalgoyal1304** [comment]
> Also just an extra suggestion: if possible please make english US avaialble by default in Florisboard since it's just one language pack and it's most spoken language.

👎 👎

**Comment by atikattar1104** [comment]
Hacker's Keyboard Have It's Dictionary Plugin Apps On SourceForge, Along With Some Other APKs. Perhaps, This Can Be Done The Same Way. 
# For Example, :- 
1) For People Who Don't Want To Let Keyboard App Use Internet, A Separate Github Repository, Which Will Provide APK Releases Of Dictionary Plugin Apps For Keyboard, And Their Source Code.

2) For People Who Don't Want To Leave Keyboard App, A Download Page Implementation, Which Will Download Dictionary Data From Same Github Repository, And Add That Dictionary Data To Keyboard App.

# Also,
Instead Of Downloading Dictionary Data, Keyboard App Can Be Used To Install Plugin APKs And User Can Install Them As They Want.

# Also,
All Of The Above Steps Can Be Done Manually By User

**Comment by Pantyhose-X** [comment]
### dictionary packs
#### Need to delete a lowercase duplication item

https://openslr.org/14/ > BEEP Dictionary Summary: Phonemic transcriptions of over 250,000 English words.
> I use notepad++ and TextFX to remove duplicates and case, 164.146 English words. [English.txt](https://github.com/VaibhavCodeClub/learn/files/14443439/English.txt)

https://openslr.org/21/ > Spanish Word list
https://openslr.org/34/ > Santiago Spanish Lexicon
https://openslr.org/55/ > Chinese Word list
https://openslr.org/resources.php > other languages

**Comment by patrickgold** [comment]
This discussion is superceeded by the upcoming official addons store, please see issue #2468 for more.

Although dictionaries do not exist in the form anymore we discussed in this discussion they will appear in the form of "language packs" in the next major revision v0.5. The addons store both solves the problem of keeping the APK size small and not adding the NETWORK permission in a creative but intuitive way. To de-duplicate any discussions I will close this issue, if you have comments on the addons store plan please comment them in the linked issue!
