### ISSUE TITLE
all round Suggestions

### ISSUE THREAD

**Issue by yashpalgoyal1304** [florisboard/florisboard#341]
**update:** https://github.com/florisboard/florisboard/issues/341#issuecomment-778764176 : following have been split into separate dedicated issues. So, have hidden the images as a cleanup here. the images are already there in the dedicated issues.

### Basics first:

1. **Smartbar**
the button there should be "toggle select mode" rather than "select all" in my opinion.
2. **Themes**
 "Adapt colors to app" shouldnt disobey borderless option

^

4. **Numpad**\
The numbers on numpad are way too small, and doesnt fit. Feels weird using it. And the numpad in the dialer is completely different too, i thought they were same thing. (the bottom one - not to scale). I am mentioning dialer numpad in the hope that maybe it can suggest something on how can normal numpad and its layout be improved.

-----
### Additionals (may contain continuation of above written basics)

1. **Smartbar** 
    But however, reading the way many people have said it here, it seems to me that people are ~okay with~ **frequently** using select all too. So, if that is the case, smart bar may be made customisable i.e. which tools/icons to show there be user choosable.  \
 _It is not split per se, as it seems out of scope currently. And i dont have interest in it either - if it's not required for the purposes mentioned in the basics section above._ \
_But feel free to open this as a separate one if u want this, but mention this issue's link there/or mention the new issue's link here_
2. **Themes**
    - themes UX maybe streamlined a bit 
    - themes preset options maybe diversified (bg color, accent color, etc)
    - i have some ideas on how it can be, if u are interested - will try to come up with mockups

^

5. **Layout**\
Can ortholinear layout be added? 😋\
Inspired via https://www.youtube-nocookie.com/embed/Ho_CFfdsmc8?start=346 \
Rough mockup:
 

---
<details><summary>Following were duplicates:</summary>

3. **Emojis and Panel**
     - #142 swipe between categories gesture should be there
     - #268 what are ur thoughts for having a "history" and "favourites" category? 
     - #45 ... and for having ability to search emojis? 
     - #56 Novel suggestion: enter emojis with shortcut/syntax - like here in gitlab - `:smile:` the matching emoji will be shown in the suggestions bar

</details>

[4jmage_2021-02-13_01-53-00]: https://user-images.githubusercontent.com/19423063/107818958-631c6e00-6d9e-11eb-92e3-542faa2f9186.png
[4image_2021-02-13_01-53-00]: https://user-images.githubusercontent.com/19423063/107818973-69124f00-6d9e-11eb-8cab-df78e9cf2418.png
[5photo_2021-02-12_23-30-57]: https://user-images.githubusercontent.com/19423063/107818974-69aae580-6d9e-11eb-8e18-706e93e28a6b.jpg
[6photo_2021-02-12_23-30-57]: https://user-images.githubusercontent.com/19423063/107818978-6a437c00-6d9e-11eb-811c-5601336c759a.jpg
[1photo_2021-02-12_23-30-49]: https://user-images.githubusercontent.com/19423063/107851466-2d27ca00-6e30-11eb-898f-d6bc42ad4b5b.jpg
[2photo_2021-02-12_23-30-55]: https://user-images.githubusercontent.com/19423063/107818583-da9dcd80-6d9d-11eb-9765-837da474f49f.jpg
[3photo_2021-02-12_23-30-55]: https://user-images.githubusercontent.com/19423063/107818585-db366400-6d9d-11eb-84da-cf36e92f8081.png
[3photo_2021-02-12_23-31-01]: https://user-images.githubusercontent.com/19423063/107818573-d83b7380-6d9d-11eb-859d-f326cc8dbfd5.jpg
[7photo_2021-02-12_23-30-55]: https://user-images.githubusercontent.com/19423063/107850639-e931c680-6e29-11eb-8b74-a6a088c76d5a.png
[q6HAggbrop]: https://user-images.githubusercontent.com/19423063/107852192-66af0400-6e35-11eb-98f5-421ff648fba6.png

**Comment by yashpalgoyal1304** [comment]
hi, have cleaned it. Looking f/w to u :)

**Comment by yashpalgoyal1304** [comment]
the basics were one line things, so, thought to hear ur thoughts before splitting up these.

**Comment by yashpalgoyal1304** [comment]
I just noticed (thanks to borders) that there is quite enough space to show the numbers in sufficient height too. As shown in the below image. So, making me wonder if there was some specific reason for setting the letter height for numbers to low. ![photo_2021-02-13_21-23-42 - Copy](https://user-images.githubusercontent.com/19423063/107854849-bfd26400-6e44-11eb-9ccf-9166f2745253.jpg)

**Comment by patrickgold** [comment]
Thanks for your long list of suggestions + bug reports. A lot of the suggested things are already open in some issue, if I find it I will link it.

>  the button there should be "toggle select mode" rather than "select all" in my opinion.

I think the select all is more useful, as the toggle select mode requires a few "special" logic parts to even work. If you go to the selection keyboard, there you can see my implementation of such.

> But however, reading the way many people have said it here, it seems to me that people are okay with frequently using select all too. So, if that is the case, smart bar may be made customizable i.e. which tools/icons to show there be user chooseable.

Ah I see you mentioned it too that select all is way more frequently used. Customization options for the clipboard tools could be the solution.

>  "Adapt colors to app" shouldnt disobey borderless option

That's true the current behavior does not account for the "Show key border" property. Could you open a new issue for this so I can separately deal with this suggestion? Thanks.

>  swipe between categories gesture should be there

Planned for the emoji rework in v0.5.0. (See #142)

>  The numbers on numpad are way too small, and doesnt fit. Feels weird using it. And the numpad in the dialer is completely different too, i thought they were same thing. (the bottom one - not to scale). I am mentioning dialer numpad in the hope that maybe it can suggest something on how can normal numpad and its layout be improved.

Thaaaat's a bug :) Normally, the numbers should be as big as the numbers in the blue themed screenshot you provided. Could you open a separate issue for this so I can handle with this bug? Thanks!

> themes UX maybe streamlined a bit  [...]  if u are interested - will try to come up with mockups

I would definitely be interested in some mockups if you have the time, because I am not sure what exactly you mean by streamlining and what you suggest you want to get improved.

> what are ur thoughts for having a "history" and "favourites" category? 

See #268, planned also in the v0.5.0 emoji rework

> ... and for having ability to search emojis?

See #45 

> Novel suggestion: enter emojis with shortcut/syntax - like here in gitlab - :smile: the matching emoji will be shown in the suggestions bar

See #56 

>  Can ortholinear layout be added? 😋

Definitely can, but requires a few extra implementation in the layout engine and a new icon for the forwards delete. Could you also open a new issue for this?

The reason why I want to have every separate feature request in a separate issue is the ability for me to better keep track and to be able to implement one thing and close one issue with it.

**Comment by Glitchy-Tozier** [comment]
> I think the select all is more useful

I absolutely agree with this, please keep the copy&paste-menu as awesome as it is!  :)

That being said, one day an option for a self-assembled top-bar might be interesting to some people.

**Comment by yashpalgoyal1304** [comment]
With toggle select mode, i meant this button in text editor mode (i guess u are saying same thing, but still thought to clarify). Maybe it can be given as one more button? rather than select all that is! There is just enough space for one more icon to come there.

![zjw3NnJ7ec](https://user-images.githubusercontent.com/19423063/107872959-6ca7f200-6ed4-11eb-89cf-5643db8d680d.png)

Rough mockup: this is basically a combination of [area🡭](https://www.iconfinder.com/icons/6602651/area_design_graphic_select_selection_tool_icon) and text cursor. The circle underneath was used to ensure equal spacing.
![photo_2021-02-12_23-30-39 (2)](https://user-images.githubusercontent.com/19423063/107873454-b2ff5000-6ed8-11eb-96b0-9316fde7f4f2.jpg)

If that sounds like feasible, i'd split that too in a separate issue

**Comment by patrickgold** [comment]
Hmm I see it is technically possible to add this but like I said the wonky selection toggle logic would have to be ported to work in the SMartbar context as well. I will add it to my todo list.

**Comment by Glitchy-Tozier** [comment]
Personally, I'd prefer to not have the copy&paste-bar cluttered by an option I never use.

(Also, a little off-topic: why is the `cut`-button not next to the `copy`-button? That would make sense, from a semantic perspective as well as from a functional point of view. (Because in that case it could be closer to the `select-all`-button.))

**Comment by yashpalgoyal1304** [comment]
"i"

**Comment by yashpalgoyal1304** [comment]
all split. hooof. :)

**Comment by patrickgold** [comment]
> (Also, a little off-topic: why is the cut-button not next to the copy-button? That would make sense, from a semantic perspective as well as from a functional point of view. (Because in that case it could be closer to the select-all-button.))

Because select all + copy together is often used, so it makes sense to have them by each other. The arrow keys are in the middle because it looks best and it has some kind of symmetric appearance.

> all split. hooof. :)

Thanks a lot! I will label all your issues accordingly but not comment on each for now, just so you know I still have seen all of them.

**Comment by yashpalgoyal1304** [comment]
> select all + copy together is often used, so it makes sense to have them by each other

yeah, i was thinking exactly same yesterday. That's really nice thought. I like it rather than just following conventions :)

> but not comment on each for now, just so you know I still have seen all of them.

okay. yeah, that makes sense. thanks for informing me about thiss. Thanks :)

**Comment by Glitchy-Tozier** [comment]
> Because select all + copy together is often used, so it makes sense to have them by each other. The arrow keys are in the middle because it looks best and it has some kind of symmetric appearance.

Not saying it shouldn't be there. I'm saying Cut should also be on the left side of the two arrow-keys.

**Comment by yashpalgoyal1304** [comment]
hi, since the purpose of this issue is complete. so closing this. but saying just for clarification, the closure doesnt mean that i am doing so to hinder the discussions :)
