### ISSUE TITLE
Setting to have Select All, Copy, Left Arrow, Right Arrow, Cut & Paste w/ Suggestions

### ISSUE THREAD

**Issue by trymeouteh** [florisboard/florisboard#349]
Please have a setting were you can have the select all button, copy button, left arrow button, right arrow button, cut button and paste button just like when the setting "Display suggestions while you type" is disable in the smartbar but to have this row of buttons when you enable the "Display suggestions while you type" setting. Here is a few ways I vision this to be achieved

1. The smartbar has a arrow button ">" in a circle on the left side. You could add another arrow button "<" on the right side that will show/hide the select, copy, left arrow, right arrow, cut and paste buttons.

2. The smartbar has a arrow button ">" in a circle on the left side. The select, copy, left arrow, right arrow, cut and paste buttons can be added to the buttons in the left ">" button.

3. Have two smartbars, one stack on the other. One smartbar is the select, copy, left arrow, right arrow, cut and paste buttons and the other smartbar is the word suggestions.

Great keyboard app BTW! Thanks for putting it on F-Droid!

**Comment by patrickgold** [comment]
Thanks for your suggestion!

I have already discussed this with others and we had the idea to make a swipe left/right action in the Smartbar, which would allow you to quickly switch between different Smartbar contents. The problem is that I have absolutely no space for an extra arrow button, but a swipe action is definitely possible.

> Have two smartbars, one stack on the other. One smartbar is the select, copy, left arrow, right arrow, cut and paste buttons and the other smartbar is the word suggestions.

Stacking two Smartbars on top of each other doesn't look that good imo

**Comment by trymeouteh** [comment]
I think the swipe action will be best and the arrow will be good if you have room.

**Comment by trymeouteh** [comment]
Amazing work! Cant wait for word suggestions!
