### ISSUE TITLE
Barcode and QR code scanner

### ISSUE THREAD

**Issue by iceleo-com** [florisboard/florisboard#365]
Hi,

Thank you for your hard work!!!

I'm working in a warehouse. Every SKU, BIN, and product links are a barcode or QR code. If your keyboard can support Barcode and QR code scanner, it would be very nice.

**Comment by tsiflimagas** [comment]
Wouldn't it be better to use a qr scanner app for that? I don't quite see how could this be implemented in a keyboard app.

**Comment by patrickgold** [comment]
Thanks for your suggestion. I don't see the point of integrating a barcode scanner into a keyboard, as one can easily use one of the many barcode scanners available for Android, even open-source ones. The focus of FlorisBoard is to be a keyboard with additional features related to a keyboard, not an all-in-one app which has everything implemented. Thus I am sorry to say that this will probably never be implemented into ForisBoard...

**Comment by maverick74** [comment]
Hi,

I personally was also searching for this!

case point:

In a warehouse you might need to insert a specific code into a webpage form.
For example, imagine you use software like Salesforce, Odoo, etc and you want to search for a product in your webservice. When you press the desired field the keyboard popup. Now if the sparepart has a barcode or a qrcode we could just press the keyboard button, take a photo and the (sometimes big - like 19 digits) reference would came up.

At the moment, using regular barcode readers zxing, for example, you have to copy that to the clipboard then return to the webpage and paste it. This may seem easy for all of us... but try to teach that to a 50+ years worker :)

As such, i would also vote for this :)

**Comment by ThreeDeeJay** [comment]
A reasonable compromise would be adding a dedicated button to temporarily switch to an external IME,
like https://github.com/raphaelm/android-barcode-keyboard

I'm still, in the year of our lord 2024, rocking [Swype](https://github.com/ThreeDeeJay/swype/releases/latest) (mainly because it's hands down the best swipe typing prediction I've ever found) with [SwypeTweaks](https://github.com/ThreeDeeJay/SwypeTweaks/releases/latest) to make the quick-tapping the mic button launch Google voice typing, and by long-pressing it, it switches the QR/barcode scanner keyboard. But since Android will probably kill old 32-bit apps support for good eventually, I'll have to switch to something else, so hopefully by then Florisboard will have implemented a decent glide typing and other features like these 👀🤞
