### ISSUE TITLE
Make settings accessible in system settings

### ISSUE THREAD

**Issue by mortezae** [florisboard/florisboard#366]
Make settings accessible via Android Settings -> Language and input -> On-screen keyboards

**Comment by patrickgold** [comment]
Thanks for your suggestion! I know that this is currently not possible, because that's one thing I tried to implement like 10 times and to this day I am unable to figure out what I am doing wrong. Android just won't detect the Settings activity, even though I've added it to the `method.xml` file. If either I or someone else figures this out, this will definitely start working :)

**Comment by patrickgold** [comment]
Above PR rather accidentally fixes the Language & Input settings bug, FlorisBoard's settings can now be accessed via that screen. Will be released with v0.3.13-beta01 in the next few days.
