### ISSUE TITLE
Text selection gesture

### ISSUE THREAD

**Issue by Donkey-Doug** [florisboard/florisboard#370]
Make it possible to press and hold the shift key and swipe left/right across the space bar to select text using gestures.

**Comment by patrickgold** [comment]
Thanks for the suggestion! The problem with this is that the shift key triggers for the `keydown` event rather than `keyup`, so every time you do this, the capitalization of the keyboard changes. Another problem I see here is for languages which do not have a shift` key, they can't use this feature at all. I will add this to my todo list, but we have to think of a few solutions for the mentioned problems before implementing this.
