### ISSUE TITLE
Make backspace long press delete whole world

### ISSUE THREAD

**Issue by Vendicated** [florisboard/florisboard#374]
Currently deleting words is really slow. This would increase efficiency by a lot

**Comment by Waelwindows** [comment]
Left swipe on backspace has an option for deleting whole words

**Comment by D3SOX** [comment]
@Waelwindows I think @Vendicated meant that when you hold down backspace for a certain amount of time, it starts deleting words

**Comment by Waelwindows** [comment]
I get that. I'm just saying it should be easy to implement as it's already implemented in a different way

**Comment by haarp** [comment]
If this is implemented, it must be an option. I hate whole-word deletion when backspacing.

Algorithms don't understand what constitutes a "word" for a given context and end up deleting too much. Backspace an URL with whole-world deletion enabled? Whoops, the entire URL is now gone!

**Comment by Invisible3ck** [comment]
Holding shift and pressing backspace should delete the entire word in my opinion.

**Comment by mxvin** [comment]
It is much faster to delete mistyped word by holding backspace, this is same like swiftkey do. I agree, it must be an option, because not everyone liked this.
This will be a supplement of the existing "swipe backspace to delete", I like that, never seen it on other keyboard
+1

**Comment by patrickgold** [comment]
Forgot to link this issue to PR #1822 (because there was a duplicate issue #637 for the exact same request), which was released a few days ago in 0.3.16-beta01. 

https://github.com/florisboard/florisboard/pull/1822/commits/64fefef31ae16d00458a30ba2278aebaee9edd2b adds an option in the gesture preferences to define the long press action of delete. By default it is set to "Last character" as this makes more sense, but you can optionally set it to "Last word" if you prefer so.

As such I will close this issue as implemented.

**Comment by silverwings15** [comment]
glad to see this super awesome feature implemented! if i may, i would also suggest there to be a haptic feedback each time a word is deleted.

**Comment by tsiflimagas** [comment]
Generally, new suggestions should be made into new, separate issues. Making suggestions in closed issues isn't convenient, as such issues aren't tracked anymore, and it will probably be overlooked.

**Comment by silverwings15** [comment]
i was afraid of clutter so decided to piggyback on a relevant closed issue, but you're right, i'll remake it as a new issue. thank you for the heads up
