### ISSUE TITLE
Excessive clipboard access

### ISSUE THREAD

**Issue by Vendicated** [florisboard/florisboard#376]
#### Short description
Not really a bug, simply bad design. The keyboard accesses the clipboard on every keypress. I only noticed because I get a toast every time an app accesses the clipboard, but I'm assumming this excessive access makes performance worse

#### Steps to reproduce
N/A

#### Environment information
- FlorisBoard Version: 0.3.7 
- Install Source: Fdroid 
- Device: OnePlus 3T 
- Android version, ROM: Havoc Os 3.12 Android 10 

https://user-images.githubusercontent.com/45497981/108467180-13014800-7285-11eb-93b9-17b99c27aa08.mp4

**Comment by Glitchy-Tozier** [comment]
I find this extremely funny! Great find!

**Comment by patrickgold** [comment]
Do you by any change have the clipboard suggestions (Settings > Typing) enabled? This would help me in finding the source of this behavior/bug.

**Comment by Vendicated** [comment]
My bad, should have included this. It happens no matter the state of that toggle so its not related to it

**Comment by patrickgold** [comment]
Hmm, that's really strange but thanks for letting me know! Will definitely have to investigate into this, maybe the clipboard checker for the clipboard suggestions gets accidentally called (how exactly I am not sure, but its my primary suspicion).

**Comment by D3SOX** [comment]
Off  topic: It's kinda scary that every application can literally access the clipboard any time without a permission that you must explicitly grant. It's the same on PC (I think across Windows macOS and Linux) but permissions on PC are a mess in general. I think macOS does the best there and maybe Linux can be also okay with Firejail but I've never tested that and I don't know if it's a viable option to run everything inside Firejail.

@Vendicated is this access granted toast a feature of Havoc OS or how did you get that?

**Comment by patrickgold** [comment]
> Off topic: It's kinda scary that every application can literally access the clipboard any time without a permission that you must explicitly grant. (Or is this because Florisboard is an IME?)

FlorisBoard, if the default IME in your system, has full clipboard access given by Android automatically. Other apps can read your clipboard only if they have input focus (e.g. not in the background) or if they define the `android.permission.READ_CLIPBOARD` permission, which gets automatically granted on install. Great security, isn't it... You as a user can revoke that permission from apps, but with the exception of some custom ROMs only via adb. Because of this, at some point FlorisBoard will get an internal clipboard manager which has the ability to not sync with the system clipboard to prevent this from happening.

**Comment by D3SOX** [comment]
@patrickgold Thanks for the explanation!

**Comment by patrickgold** [comment]
Ok so I've investigated into this issue and the only repeatedly access to the clipboard happens here: https://github.com/florisboard/florisboard/blob/7e56094f5cde7bff7ec978f92de7f14fc5ee4319/app/src/main/java/dev/patrickgold/florisboard/ime/text/key/KeyView.kt#L547-L565

Every time the selection changes or the cursor moves due to key presses, this method is invoked to refresh the enabled state of the clipboard tool icons. On line 556, I am querying the system if it has a primary clip (means it has data to paste) and I set the paste icon visibility based on this. No data is read at this point, this would only happen if you have clipboard suggestions turned on and the system reports that it has new clipboard data.

I am unsure how to fix this, as it is bad UX if I let the paste icon enabled all the time and then nothing happens if there's no data in the primary clip when the user clicks on the icon.

**Comment by Glitchy-Tozier** [comment]
> I am unsure how to fix this, as it is bad UX if I let the paste icon enabled all the time and then nothing happens if there's no data in the primary clip when the user clicks on the icon.

I agree, that wouldn't be good design.

Why do you request this information on wvery key-press?

**Comment by patrickgold** [comment]
> Why do you request this information on wvery key-press?

I update the enable state every time the selection changes, this has been the only reliable way to determine the enabled state thus far. Maybe I find another way which avoids doing that, will see.

**Comment by patrickgold** [comment]
Since February 27th a lot of time has passed and FlorisBoard has changed a lot. Could you try out if this issue still occurs on the latest stable release v0.3.12? Thanks in advance!

**Comment by Vendicated** [comment]
the issue does not happen anymore! :)
