### ISSUE TITLE
Fast typing ruins the app

### ISSUE THREAD

**Issue by e-edgren** [florisboard/florisboard#388]
#### Short description
You can't fast type because that will send the text without any warning on for an example Telegram. You can't fast type A either because doing so will replace the A with a dot (.).

#### Environment information
- FlorisBoard Version: 0.3.5 (latest on F-Droid, please fix)
- Install Source: F-Droid
- Device: Nokia 7.2
- Android version, ROM: 10, stock

I can't reproduce these bugs in version 0.3.7, but I leave this bug report here in case this bug will occure later on.

**Comment by patrickgold** [comment]
> latest on F-Droid, please fix

I don't understand F-Droid, it seems that literally everyone has a different version of FlorisBoard available... (If I look at the F-Droid website [here], then the newest version is v0.3.7)

[here]: https://f-droid.org/packages/dev.patrickgold.florisboard/

As this bug is fixed in v0.3.7, I will close this report.
