### ISSUE TITLE
Long-pressing does not select the key as shown on the keyboard

### ISSUE THREAD

**Issue by nvllsvm** [florisboard/florisboard#39]
By default, long pressing _should_ insert the symbol shown on the keyboard. For example, the "A" key shows an "@" symbol on it so long-pressing it should open the popup with the "@" symbol selected. This applies to some other keys like "u" and "e" - maybe more.

**Current**
Long-pressing the "A" key opens the long-press popup and selects the "á" symbol by default. 
![image](https://user-images.githubusercontent.com/6550543/99003440-165d9880-250c-11eb-9944-b9d20cc0e9dd.png)

This is unexpected as the keyboard clearly shows that long-pressing the "a" key can be used to insert the "@" symbol.
![image](https://user-images.githubusercontent.com/6550543/99004474-20cc6200-250d-11eb-89cb-1abb2b911931.png)

**Desired**
Long-pressing the "A" key opens the long-press popup and selects the "@" symbol. Both the AOSP and AnySoftKeyboard keyboards function this way. I believe Gboard also works this way.

AOSP keyboard
![image](https://user-images.githubusercontent.com/6550543/99003638-6177ab80-250c-11eb-91ef-45152b977fe8.png)

AnySoftKeyboard
![image](https://user-images.githubusercontent.com/6550543/99003647-650b3280-250c-11eb-9c94-4eafe147221e.png)

**Environment information**
- FlorisBoard Version: 0.2.3
- Install Source: GitHub
- Device: OnePlus 6T
- Android version, ROM: Android 10 (LineageOS 17.1)

**Reproduce**
1. Long-press and release "a" key without selecting anything from the popup.
2. Notice that "á" is inserted.

**Comment by patrickgold** [comment]
This is less a bug but more a question how to interpret the "hinted" symbol. The hinted symbol in FlorisBoard is indicating that a symbol is accessible via long-pressing that key, but it doesn't automatically mean that it takes priority over the already existing popup keys defined for the currently selected locale (lets take `a->ä`, where it would be annoying if you had to move your finger for the `ä` because the `@` took priority).

This is intended behavior and you will find this for all keys which would have an extended popup without the symbol feature turned on. I am of course open to discuss if it should be changed, but this is how I wanted this feature to work.

**Comment by nvllsvm** [comment]
Some thoughts...

- The hints exist to make it easier to access certain characters without switching layouts. I'd argue that it _should_ become the default when enabled, but _only_ when it's enabled.

- A default of `a->ä` might make sense for some languages, but `a->@` is arguably a better default when some layouts like "English (United States)". The other choices are rarely used, if ever.

- It's inconsistent. The `a` key shows a `@` and the `d` key shows a `$`. Long-pressing `d` gives the alternate character while `a` does not.

- Follow the behavior of other keyboards if they all do it the same way. It's less jarring to a new user - especially for someone like me with a decade of muscle memory with this.

Personally, the current behavior is a blocker for me to use FlorisBoard. I'm excited that FlorisBoard is a brand new, **open source** keyboard for Android and would love to switch to it. Thanks for your work on this!

**Comment by patrickgold** [comment]
Thanks for your response!

> The hints exist to make it easier to access certain characters without switching layouts. I'd argue that it should become the default when enabled, but only when it's enabled.

That was also the idea behind this feature. The symbols also become the default if no extended characters for the subtype exists. If the symbol hint feature is turned off either a key has no extended characters (like the `d`) or it has its default popups.

> It's inconsistent. The a key shows a @ and the d key shows a $. Long-pressing d gives the alternate character while a does not.
> Follow the behavior of other keyboards if they all do it the same way. It's less jarring to a new user - especially for someone like me with a decade of muscle memory with this.

The inconsistency does also exist in Gboard and OpenBoard. The difference is that they are smarter when it comes to decide whether the symbol or an extended character should take priority. For instance in "English (US)" the `@` takes priority while in "German" the `ä` takes priority. I guess that there also inconsistencies for other locales as well. But regardless of the default popup character, the `@` _always_ shows as the hint. (Maybe I'm used to this inconsistency because I've used the German layout for years and my muscle memory knows that some characters are off)

> Perhaps another option for customizing the alternates?

Could be the solution to the problem, but I will see if I can manually differentiate if an extended symbol or an extended character should be the default, so the selection process better matches the one from other keyboards.

**Comment by zecamigo** [comment]
> The inconsistency does also exist in Gboard and OpenBoard. The difference is that they are smarter when it comes to decide whether the symbol or an extended character should take priority. For instance in "English (US)" the `@` takes priority while in "German" the `ä` takes priority. I guess that there also inconsistencies for other locales as well. But regardless of the default popup character, the `@` _always_ shows as the hint. (Maybe I'm used to this inconsistency because I've used the German layout for years and my muscle memory knows that some characters are off)

I've tested many keyboards (AOSP, AnySoftKeyboard and others proprietary) in several languages (english, portuguese, spanish, french) and never found this inconsistency before.

I agree  with @nvllsvm that the  desired behavior is 

Long press ===> hinted character.


Thank you for your hard work! I'm using it nevertheless and looks very promising!

**Comment by patrickgold** [comment]
@zecamigo Thanks for your feedback. I think there are a lot of factors playing into the inconsistency, as I've encountered them quite a lot with OpenBoard and Gboard (except for English (US), where the hint indeed always matches the selected popup). I'm using Android 10/Oxygen OS.

I will look into making this behavior toggle-able, so one can decide how it should work.

**Comment by HyknuF** [comment]
> I will look into making this behavior toggle-able, so one can decide how it should work.

i think this would be the best solution for different languages. for german purpose, it is very useful, imo actually necessary, to get a>ä, s>ß and so one. 

Again, a toggleable solution would be quite nice.

**Comment by patrickgold** [comment]
Above PR replaces the number row / symbol hint toggle with list preferences, which can bet set to `Disabled`, `Enabled (Hint takes priority)` and `Enabled (Accent takes priority)`. This is a solution for the key popup hint priority problem and allows to customize this behavior. Sometime in the future it is also planned that a smart selection process is added, which dynamically selects the right approach for each key like in OpenBoard, Gboard, etc.

This change will release later today with v0.3.2.

**Comment by nvllsvm** [comment]
The change works perfectly in 0.3.2, thank you!

**Comment by khlsvr** [comment]
I was wondering if I could modify what I see in the popups. Majority of the keys only has one extra key behind the popup right now on my finnish - dvorak. I would want to be able to add 10 different popups behind each key. Would this make the florisboard use much more resources and thus have a negative side-effect? If not, then it could be considered a wasted opportunity. If it's possible to even add words behind popups, you could add some strings you use a lot and have a true swiss knife in your keyboard. Anyway, just being able to pick up multiple utf-8 characters to those popups would suffice.

So currently the florisboard picks up the popups/hints from the current locale? So if the above mentioned feature is not possible/feasible for the florisboard itself, I wonder what is needed for me to modify the keyboard layout files the locale uses. Apparently there is at least some old app that probably was done for this purpose https://www.appbrain.com/app/custom-locale/com.mhoffs.customlocale It's just very old and not open source, not sure if it would work on my phone. Then I found this tutorial to create own custom keyboard layout, but not sure how that would get into the locale https://androiddvlpr.com/android-custom-keyboard-layout/

Can I access the layout files and edit them directly? I actually have done this on my home linux machine. I just edit the /usr/share/X11/xkb/symbols/cz file if I want to edit the layout of the czech keyboard. Then if I take that into use, I get the changes I have just made.

**Comment by khlsvr** [comment]
With finnish language and Dvorak layout - the hinted symbols with the setting to prioritize accented characters will pick the `ā` on long-pressing the `a` instead of the `ä`, then long-pressing `o` will pick `ò` instead of `ö`. These are characters that are widely used in finnish language. This is especially cumbersome for dvorak keyboard users, as the dvorak keyboard doesn't have a dedicated character for `ä` and `ö`. With swiftkey I have learned to type ä and ö with a shortening the long-pressing duration and just using the `a` and `o` longpresses for `ä` and `ö`.

**Comment by patrickgold** [comment]
This is probably because the `main` character popup prioritization is incorrectly configured (because at the time I didn't know which character popups need such prioritization and which don't. Could you name all base characters in Finnish which needs this? Like `a` -> `ä`, `o` -> `ö` etc. This way I can set the prioritization rules correctly. Thanks in advance!

**Comment by khlsvr** [comment]
Only those two are needed for Finnish. We have `å` also on our physical keyboards, but that's only because swedish is also the official language in Finland. Also `å` is under the same `a` popup so there's that too. I don't normally write Swedish with FlorisBoard so the following doesn't concern me, but for swedes they are using the same extra base characters as finns, the only difference is that they also use the character `å` widely. According to  https://www.sttmedia.com/characterfrequency-swedish#:~:text=Accordingly%2C%20the%20letters%20A%2C%20E,letters%20in%20the%20Swedish%20language the `ä` is more frequently used than `å` so probably if you want to fix the Swedish popups, you would want to make the exact same changes as you would with Finnish, by changing the long-press behind `a` to `ä` and behind `o` to `ö`. 

Thanks!
