### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MrSpenalzo** [florisboard/florisboard#404]
Attempting to paste error report but nothing on clipboard.

**Comment by Glitchy-Tozier** [comment]
Could you provide some more Information?

That's what the template was for.

**Comment by MrSpenalzo** [comment]
Apologies for confusing post.  I've been trying florisboard for about a week (pretty cool). I got a "sorry florisboard has crashed" message. At the prompt I chose to send error report which brought into new issue 404 here, but there was nothing on the clipboard to paste. I may have missed a prompt to copy, don't remember.  I tried to delete post but couldn't and deleted template in attempt to clean up entry. This happened in Cyanogen 13 (android6) on MotoE2. I'm pretty sure I was in os/home screen/KISS launcher and not an app when crash notification appeared; probably just calling up the keyboard. Thanks.

**Comment by patrickgold** [comment]
Hmm difficult to say why FlorisBoard crashed when given no stacktrace, the described pattern doesn't really help and since v0.3.7 a lot in the code base has changed. As there's not really something to work with here, I will close this issue. If the crash happens again and you are able to copy the stacktrace, then feel free to either reopen this issue or open a new bug report.
