### ISSUE TITLE
Distracting flicker as suggestions update

### ISSUE THREAD

**Issue by X-yl** [florisboard/florisboard#407]
After every key press, there is a visible flicker as the suggestions update in the smartbar.

#### Steps to reproduce
1. Enable suggestions 
2. Type something

#### Environment information
- FlorisBoard Version: 0.3.8
- Install Source: github
- Device: Samsung A50
- Android version, ROM: Stock android 10

https://user-images.githubusercontent.com/28653555/109469504-8a09be00-7a87-11eb-950e-c2291112b992.mp4

**Comment by X-yl** [comment]
I'm not sure whether this line does something useful but commenting it out fixes the issue.
https://github.com/florisboard/florisboard/blob/91cbbe74a311e64ec8ce13d81bb6f898c5b18bb0/app/src/main/java/dev/patrickgold/florisboard/ime/text/TextInputManager.kt#L362

**Comment by patrickgold** [comment]
Thanks for your bug report! While the flickering is certainly annoying, this is happening because the next word suggestions are currently not yet implemented, thus the flickering happens. I am intentionally resetting the suggestions here because else suggestions are displayed which don't match the current state. While your above mentioned fix would remove the flicker, I will add next word predictions in the next version, so the flickering will be gone then.

**Comment by X-yl** [comment]
Ah that explains it then. Alright, I'll go ahead and close this issue.
