### ISSUE TITLE
Abbreviate word suggestions

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#426]
#### Short description
Most of the time this isn't needed. however, in some cases there will be long words that should be abbreviated by some number of dots.

Looking for a prime example? It's…
![supercalifrag](https://user-images.githubusercontent.com/59611881/109777717-4ee0c980-7c04-11eb-984a-0a061b80f7fa.jpeg)
Even though the sound of it is something quite atrocious, people might want to use word-suggestions to type it faster.

#### Suggestion
Abbreviate it → The cut-off nobody will notice.
Supercalifragilisticexpiali…

#### Environment information
- FlorisBoard Version: 0.3.8
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10, whatever Samsung uses (one-ui?)

**Comment by patrickgold** [comment]
> Most of the time this isn't needed. however, in some cases there will be long words that should be abbreviated by some number of dots.

Definitely agree here, that's why I marked word suggestions as experimental. In many areas they are currently more a mess than anything else, but phase 2 will fix a lot of this.

> Supercalifragilisticexpiali...

That's a new word for me, it amazes me what words are embedded in the wordlist I don't know of :)

> whatever Samsung uses (one-ui?)

I think it's OneUI 2.0, but I could be wrong there. For me it is mostly enough to know what type of ROM you are using, because for instance a custom ROM behaves differently to stock which behaves differently to Smasung's OneUI.

**Comment by Glitchy-Tozier** [comment]
> That's a new word for me, it amazes me what words are embedded in the wordlist I don't know of :)

You don't know the word or you didn't know it existed as a suggestion?

> I think it's OneUI 2.0, but I could be wrong there. For me it is mostly enough to know what type of ROM you are using, because for instance a custom ROM behaves differently to stock which behaves differently to Smasung's OneUI.

Meaning that telling you about OneUI gives you more information than telling you it's Android 10?

**Comment by patrickgold** [comment]
> You don't know the word or you didn't know it existed as a suggestion?

No I haven't heard the word ever yet, but I just looked it up in DDG and it is the name of a song from Disney's musical film Mary Poppins it seems, so that's how this word made it onto the wordlist.

> Meaning that telling you about OneUI gives you more information than telling you it's Android 10?

No, telling me what Android version you use is the most important info in that line (because Android APIs behave differently and change in every version). I just wanted to state that it's probably OneUI because you placed a question mark after it.

**Comment by Glitchy-Tozier** [comment]
> No I haven't heard the word ever yet, but I just looked it up in DDG and it is the name of a song from Disney's musical film Mary Poppins it seems, so that's how this word made it onto the wordlist.

You should watch it eventually. In German though. The German songs are better.

> No, telling me what Android version you use is the most important info in that line (because Android APIs behave differently and change in every version). I just wanted to state that it's probably OneUI because you placed a question mark after it.

Got it.
