### ISSUE TITLE
Satus bar color is set by FlorisBoard in keyboard mode

### ISSUE THREAD

**Issue by unresolvedsymbol** [florisboard/florisboard#43]
Would be nice if there was an option to disable changing the status bar color when the keyboard is showing, no other keyboard I've used does this. Otherwise I appreciate your work!

**Comment by patrickgold** [comment]
Thanks for your suggestion!

Clarification question: with "status bar" do you mean the bar with the notification icons, clock, etc. (status bar) or the bar with back home and recent (navigation bar)? If it is the former than it either is caused by the app or its a bug, if it is the latter you can set the color of the navigation bar in the theme settings (Settings > Theme > Navigation bar foreground).

**Comment by unresolvedsymbol** [comment]
Yes it is the former. Apparently it's not correctly detecting if it's in the settings activity or the keyboard activity.

**Comment by patrickgold** [comment]
Interesting, this is then definitely a bug. Could you please fill out the following fields and send me a screenshot of the issue, so I can investigate this further? Thanks in advance!

**Environment information**
- FlorisBoard Version: 
- Install Source: 
- Device: 
- Android version, ROM:

**Comment by unresolvedsymbol** [comment]
* FlorisBoard version: 0.2.4
* Package/install source: GitHub releases, pm
* Device: OnePlus 7 Pro
* Android Version/ROM: Android 11, RevengeOS
I was contemplating putting a screenshot in the original post but figured it was self explanitory. Here:

**Comment by unresolvedsymbol** [comment]
Apologies, misclick.

**Comment by patrickgold** [comment]
Above commit fixes the status bar color issue. Will be shipped with 0.2.5 which will release later this evening.
