### ISSUE TITLE
Move CUT next to COPY in copy&paste bar.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#432]
Move it next to
I feel like this would make a lot more sense as we would group the "copying" options in one place and have PASTE clearly separated to that place by the cursor keys.

Of course that results in the arrow keys not being symmetrical, which is annoying.
I still think it becomes more intuitive when grouping the symbols correctly. (especially to users that aren't certain what symbol means copy and which one means paste.

![copynewnew](https://user-images.githubusercontent.com/59611881/109859285-102b2d80-7c5d-11eb-8e78-ec62dc8c26b3.jpeg)

**Comment by patrickgold** [comment]
Oh no, the symmetry of my arrow keys :(

I think we had that discussion already earlier, but I just don't like the above arrangement, it looks so... weird (but kudos for the excellent mockup, which on first look looks like it was rendered by FlorisBoard that way :+1: )

> especially to users that aren't certain what symbol means copy and which one means paste

I know there will always be some people who don't know the symbols but I am also not using just some icons, I am using the default icons which have been established in Android for years if not a decade now and which many other apps also use as cut/copy/paste icons.

I think the best solution to this problem is to just wait for Smartbar customization, then everyone can rearrange the icons how one wants.

**Comment by Glitchy-Tozier** [comment]
> but kudos for the excellent mockup, which on first look looks like it was rendered by FlorisBoard that way 👍

I'm a genius at using Gimp 😎

> I think we had that discussion already earlier, but I just don't like the above arrangement, it looks so... weird

I think i mentioned it once, but I couldn't remember hearing you thoughts.

Should you ever consider changing the default, remember this:
(1. As I previously said, from a functional standpoint this grouping makes sense.)
2. When you implement shift+cursor_movement=selected text, this makes it even more tempting to move the arrow-keys closer to the right thumb.
(as the left thumb is used for shift)

**Comment by patrickgold** [comment]
The upcoming release 0.3.14-beta07 will have a revamped Smartbar, alongside with that the copy button is next to the cut button now. This is how it looks:

![image](https://user-images.githubusercontent.com/19412843/145722348-58022026-f6a7-4456-8fbe-5a4acfbdcf45.png)

Thanks again for your proposal!

**Comment by Glitchy-Tozier** [comment]
Sick! This way the buttons are grouped semantically while satisfying your (understandable) wish for symmetry. 

What does that rubbish-bin-button do and where did you move the "switch smart-bar-button"?


Btw, I'm not a fan of the clipboard-manager button...It looks to similar to the normal paste-button. Are there any alternatives? (The "Pending Action"-icon looks decent to me)

**Comment by patrickgold** [comment]
> What does that rubbish-bin-button do and where did you move the "switch smart-bar-button"?

Clearing the current primary clip (the item what would be pasted if you press paste). I added this because it allows you to quickly clear the primary clip in case you have some sensitive data copied and want to get rid of it immediately after pasting it.

> Btw, I'm not a fan of the clipboard-manager button...It looks too similar to the normal paste-button. Are there any alternatives? (The "Pending Action"-icon looks decent to me)

The pending actions icon looks cool, but I do not see how it solves the current's icon problems: The current is basically the paste icon with lines in it, the pending actions is the paste icon with a timer.

I could use my current icon but fill it for more contrast (but I am not so much a fan of filled icons): https://fonts.google.com/icons?selected=Material%20Icons%3Aassignment%3A
On the other hand the current icon would be consistent with what both Gboard and SwiftKey use for the clipboard manager, which would be better for newcomers. Tbh, I dunno what to do really with the cion rn

**Comment by patrickgold** [comment]
> where did you move the "switch smart-bar-button"?

Forgot to mention the clipboard cursor row is now an expandable bar, this is how the full Smartbar looks (the empty space is where clipboard/word suggestions would be shown):

![image](https://user-images.githubusercontent.com/19412843/145723075-57f46b89-9f86-4455-9640-9e5ee97dbb3d.png)

**Comment by Glitchy-Tozier** [comment]
I finally got the update!
It's fun being able to resize Apps with this new expansion-feature.
What was the thought-process behind this design? On fist glance, it seems somewhat complicated, being able to get different smart-bars using different methods.

**Comment by Glitchy-Tozier** [comment]
I'm curious how you plan to do this for future iterations of the smart-bar. For example, I can't see fitting the copy&paste-bar into the spot where it used to be (next to the TWO expand-buttons).

Btw, just to make sure you know about it: Currently, pressing a letter always resets the bottom smart-bar, turning this

into this

**Comment by patrickgold** [comment]
> I'm curious how you plan to do this for future iterations of the smart-bar.

That's a valid question I currently do not have an answer for.

> Btw, just to make sure you know about it: Currently, pressing a letter always resets the bottom smart-bar,

That's intended, because the quick actions automatically expand if you start typing but FlorisBoard cannot provide suggestions. If you dislike this behavior you can also disable it in the prefs (Smartbar > Action row > Auto expand)
