### ISSUE TITLE
Add "€" in Symbol Popup "e"

### ISSUE THREAD

**Issue by Loico84** [florisboard/florisboard#434]
I'm italian ed I use the QWERTY layout, so I often use the 
"€", but it'is very tedius to insert, because it isn't in "e" popup symbol. Can you add "€" in "e" popup symbol?

I think that it is a useful feture for all European people.

**Comment by lawson85** [comment]
Be better if we could customise which key goes where on long press so that the developers don't have these issues all over Github asking for random keys

**Comment by Glitchy-Tozier** [comment]
@lawson85 That a very common thing though. Especially in ISO-keyboards (German for example), where `Alt Gr` + `e` = `€`.
I wouldn't add it to every language though.

Let's see what @patrickgold thinks though.

**Comment by lawson85** [comment]
I think I was misunderstand. I used to be able to long press g key on Multiling keyboard however, I cannot on FlorisBoard. I want to customise the key long press.

**Comment by patrickgold** [comment]
> I'm italian ed I use the QWERTY layout, so I often use the
"€", but it'is very tedius to insert, because it isn't in "e" popup symbol. Can you add "€" in "e" popup symbol?

By default I don't think it fits here, as on soft keyboards there's a clear distinction between characters and their accents and symbols.

> I think that it is a useful feture for all European people.

Only 19 countries in Europe use Euro as their currency, which isn't even half of all European countries. Also, the QWERTY layout for instance is used in America too, where the Euro symbol is completely irrelevant. Thus I don't want to add it to the "e" popup by default.

With layout customization, once I implement it, you can add symbols were you want, so then it shouldn't be an issue.
