### ISSUE TITLE
Official Play Store release version?

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#442]
I know it was mentioned before, but I can't find the conversation anymore.

What version do you plan on releasing Florisboard publicly on the Play Store on?

**Comment by patrickgold** [comment]
Public beta on GPlay will happen with the v0.4.0 release (or maybe a few days delayed, depending on the time it takes that the new release track in the GPlay Console is ready for publishing). I expect this to happen beginning April (if everything goes according to plan) but would not be surprised if v0.4.0 sees its light only in mid-April because of unexpected issues.

**Comment by Glitchy-Tozier** [comment]
Got it, thank you!
