### ISSUE TITLE
How to help with suggestions in Spanish?

### ISSUE THREAD

**Issue by Atreyu-94** [florisboard/florisboard#453]
Hey! This is a wonderful project. Gboard has been consuming me a lot of space for a long time.

I am not a developer. But I could help with the suggestions in Spanish if you explain me how or where to document myself. Greetings!

**Comment by patrickgold** [comment]
Thanks for considering to contribute to FlorisBoard! I am unsure if you can help here, because most of the current big problems with suggestions are within the code and data structure. When suggestions phase 2 comes out, you can try out Spanish though and give me feedback on it, if it works well for your language.
