### ISSUE TITLE
Android 4.X support

### ISSUE THREAD

**Issue by Atreyu-94** [florisboard/florisboard#470]
Any chance to add support for Android 4.X?

**Comment by patrickgold** [comment]
Nope sry, FlorisBoard has been built around and tested for only for Android versions 6.0 and newer. There has been quite some changes for the IME API between 4.X and 6.0 which would require me to add all sorts of compat checking and different code for different versions, which when looking at the distribution chart is not worth it. According to the last distribution numbers of April 2020, I target about ~85% of all devices, this number is probably even higher since Android 11 has been released and rolled out.
