### ISSUE TITLE
 FlorisBoard Scrolls Back Up in Settings When You Switch to Another App

### ISSUE THREAD

**Issue by jetrosut** [florisboard/florisboard#477]
#### Short description
When you want to further customize the keyboard theme, you want to switch to another app to see how it looks. Though, any time you leave FlorisBoard settings, you go back to the top setting in the menu no matter where you were last time. [See it in action.](https://i.imgur.com/c2cbQg6.mp4)

#### Steps to reproduce
1. Open FlorisBoard.
2. Go to themes.
3. Edit a theme.
4. Scroll down.
5. Hit the menu button, you can switch to another app if you want.
6. Go back to FlorisBoard, you will be at the top where it asks you to enter a name for the theme you are creating.

#### Environment information
- FlorisBoard Version: 0.3.7
- Install Source: F-Droid
- Device: A Samsung Galaxy Note
- Android version, ROM: Android 7, Stock

**Comment by patrickgold** [comment]
This bug is known in v0.3.7 but has been fixed with v0.3.9 (PR: #455). The F-Droid version was stuck since mid-February due to a bug, thus you still have v0.3.7 which contains a lot of annoying bugs which have been fixed in v0.3.9. You should receive an update to the newest stable release next week.
