### ISSUE TITLE
Enable keyboard at startup (Direct boot mode)

### ISSUE THREAD

**Issue by ghost** [florisboard/florisboard#485]
If a password is set on the system, it's impossible to type the password with florisboard since the keyboard doesn't start at boot.
It would be nice to make florisboard start at boot.
Simple keyboard has this feature and ccording to this issue https://github.com/rkkr/simple-keyboard/issues/85 the keyboard needs to support Direct Boot Mode.

**Comment by GithbUser** [comment]
I m just a user of florisboard but i think for this to work i think you will have to make florisboard system app 
Because third party apps are not allowed to start until device is unlocked 
![Screenshot_20210322-191154](https://user-images.githubusercontent.com/75420364/111999341-e1f58b00-8b42-11eb-825c-8dba9015da5d.png)

Suggestion-Better use pin instead of password

**Comment by Netscaping** [comment]
I know that the pop-up says that, but simple keyboard starts at startup (whit device locked) even when not set as system app which is why I opened the issue.

**Comment by patrickgold** [comment]
Thanks for the suggestion! I can definitely play around with this and look at the implementation of Simple Keyboard, maybe I am able to get it running for FlorisBoard.

**Comment by GithbUser** [comment]
@Netscaping i wasnt aware of having this feature in simple keyboard 
Thanks for correcting me

**Comment by thestinger** [comment]
AOSP keyboard implements this so that's another place to look. You need to make the necessary activities have direct boot enabled and make them work without having access to most of the app data. You can store certain non-sensitive app data as device encrypted such as a subset of configuration to make it available before unlocking. I strongly recommend keeping that to a minimum though. An initial implementation could simply not have any of that data and then over time you can decide which specific bits of configuration, etc. are okay to not have protected by the user's credentials.
