### ISSUE TITLE
Non-default pop-up get chosen automatically in landscape mode

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#505]
#### Steps to reproduce
1. Go into landscape mode
2. Choose a key that has a lot of popups (i used u on QWERTZ)
3. Long-press the key but **target the side of the key** (see screenshot, pink is where to press)
4. See error: The focus automatically shifts to a popup that is towards the left or right.

![Screenshot_20210326-203304_WhatsApp.jpg](https://user-images.githubusercontent.com/59611881/112684261-0b7c2280-8e73-11eb-9914-32d5ece16409.jpg)

#### Environment information
- FlorisBoard Version: 0.3.9
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by Glitchy-Tozier** [comment]
This basically makes fast typing really annoying in landscape mode as the keys act as if they were still small when using pop-ups.

**Comment by patrickgold** [comment]
Technically speaking the correct key is selected, because the pink marked pointer is directly under the `7` and the calculation algorithm thus chooses that key. The only solution to this problem would be to make the width of a popup key the same as a landscape key, but personally I don't like the look of it. On the other hand, syncing the widths would also solve #417, so I will think about it.

**Comment by Glitchy-Tozier** [comment]
Personally, if I long-press a key and get the pop-up **without moving my finger in any way**, i would expect the default pop-up to be input.
Otherwise the width of the horizontal keys feels deceptive.
