### ISSUE TITLE
Larger keys

### ISSUE THREAD

**Issue by 2137mail** [florisboard/florisboard#509]
Larger keys would be nice. Limit too small at the mo. Would be great to ne able to select among a few sizes

**Comment by patrickgold** [comment]
What exactly do you mean by larger keys? The keyboard height maximum is currently 150% if you use the custom height setting and this takes away already a large portion of the screen.

**Comment by 2137mail** [comment]
Larger not higher. Example, the caps lock and the back keys could be narrower. If i didn't have the é, à, è that would lrave space in the first 2 rows to have larger keys.


27 mars 2021, 13:25 de ***@***.***:

**Comment by patrickgold** [comment]
The backspace and caps lock key are adjusting a bit for rows which have to many keys. If you think these keys are to narrow then you can switch to another layout (but leave the language the same).

**Comment by khlsvr** [comment]
Make this keyboard exceed all other keyboards in superiority and add some intuitive layouts where the long-press of keys will be used to type the least used keys in the language the layout is for. 

For example in english the letters Q, X, Z and J occur less than 1% of the characters typed, so they could easily be behind a long-press. https://www.sttmedia.com/characterfrequency-english On the other hand this would break the general "qwerty", "dvorak" etc layouts and you would need to learn a new layout, but you would have larger keys. This would be a type of hybrid with the messagease keyboard and a regular keyboard. The best would be to have a way to configure keys, popups and the layout yourself.

**Comment by tsiflimagas** [comment]
I think this issue isn't certain and consistent enough, and same goes for the ideas mentioned. Afaik, there have been/are people or teams working specifically on optimization of layouts. Some typing optimized layouts have already been added, and more of them are welcome from contributors. That said, working on creating an optimized layout, is a different field from developing a keyboard app, as far as I can see. Since specific issues for customizability of the layout exist, I think we can close this one.
