### ISSUE TITLE
Correct line-thickness for emoji view buttons

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#522]
I think the Emoji-View might look less like a completely different app if the buttons on the bottom were actual buttons.

At least `ABC` and the delete button should follow the keyboard's design by being buttons.

![Screenshot_20210328-205656_KISS launcher.jpg](https://user-images.githubusercontent.com/59611881/112764298-28962a00-9008-11eb-9d8e-d8807fcf634e.jpg)

#### Environment information
- FlorisBoard Version: 0.3.9
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by Glitchy-Tozier** [comment]
This _might_ be able to solve the design issue where 
- `ABC`
- The delete-Key
- and the other two text buttons

all have a different line thickness.

**Comment by patrickgold** [comment]
I don't necessarily think that they need their key border around them, as the clipboard manager for instance also does use this transparent style for the `clear all` command. Additionally the tabs for the categories are also transparent, which matches the background-less buttons better.

**Comment by Glitchy-Tozier** [comment]
> This _might_ be able to solve the design issue where 
> - `ABC`
> - The delete-Key
> - and the other two text buttons
> 
> all have a different line thickness.

No matter what you settle on, i think this should be corrected. ↑

**Comment by patrickgold** [comment]
> No matter what you settle on, i think this should be corrected. ↑

The problem is that the ABC button and the other two text tabs are rendered as a font, while the emoji symbol and the delete icon are icons from the material icon library, thus thy have different thickness. I probably should make an icon out of the text labels, so I can always ensure the same thickness.

> In this case the needs-more-info-badge doesn't mean you need more info from me, right?

This was more of an helper label for this issue so I see that I've already initially handled it. I don't need any additional info from you on this one, except you want to add something :) I will rename this issue to "Correct line-thickness for emoji view buttons", because that's essentially what this issue is about.

**Comment by Glitchy-Tozier** [comment]
Sounds great!
