### ISSUE TITLE
Gestures sometimes don't activate

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#549]
#### Steps to reproduce
1. Set gestures to cursor-movement or go-to-end-of-line
2. Open keyboard. If there's no text, type a few words
3. Click somewhere else in the text
4. Try out the gestures to move around in the text
5. If they all work consistently, repeat the process, starting at nr. 3.

#### Environment information
- FlorisBoard Version: 0.3.9
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by patrickgold** [comment]
I see what you mean. Not a bug per se technically speaking (the minimum distance threshold requirement is not met by a few pixels), but for the user it seems that something is not working. As I've recently discovered the Android in-built `VelocityTracker`, I can finally rely on the velocity threshold as well when I add it to the SwipeGesture, which should improve things in this regard. Will add this to the todo list.

**Comment by Glitchy-Tozier** [comment]
Does that threshold ... somehow increase? I made sure to use large movements to rule out the option of accidentally performing movements that are too small.

**Comment by patrickgold** [comment]
A gesture movement of "large" means that you must perform a long swipe at min to execute the swipe, basically amplifying this issue. Setting it to short would decrease the likelihood of this issue, though you may execute gestures accidentally then (because the distance is too short). Like I said, this issue can't go away unless coupled with a VelocityTracker (because then both requirements have to be met, so I can set the distance threshold basis to something lower while still avoiding some accidental gesture activations).

**Comment by pierstitus** [comment]
I'm having issues with gesture activation too:

1. The space bar swipe up gesture often isn't activated, especially when glide typing is activated. As soon as the swipe enters the letter key area the letter where the swipe stops is inserted instead. Making an up swipe without leaving the space bar is difficult.
2. Cursor movement on the space bar left/right swipe doesn't always work. For example in Simple Notes: it sometimes doesn't work in one note, while it works in another. Switching back to the first note it doesn't work anymore. This seems to happen sometimes after pasting some text. Very strange.
