### ISSUE TITLE
Add IPA keyboard

### ISSUE THREAD

**Issue by Huy-Ngo** [florisboard/florisboard#558]
[International Phonetic Alphabet](https://en.wikipedia.org/wiki/International_Phonetic_Alphabet) (IPA) is a way to represent sounds in languages. As I am often in linguistic discussions, I find it helpful to have a keyboard for it.

I suggest not following Gboard's example, whose layout spreads over four pages with all vowels on the second page and thus unpleasant to use. I have two suggestions for implementation:

- Use QWERTY layout, make the input based on [X-SAMPA](https://en.wikipedia.org/wiki/X-SAMPA) (sorry I don't have a visual for it)
  - the default key is like normal QWERTY
  - after pressing Shift, each key returns the equivalent IPA symbols encoded by X-SAMPA
    - e.g. `Shift` + `s` → x/S/ → ʃ
  - All keys' variants can be accessed by holding the key (e.g. hold s --> show x/S/ ʃ, x/s\/ ɕ, x/s`/ ʂ)
  - Symbols encoded by non-alphanumeric characters in X-SAMPA (which usually don't represent consonants nor vowels) are in the special character input.
- Use X11 keyboard layout, like in the below picture. In each key:
  - the bottom left is the default key
  - the top left is the key after pressing Shift
  - the other keys can be accessed by holding the key
  - characters that don't look like a letter (which usually don't represent consonants nor vowels) can be put in the special character input.

![X11 layout](https://user-images.githubusercontent.com/19296926/113422183-78089b80-93f6-11eb-9145-28bbc030ddb3.png)

**Comment by patrickgold** [comment]
Thanks for your issue! This layout indeed seems very interesting, though I have to admit that I've never seen it before and thus I don't know what the correct way of implementing would be. I have also seen that you started working on this already, so I will let you work on this and review it once you feel like it is finished. Should you have any questions or need help with something in the code, feel free to ask :)

**Comment by Huy-Ngo** [comment]
I have two questions:

- Since IPA is language-independent, which code should I use for it?
- How do I change the symbol keyboard? I saw two folder `symbols/` and `symbols2/`, both have `western_default.json`, which I assume are for the two pages of special characters. How do I add the layouts for IPA keyboards?

**Comment by patrickgold** [comment]
> Since IPA is language-independent, which code should I use for it?

`zz` seems to be a popular code for language independent locales, so I'd go for it.

> How do I change the symbol keyboard? I saw two folder symbols/ and symbols2/, both have western_default.json, which I assume are for the two pages of special characters. How do I add the layouts for IPA keyboards?

For this you must merge in master into your development branch to get the latest features, which includes the ability to add custom symbol layouts. Once merged in and any merge conflicts resolved, you can add new symbol layouts just like the default western/eastern ones in their respective folder and they will automatically appear in the settings subtype UI. Note, that layout labels are not stored in the IME config anymore, rather than in the layout itself, as `"label": "Your Custom Label"` below `"name"`. To add them as the preferred symbols layout for the IPA subtype, add them to the `preferred` object of your subtype, like done here with Persian: https://github.com/florisboard/florisboard/blob/62eb97cd16c2cd348f8de479797ebb7796124de4/app/src/main/assets/ime/config.json#L438-L448

**Comment by Huy-Ngo** [comment]
Thanks. I'll look into it now.

**Comment by writeblankspace** [comment]
This keyboard doesn't seem to have eth (ð) in it. Can it be added?
