### ISSUE TITLE
Multi-touch & swipe-typing

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#583]
@X-yl Hey, just a quick question:

How exactly do you handle multi-touch in your implementation of gesture-typing?

You said you now disabled it while swiping, but what if the user *first* presses&holds a button and then starts swiping with the other hand? (and then releases the button)

**Comment by X-yl** [comment]
Uh well I don't handle multi-touch at all lol. It just locks on to the first pointer to touch the screen and then ignores all other touch events. So nothing should happen, really. Even after the first pointer is lifted, it won't react to the second one because it only locks on when a pointer first touches the screen.

**Comment by Glitchy-Tozier** [comment]
Okay, I'm not sure what that means in every possible situation but i'll thourougly test gesture-typing once it's released!  ;)
