### ISSUE TITLE
Cancel Word-Deletion Behaviour

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#595]
@X-yl Adding you because you seem to be the expert in regards to Swipe-typing

You have added a very smart thing: If the user presses `delete`, after swiping, the whole word will be deleted.

HOWEVER this behavior isn't cancelled when the user starts typing normally. This means that this...
1. Swipe
2. type multiple word
3. try to delete a character
4. accidenntally delete the whole last word

...is a common occurrance.

In my opinion, this is a very important fix.

#### Environment information
- FlorisBoard Version: 0.3.10
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android version, ROM: 10

**Comment by Glitchy-Tozier** [comment]
Edit: This only happens with suggestions turned off.

Is there a way to just use the same codebase for suggestions enable&disabled?

**Comment by X-yl** [comment]
Yes, you're right, this as well as #581 are both caused by my stupid hacky workaround which breaks when suggestions are not enabled. 

The issue is that I'm kinda working around the suggestion code which causes the suggestions to be refreshed whenever the cursor is updated, however inserting the glide text causes the cursor to be updated but the glide suggestions still need to show. As a result of that I did some hacky state storing stuff that breaks when suggestions aren't enabled.

I'll try to fix soon
