### ISSUE TITLE
Add symbol-properties for automatic spaces to improve gesture typing

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#596]
Problem: When typing `.` and then swiping a word, a space should appear between them. After typing `(` no space should appear.

I can't think of a smart solution to the problem though, except for saving the proper behavior for every symbol.

**Comment by X-yl** [comment]
It's definitely a tricky one. Do you know of any dataset with this kind of thing? Like it's all well and good when disabling spaces for the easy ones like `'` `"` `(` `[` , and maybe even the trickier ones like `#`. But then we get into scary unicode land where both `“` and `«` exist and need to be treated differently.

**Comment by Glitchy-Tozier** [comment]
Yeah, i can see how this would be difficult to decide and a lot of work if tackled manually.  :/

Unfortuantaley i'm not aware of any helpul datasets...

**Comment by xander-page** [comment]
I've been thinking, and it might be easier to just _never_ automatically insert the space except between actual words. Even if you did make a list of which punctuation needed it and which didn't, there would still be edge cases:

* Space after asterisks? The user might want them if the asterisk is being used to make a bullet list, but might not want them if they're being used to emphasize or correct a word.
* What about full stops, pretty simple, right? Sure, except in URLs. And domains don't always look like _www.example.com_ anymore. Even if the dictionary kept track of the ever-growing list of top-level domains, how would it handle this?:

``` Welcome to example.horse. Horse puns are among the many things you'll find here...```

Just as an example.

It would take some getting used to to hit space after every full stop and comma, but that's still less of a hassle than repositioning the cursor and _removing_ one after every quotation mark, bracket, and hyphen.

**Comment by Glitchy-Tozier** [comment]
> Space after asterisks? The user might want them if the asterisk is being used to make a bullet list, but might not want them if they're being used to emphasize or correct a word.

I agree with this. Some symbols are used in many different scenarios, and defining behaviors for each of them is not possible.

> What about full stops, pretty simple, right? Sure, except in URLs. And domains don't always look like www.example.com anymore. Even if the dictionary kept track of the ever-growing list of top-level domains, how would it handle this?:

I don't agree with this. Personally, I never use gesture-typing for any kind of URL, because they contain weird words and many symbols in-between.

How about having two categories?
1. Sentence finishers `.?!¿¡ etc.`
2. Everything else

On the other hand, having a universal system sounds appealing as well.
@patrickgold We need you and your usability-genius. Thoughts?

**Comment by X-yl** [comment]
I think the way gboard does it is have it by default not enter a space, and then they made exceptions for things like `.?!:"';)` etc.  It has issues obviously, but I think that's probably the easiest solution. The URL thing should be easy to solve, since the keyboard knows if it's entering into an address bar. Obviously other contextual behaviours aren't really possible but I think that covers most cases.

**Comment by patrickgold** [comment]
So after a long time I finally got around to experiment with a potential solution (above linked commit):

I added the ability to define "punctuation rules". These rules currently allow to define regexes for preceding and following symbols and are subtype bound, which means one can have different punctuation rules for different languages. At the moment though there's only the "default" punctuation rule, automatically applied to all subtypes:

```json
  "punctuationRules": [
    {
      "id": "default",
      "symbolsPrecedingSpace": ".*[.,;:!?‽&%)\\]}»©®™\\p{L}0-9]",
      "symbolsFollowingSpace": "[\\p{L}0-9].*"
    }
  ],
```

This is then used by the phantom space determine function:

```kt
    private fun PhantomSpaceState.determine(text: String, forceActive: Boolean = false): Boolean {
        if (!(isActive || forceActive) || activeState.keyVariation == KeyVariation.URI) return false
        val content = activeContent
        val selection = content.selection
        if (selection.isNotValid || selection.start <= 0) return false
        val textBefore = content.getTextBeforeCursor(2)
        val punctuationRule = nlpManager.getPunctuationRule()
        return punctuationRule.symbolsPrecedingSpace.matches(textBefore) &&
            punctuationRule.symbolsFollowingSpace.matches(text)
    }
```

The reason why I opted for a regex instead of a traditional list is, because some symbols may require additional context (e.g. only enter a space if the character before the symbol is something specific). This means I use the "default to not entering a space except if both rgeexes match" philosophy, which seems to also be Gboard's way of approaching this.

Now the question is how well this works in real-life use. I tested this a lot and it the punctuation rules gets applied fine for the defined symbols, however I am unsure if I missed some symbols or if some languages need extra care.

Atm there's no option in the subtype add/edit UI to change or select these rules, but if this experimental punctuation rule stabilizes I can consider adding a selection dropdown, and we can add more punctuation rules if needed.

For URL fields, the phantom-space is always ignored and never inserted. I don't know though if the users expect this behavior, as both Gboard and SwiftKey respect the phantom-space and insert it even in URL fields. For password fields glide typing is now disabled.

If some of you want to try it out immediately, PR #1844 has a debug artifact build to test this new auto-space / phantom-space behavior out for glide typing. If not then it would be great if you could test this out once beta03 releases, this would be greatly appreciated :)

**Comment by patrickgold** [comment]
After some reconsideration I removed the URL exclusion again, as most URL bars have a dual purpose of acting like a search bar nowadays, and it just makes more sense to have proper auto-spacing here too. Everything else of my above comment is unchanged and still valid.
