### ISSUE TITLE
Clipboard suggestion in numeric keyboard

### ISSUE THREAD

**Issue by D3SOX** [florisboard/florisboard#603]
Sometimes I copy a TOTP and then want to paste it inside the corresponding field. In this case I have to long press -> paste on the input field because FlorisBoard does not suggest pasting in the numeric/phone layout (not sure which one it is)

**Comment by patrickgold** [comment]
Thanks for your suggestion! The numeric/phone layouts purposely don't have suggestions, because normally they aren't relevant in such context. I agree though that for TOTP codes it would be very useful to have some sort of copying/pasting the code. Would it be sufficient for you if I gave those layouts access to the clipboard cursor row instead of showing the paste suggestion? This is way easier to accomplish and you can copy, paste and move the arrow keys when having the numeric field.

**Comment by D3SOX** [comment]
> Would it be sufficient for you if I gave those layouts access to the clipboard cursor row instead of showing the paste suggestion? This is way easier to accomplish and you can copy, paste and move the arrow keys when having the numeric field.

Yes, I think that's a good idea

**Comment by patrickgold** [comment]
Above PR adds the clipboard/cursor row to the numeric/phone layouts, will be available in the next beta release v0.3.11-beta01
