### ISSUE TITLE
Implement a common manager for composing input methods

### ISSUE THREAD

**Issue by Huy-Ngo** [florisboard/florisboard#607]
Many input methods requires multiple inputs to compose a character, for example, Telex for Vietnamese (#183), Indic scripts (#368) or Korean (#305). Therefore, it could be helpful to have a common manager for them that reads from a config file. Each row in the config file represent a transformation rule, with the LHS being the sequence of keys pressed and the RHS is the output character.

For example, config for Telex can look like:

```json
{
  "_depth": 2,
  "aa": "â",
  "as": "á",
  "âs": "ấ",
  "..."
}
```

I suppose we can use [getTextBeforeCursor][get] and [setComposingText][set] to implement this. Here is a pseudocode of how I think I would implement it:

```kotlin
fun onKeyPressed(pressedKey: Char, config: Json) {
    depth = config["_depth"]
    pattern = getTextBeforeCursor(depth - 1) + pressedKey
    if pattern is a key in config {
        replacedText = composingText.replace(pattern, config[pattern])
        setComposingText(replacedText)
    }
}
```

[get]: https://developer.android.com/reference/android/view/inputmethod/InputConnection#getTextBeforeCursor(int,%20int)
[set]: https://developer.android.com/reference/android/view/inputmethod/InputConnection#setComposingText(java.lang.CharSequence,%20int)

**Comment by Huy-Ngo** [comment]
Note regarding Telex (#183): this implementation wouldn't allow for the free order like a [standard implementation][unikey] would.
For example, inputting `ans` would give `ans` instead of `án`, which may hinders your typing if you have a habit of adding tone after finishing words. The implementation of [unikey ibus table][ibus] and [vim keymap][vim] also suffer this problem, though I think it's not a big deal and worth it if it's make things easier for the maintainer(s).

[unikey]: https://sourceforge.net/projects/unikey/files/x-unikey/1.0.4/
[ibus]: https://github.com/McSinyx/ibus-table-vietnamese#ph%C6%B0%C6%A1ng-th%E1%BB%A9c-g%C3%B5
[vim]: https://github.com/vim/vim/blob/master/runtime/keymap/vietnamese-telex_utf-8.vim

**Comment by patrickgold** [comment]
Thanks for your suggestion! Yes, a common manager for languages which require special input handling will have to be implemented sooner or later. I get the basic idea of your pseudo code and this way it is the least complicated. These special input methods are planned for the v0.5.0 milestone (currently I am focusing on bug fixing and adding a proper suggestions code). I will keep this suggestion in mind and see where we go from here.

> For example, inputting ans would give ans instead of án

Even though it is more complicated, it is still possible to achieve the correct input, right? If so, I would invest the extra effort to make these special input layouts feel more completed.

**Comment by Hayleia** [comment]
Teaser...
![korean_test](https://user-images.githubusercontent.com/7904776/116659650-32f26d80-a992-11eb-8ba4-21f3d588b435.gif)

More seriously, I was just experimenting stuff and plugged my code at the wrong place (that's probably why sometimes the input is ignored, and why glide typing does absolutely nothing) but at the easiest place in order to avoid doing changes everywhere just for testing purposes.
My changes can be seen [here](https://github.com/Hayleia/florisboard/commit/b69b1caa72d25e178b79d9f9ff2d157b445a8dea) (once again, for testing purposes, I know it's bad, especially the part in EditorInstance.kt, this is not meant to be merged anywhere).

I know there is that ["talk to devs before working on a change"](https://github.com/florisboard/florisboard/blob/master/CONTRIBUTING.md#adding-a-new-feature-or-making-large-changes) part in the guidelines. That's all on me, I know it, but this is my first time in Kotlin so I didn't really want to start wasting people's time only to fail hard later.
Now that I didn't fail too hard (not saying my code is perfect at all), I'm ok with not going any further before discussion.

Where should the base "don't necessarily concatenate text but maybe edit what's already written" code actually be plugged? Right now I put it in commitText in EditorInstance.kt but I'm definitely sure it's not the right place.

Also you can see I used reflection for what seems to be zero reason when I could just have instanciated my composer with `val composer = ComposerHangul()` (and it would still be a bad idea to instanciate it everytime the code goes through here but still for testing purposes). But I was thinking that reflection could be the most modular way to get a common manager for composing input methods. We could have an abstract Composer class and then we could specify in layouts' specific json files that:
- Telex would use the Composer implementation that uses rules in a json (and rules would be specified in the layout json).
- English does not need any specific composition so it would use a default Composer implementation that just concatenates (note that it can actually be the implementation that uses rules except there are no rules).
A lot of layouts would fall in that category I guess (including all the ones already supported).
- Korean would use a specific Composer implementation which we name precisely in the json ("dev.patrickgold.florisboard.ime.core.ComposerHangul" right now in my branch but I didn't think a long time before choosing the package), and then the keyboard gets the correct class with reflection. This way, Korean would not use the default manager along with 30000 rules, it would rather use a specific algorithm optimized for Korean and more efficient.
Not too many layouts would fall in that category I hope.

The interesting method in the abstract class would be `getActions` (not a definitive name) in my current ComposerHangul class, which retuns the number of characters to delete and the string to insert.

Of course I'd think twice about using reflection if there was an alternative, but it seems fine here.
- Creates problems that can't be detected at compile time? 
  * there are already jsons with keys and values subject to typos or missing keys/values, so either this is not a problem or this is not a new one.
  * all the Composer classes would be subclasses of an abstract class. Reflection would only be used to get the correct class from a string value in a json and then instanciate an object from that, then from that point there is no longer any reflection into play, only calls to methods defined in the abstract class. So the relevant composing methods cannot have the wrong signature in the actually instanciated class unless it doesn't exist or it does not extend the abstract class, but this kinda falls in the typo problem mentioned above.
- Modularity? well this is at least as modular as the previous suggestion with rules since it includes it.
  * layouts that don't need specific composing can still be described with json only.
  * layouts that need specific composing BUT can be described as rules can still be described with json only (specifying rules and the rules composing manager).
  * layouts that can't reasonably be described with json only will have specific classes instead of being described in json files only, yes. But that could bring efficiency as a trade-off and that would not come in the way of other layouts' code (I mean, there wouldn't be a place in the code with a per-layout `when` statement).

  So yeah, sorry for being the one to bring the R-word here but I see "everything has their best solution" as a successful modularity and I don't see a drawback in this case.

**Comment by patrickgold** [comment]
@Hayleia Sorry for my late response, there's currently a lot of stuff going on and I can't respond to everything immediately. That being said, really cool work you've done here! I've had a quick look on your code and luckily it doesn't intersect with the layout rework (#734).

Now to your questions:

> is commitText the right place or is it somewhere else?

Yes and no. There's currently no "right place" to do such replacement, but commitText is the best solution currently. So leaving it there is fully acceptable for me.

> is reflection a good idea or not?

In general no. The problem with reflection is performance and it really feels like a hack if used in a production code to me. I've seen you mentioned modularity and loading a different composer based on a JSON value - you can do that with kotlinx's serialization features (available in the master code since v0.3.11.beta02). I even use this kind of modularity to load a different key data class (BasicTextKeyData, CaseSelector, VariantSelector, AutoTextKey etc.) without using reflection, and the serializer automatically determines which class must be used based on the `"$": "<class identifier>"` value in JSON.

> We could have an abstract Composer class and then we could specify in layouts' specific json files that

That's an idea I really like. The new layout logic also has an abstract base class for Key, Keyboard, KeyboardView, KeyData etc. which allows to work with these objects without knowing exactly what it is. Like I said above, with kotinx.serialization you can load a different composer (and even a default composer in case the composer attribute is missing or some. invalid value).

If you want, you can further work on this feature, I'd be really happy. If you do so, please make sure to rebase your changes on the latest master commit though so you can make use of the serialization features I mentioned. If you have further questions or need help, feel free to ask in this thread!

**Comment by Hayleia** [comment]
No worries for the delay, I saw the work that was done in the commits and also people have lives. Thanks for your work and your answer.

Yes I agree that reflection is disgusting most of the time (at least in Java, maybe all the time in Kotlin). It was my first time doing any Kotlin this week so heh, didn't know about kotlinx's serialization features or I would have suggested that instead. I'll have a look into this. Btw it seems like the work you did with it on layouts and the different TextKeyData will also be useful for keys where the "shift" character is not the uppercase "non-shift" character (as mentioned in #305 but that's probably not the only case).

So do I want to further work on this? Yes, but as I said it was my first time doing Kotlin and seeing florisboard's codebase and I'm obviously still learning, and also I was in vacations this week but that's over so my progress is going to be slow. What I mean is, yes I'll work on this but if you get rid of all of your tasks elsewhere and I'm still struggling here, don't feel obligated to wait for me just because I somehow assigned myself to this.

**Comment by Hayleia** [comment]
Well I got that specific-uppercase thing working, that's one thing.

For the rest though, I have a plan in mind and I don't know if it's the right plan (and I'd rather ask before I change all the layers of config code).
I'm thinking of adding a composerName property to the Subtype class, which would of course reference a json that could be instanciated into a Composer through kotlinx's serialization. Which means that this could be selected in a dropdown in the "add subtype" dialog, etc (so not necessarily a lot of changes in terms of number of lines of code, but an important change nonetheless).

Why there and not in other json files (such as layout json files)? Because here, it allows a French person occasionally typing Japanese to choose french_language+azerty_layout+euro+default_composer as main subtype, and japanese language+azerty_layout+yen+latin2hiragana_composer or something. This doesn't make a lot of sense for all layout/composer combinations (for example any latin layout with the korean composer would just waste performance) but it makes sense for some of them and I think this keyboard tries to please everyone (hence the subtype configuration dialog in the first place).

Does that sound like a good plan?

**Comment by patrickgold** [comment]
> I'm thinking of adding a composerName property to the Subtype class, which would of course reference a json that could be instanciated into a Composer through kotlinx's serialization.

In general I like this approach, it makes the most sense this way. Be aware though that modifying the structure of subtypes is dangerous and can lead to all sorts of issues when not handled properly. As this change is quite important though, I will assist you in avoiding the most common issues I experienced when I reworked the subtype implementation once in the past.

First, the `composerName` property:
This is a good name for the property, I like it. In JSON this should be named `composer` only though, so the same way I did it with the currency set name. As for the order, I would add it directly after the `languageTag` tag, here it makes most sense. I am unsure if it is better to make this property optional or required in the JSON file though, what is your opinion?

The subtypes have a serialized string representation, one for storing it in the preferences and one for debug: https://github.com/florisboard/florisboard/blob/5a5089c413dd6f4b1387556a83e903b2a4452a39/app/src/main/java/dev/patrickgold/florisboard/ime/core/Subtype.kt#L94-L110

Here, the new output format should also contain the composer on the third place: `<id>/<language_tag>/<composer_name>/<currency_set_name>/<layout_map> `.

Next up, the [SubtypeManager](https://github.com/florisboard/florisboard/blob/master/app/src/main/java/dev/patrickgold/florisboard/ime/core/SubtypeManager.kt): all methods need some adaptation, but I think in general it is clear what to change here, same goes for the preference subtype UI.

Next, adding the old value remover to the PrefHelper instance: https://github.com/florisboard/florisboard/blob/5a5089c413dd6f4b1387556a83e903b2a4452a39/app/src/main/java/dev/patrickgold/florisboard/ime/core/PrefHelper.kt#L159-L162

This is especially important because else for other users trying out your debug build and possibly yourself too. FlorisBoard will crash while parsing the old subtype format stored in the prefs. Either adjust the regex or make a new one and add it after the linked lines, just make sure that the mechanism detects both the previous and current subtype syntax.

> Why there and not in other json files (such as layout json files)? Because here, it allows a French person occasionally typing Japanese to choose french_language+azerty_layout+euro+default_composer as main subtype, and japanese language+azerty_layout+yen+latin2hiragana_composer or something.

I like this idea, exactly this approach makes FlorisBoard so modular in regards to some other keyboards, where the subtype variations are pretty limited.

> This doesn't make a lot of sense for all layout/composer combinations (for example any latin layout with the korean composer would just waste performance)

It is the responsibility of the user if his own custom variation makes sense, for us developers it is only important that the default options selected makes sense (to provide a good baseline especially for inexperienced users).

> Does that sound like a good plan?

Yes :) Should you need any assistance, feel free to ask for help in this thread!

**Comment by Hayleia** [comment]
Thanks for the directions. I was trying to modify things in SubType and try to cascade-fix what I break, but it helps to have an overview first.

> I am unsure if it is better to make this property optional or required in the JSON file though, what is your opinion?

I don't know either. If I had to choose, I think I'd make it required because it "complexifies" json files a tiny little bit but it probably makes the code easier (to write and maintain) for not having to deal with missing keys on top of old json versions etc?

**Comment by patrickgold** [comment]
The config.json (where you change the syntax) is not really designed to be compatible between different versions, so from this point it is completely irrelevant. Also, for the default value you would just add one single line in the asset manager's polymorphic definition for the composer, so not complicated at all. As the composer is rather important though and a default hidden composer may be confusing, I suggest we make this property required.

**Comment by Hayleia** [comment]
Teaser n°2...
https://user-images.githubusercontent.com/7904776/117855172-8619c980-b28a-11eb-8af5-d563fbf94c05.mp4

More seriously once again, I got things to work I think?
Note that the hiragana support in the video is incomplete and its only goal was to test the code that uses json rules.

Things that still need work:
- I haven't touched the old regex thing, so there might be crashes for everyone who does not wipe the app's data. But you said where that was so I'm guessing I can fix that.
- I probably forgot to update documentation comments at some places easy fix too.
- You said the composer should be right after the language tag. I did that in JSON but I didn't do it in the add/edit subtype dialog. This wasn't on purpose, I just copy-pasted the currency set dropdown and didn't move anything. Should I put the composer dropdown right after the language dropdown (or elsewhere)?
- There is [this line](https://github.com/Hayleia/florisboard/blob/df393ff607961d91d10f0b24eda8b9541ea3f661/app/src/main/java/dev/patrickgold/florisboard/ime/core/EditorInstance.kt#L189) in commitText which calls [that thing](https://github.com/Hayleia/florisboard/blob/df393ff607961d91d10f0b24eda8b9541ea3f661/app/src/main/java/dev/patrickgold/florisboard/ime/core/FlorisBoard.kt#L130) every time a character is typed, which might be a bad idea for performance. But I didn't really know which object instances where renewed when switching layouts so I didn't know where to save the composer value.
- Two "identical" subtypes can't coexist but the "identical" part might need to be a little more permissive. For example people writing in japanese might want two identical layouts except one of them writes hiragana and the other one katakana? And in that case, there would be a need to display somewhere the difference between the two layouts? I have no idea.

**Comment by patrickgold** [comment]
Impressive work, really liking the direction this is going!

> I probably forgot to update documentation comments at some places easy fix too.

That's something what happens to me too, but in most cases this is something I fix after the core changes are in. Doc strings are important for other contributors to better understand what the code does, so it should be updated if possible.

> You said the composer should be right after the language tag. I did that in JSON but I didn't do it in the add/edit subtype dialog. This wasn't on purpose, I just copy-pasted the currency set dropdown and didn't move anything. Should I put the composer dropdown right after the language dropdown (or elsewhere)?

Yes it is best if the composer selection is right below the language dropdown in the Settings Dialog UI, like also in the JSON syntax.

> There is this line in commitText which calls that thing every time a character is typed, which might be a bad idea for performance. But I didn't really know which object instances where renewed when switching layouts so I didn't know where to save the composer value.

This indeed looks a bit weird. For now let's leave it in there, when your code base is fully ready we will see if we can improve on that specific line.

> Two "identical" subtypes can't coexist but the "identical" part might need to be a little more permissive. 

Subtypes are only identical if
a. the language,
b. all the layouts,
and c. the currency set matches

Meaning the same logic also applies for the composer once added to the subtype specification: one could have the same config for language/curr.set/layouts and as long as there are two different composers selected this shouldn't cause any trouble. The list item summary string in the subtype list UI might need a rework to better reflect what each subtype represents, else it is of course a bit difficult to see the difference between the two.

Suggestions for this summary string:

- `<character layout name> | <composer name> | <currency set name>`
- `<character layout name> | <composer name>`
- `<character layout name> | <currency set name>`

What exactly fits best is a bit trial and error until something best matching has been found.
