### ISSUE TITLE
Issue with space automatically inserted before words when glide typing

### ISSUE THREAD

**Issue by xander-page** [florisboard/florisboard#616]
#### Short description
Type a quotation mark, then glide type a word. There's now a space between the quotation mark and the word, and there shouldn't be.

#### Environment information
- FlorisBoard Version: 0.3.10-beta06
- Install Source: Github
- Device: Samsung Galaxy A20
- Android version, ROM: 10, stock

**Comment by Glitchy-Tozier** [comment]
Related to #596.

**Comment by patrickgold** [comment]
Why shouldn't there be a space after a normal question mark? Don't really understand the issue here. For the upside down question mark no space is entered, so this isn't an issue.

**Comment by xander-page** [comment]
This issue's about quotation marks, not question marks.

**Comment by patrickgold** [comment]
> This issue's about quotation marks, not question marks.

Omg I can't read, in my head I always read "question" instead of "quotation" mark :facepalm:

Yeah the issue with quotation marks is known and actually addressed by PR #1844 with the punctuation rule commit (https://github.com/florisboard/florisboard/commit/977b32de6e89cb9dafd67c6dde4272aefd010ace). This fix means that for single and double quotation marks no spaces are inserted anymore.

As this issue is thus fixed, I will add it to PR #1844, so it will auto-close when I merge it in. This fix will be released in 0.3.16-beta03.
