### ISSUE TITLE
Unclear feature in keyboard mode (arrow right in quick actions)

### ISSUE THREAD

**Issue by rancidfrog** [florisboard/florisboard#63]
In the settings tab the third button is an arrow key(between settings and italics i),

![](https://i.imgur.com/ZDkXnYy.jpg)

Which brings up:
![](https://i.imgur.com/JU3vK7I.jpg)

Clicking the arrow just switches from one side to the other, the fullscreen button exits to normal mode.

What does this do?
Is it unimplemented yet?
Currently I am unable to figure it out

Thank you

**Comment by patrickgold** [comment]
> What does this do?

This is the one-handed mode, which makes the keyboard height less tall and adds the green column on either the right or left side of the keyboard and which should assist you in writing single-handed.

> Is it unimplemented yet?

No, the only thing that is missing is a good icon for it, which is currently an arrow right. At the time I implemented that feature (this existed since before v0.1.0) I didn't find a good looking icon in the material icons library.
