### ISSUE TITLE
Backspace doesn't work with single number inputs

### ISSUE THREAD

**Issue by D3SOX** [florisboard/florisboard#64]
**Environment information**
- FlorisBoard Version: 0.2.6
- Install Source: GitHub
- Device: OnePlus 8T
- Android version, ROM: 10, OxygenOS

**Steps to reproduce**
1. Open an app which uses multiple single number inputs
2. Type some numbers in
3. Try deleting them
4. It only deletes from the currently active input

During the setup of my new phone a noticed this bug in Telegram. I don't know if it's really a bug or just not implemented.
I still have Gapps right now so I can confirm this is not a bug within Telegram.

<details><summary>Screen Recording</summary>
<p>

![untitled](https://user-images.githubusercontent.com/24937357/101085128-4948f880-35af-11eb-9470-8294409b66e9.gif)

</p>
</details>

**Comment by patrickgold** [comment]
Thanks for your report, Nico! I haven't confirmed it yet, but I think the problem is that FlorisBoard uses the methods provided by the current InputConnection to tell the target app to insert text, to delete it, etc. Now these methods only work within the current input field. Telegram has 5 separate fields. Before invoking such a method, FlorisBoard checks the input length, which is correctly 0. I guess that Gboard sends a key event with the key code for delete instead, which Telegram listens to. and deletes the previous input field's content. I will see how I will handle this kind of input fields.
