### ISSUE TITLE
How to add other language support for glide typing

### ISSUE THREAD

**Issue by kk90** [florisboard/florisboard#645]
@X-yl how can I add support for different language in glide typing?
I see that a glide dict is here app/src/main/assets/ime/dict/data.json
How can I generate it for different language? 

Thank You

**Comment by X-yl** [comment]
At the moment that's just temporary because the dictionary code isn't ready yet. @patrickgold will be adding some way to add dictionaries for any language so that it works with both the suggestions and glide typing and doesn't increase the apk size.

If you just want something temporary for personal use, then many languages are available in the [wordfreq](https://github.com/LuminosoInsight/wordfreq) dataset. You can refer [here](https://github.com/florisboard/dictionary-tools/blob/84ee42c70a59464db68f9bb22b3f4663f9153179/clb.py#L29-L52) to see how to parse that file. Use that to create a json file and modify this line here: https://github.com/florisboard/florisboard/blob/3be3be8e9de5a1165f792a5731ebd39c4b387d50/app/src/main/java/dev/patrickgold/florisboard/ime/text/gestures/GlideTypingManager.kt#L80 to load the file you created.

**Comment by Offerel** [comment]
I wanted ask a similar question. Unfortunately I have no idea how to setup a coding environment for Android and I have no idea in general how to create apps on android.

That's why I risk to ask about a small timeline, when we can expect support for languages other than english? A rough timeline will be ok for me.

I'm really impressed about this keyboard as of now, but since I'm a german guy, I tend to use mostly german language and with that, I hope that we can switch easily between english and german in the near future.

**Comment by patrickgold** [comment]
@Offerel So according to my milestone plan the suggestions part is the last big part of the v0.4.0 milestone. Thus, I'd roughly say that some sort of functional solution for dictionaries will be found within the next month. How well the suggestions and dictionaries will work we will see, but after this the suggestions should at least be ready to accept different languages and the gesture/glide typing manager can also better work with this.

**Comment by kk90** [comment]
Thanks for awesome code everything is clear!
