### ISSUE TITLE
Ability to choose emoji platform style

### ISSUE THREAD

**Issue by Victor239** [florisboard/florisboard#660]
There are numerous platforms which do [different styles of emojis](https://emojipedia.org/), it would be great to be support more styles. In particular I'd like to vote for WhatsApp and Emojipedia's versions first.

**Comment by Atreyu-94** [comment]
I think this would be great. The emojis on my system are very ugly and do not have support for skin tones, and there are a lot of emojis missing. Maybe they could be added in the form of plugins :)

**Comment by patrickgold** [comment]
Long time has passed since the original creation of this issue :)

Sadly this proposal is difficult to impossible to implement due to technical limitations (see https://github.com/florisboard/florisboard/issues/1965#issuecomment-1193924487) and because a lot of emoji fonts are proprietary, thus I cannot legally include them in FlorisBoard.

As such I have to reject this proposal, I hope you can understand.
