### ISSUE TITLE
Custom layout editor

### ISSUE THREAD

**Issue by TadaCZE** [florisboard/florisboard#667]
I hereby propose a custom keyboard layout editor. The way I imagine it working like this: In the writing tab, when you add a custom subtype, there would be a checkbox "custom layout". Upon checking the checkbox, all other options would disappear, and you would be able to select for every key on the keyboard a unicode symbol to write. Moreover, for every symbol, you would be able to select the symbols you can write with a long press. If you go the extra mile, you can also make a system to select different key layouts.

If you implement a system like this, you can save yourself the hassle of creating the layouts yourself, instead asking the community to create them for you, by using an import/export system.

**Comment by MTSYuki** [comment]
I agree, I used another keyboard just because of this. Is a interesting idea.

Your proposal is more easy to customize than the other keyboard, they require to edit the XML file and apply the change, but I think you ideia is best for simplicity and ease to use.

**Comment by khlsvr** [comment]
On the readme.md under "other useful features" you can see a tagged feature that says 
` Full integration in IME service list of Android (xml/method) (integration is internal-only, because Android's default subtype implementation not really allows for dynamic language/layout pairs, only compile-time defined ones)`

I'm not sure if the above is related to your suggestion, but if it is, doesn't that indicate that Android's default subtype implementation doesn't allow you to edit the layouts through the settings? 

I'm all in to this feature too, or anything that allows me to bind custom buttons, even if just to the smartbar (my suggestion https://github.com/florisboard/florisboard/issues/698 )

**Comment by patrickgold** [comment]
Thanks for your suggestion! This was already suggested in #196 and will be implemented in v0.5.0. Closing this issue as a duplicate.

> I'm not sure if the above is related to your suggestion, but if it is, doesn't that indicate that Android's default subtype implementation doesn't allow you to edit the layouts through the settings?

The default Android subtype implementation is old, featureless and way too restrictive. System subtypes can only be enabled/disabled and a layout name can only be assigned at compile-time, for custom layouts you'd haven to resort to something like OpenBoard does: overriding the layout for each language in a separate UI. Thus FlorisBoard uses custom Subtypes, which circumvent the problem in its roots. This also allows for me to assign any layout to any subtype, this also works with custom layouts. The complicated thing for the custom layouts is building the Settings UI for it (because the keys can get quite complex + the layout JSON syntax + structure is not yet in a fully finished state).
