### ISSUE TITLE
Width of popup and key should be same in NUMERIC mode

### ISSUE THREAD

**Issue by rathod-sahaab** [florisboard/florisboard#682]
I tried to fix this but I am not familiar with the codebase.

**Comment by rathod-sahaab** [comment]
![Screenshot_2021-04-15-14-26-53-164_com.sts.flutter.jpg](https://user-images.githubusercontent.com/31929374/114844180-27327300-9df8-11eb-86bb-402e2c8254cd.jpg)

**Comment by patrickgold** [comment]
Thanks for your suggestion! This is intentional, because in my opinion it is quite ugly if the popup width is as big as the base key width (I am aware that some keyboards do that, still I don't like it). I don't intend to change the popup width in the numeric and phone/phone2 layouts anytime near in the future, I am sorry.
