### ISSUE TITLE
Add schwa symbol (ə)

### ISSUE THREAD

**Issue by Krusty27** [florisboard/florisboard#693]
Schwa is an important symbol, especially in italian language, for gender neutral sentences. It would be useful to have it among the 'e' symbols. Can you add it or can I add it personally in any way? Thanks

**Comment by khlsvr** [comment]
"add <insert symbol here> symbol"

Not a hijack of a thread attempt here, but it would be nice to be able to customize the smart bar freely, and even have a chance to add two smartbar rows. The smart phones are getting longer in proportion to their width, and having a taller keyboard is not an issue for many users nowadays anyway.

In particular I would want an ability to add custom buttons there where you could bind an action, including the chance to just input any character you want by pressing the button on the smartbar. For example I want to type the letter `ä` a lot, and I use the finnish locale and the dvorak layout. There is no physical `ä` key on the layout, which is fine, I like the layout. Also I don't want to hold down `a` and slide my finger to the popup, nor I don't want to prioritize "accents` to be able to just long-press `a` to get `ä`, because on every other key I want long press to produce symbols. So solution? If customizing popups dynamically for characters is not technically feasible then just being able to customize the `ä` somewhere for as quick access as just pressing a key, or at most long pressing a key. Like a pinned clipboard item but accessible straight from the smartbar. 

Two clear choices? Being able to customize a button on smartbar for quick inserting a key (or string), or being able to insert a character as a `space bar gesture`. There are many options for space bar gestures, but not an option to just insert character or string.

Someone who wants an access to some exotic character or string that has not been added anywhere yet, like "schwa" or any other character could bind it to smartbar or space bar gesture if such feature existed.

**Comment by patrickgold** [comment]
Above commit adds the requested symbol to the Italian extended popups. Will be available in v0.3.11-beta04!

**Comment by alxlg** [comment]
To make it clear, Italian have not that symbol at all nor the neutral gender like English (it, they etc), it's just a new trend by young people, it could disappear in a year or two, who knows

**Comment by Krusty27** [comment]
@patrickgold uh that was fast, thank you!
