### ISSUE TITLE
When we can test the suggestion system in Spanish? 

### ISSUE THREAD

**Issue by murph2495** [florisboard/florisboard#792]
Hi, guys. I write to ask you if you know when we can try the suggestion system in Spanish and other languages? I understand that this will be implemented in version 4.0, if so. When will the release of that version be installed?. thank you for your time and work

**Comment by Glitchy-Tozier** [comment]
Hi, in #325 you can see the planned timeline. It has been delayed because of a few bugs, but now development should slowly recommence.
I can't tell you any precise dates on when other languages will be implemented, unfortunately, but it's definitely a planned milestone. (personally, I'm waiting for German suggestions.)

Do you have any other questions?
