### ISSUE TITLE
Random crash

### ISSUE THREAD

**Issue by Linuxuser437442** [florisboard/florisboard#856]
While just typing the keyboard suddenly got slow and then crashed on me

**Comment by Glitchy-Tozier** [comment]
Hi and thank you for your bug-report!

Could you please provide additional details?
- What did you do at the time?
- What Version of Florisboard are you using?
- Please, if this happens again, copy the crash-log and paste it here.

**Comment by Glitchy-Tozier** [comment]
Ah, I see!

This issue has been reported a couple of times and is summarized in #677. It is largely fixed by now, and the update should already be available in the Play-Store or should arrive within the next 1-2 days.

If you don't mind, let's close this report to keep the list of issues free of duplicates!
Should this happen again with 0.3.11/0.3.12, make sure to comment in #677! People would be interested to hear!
