### ISSUE TITLE
Rapid-fire deleting is delayed

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#883]
#### Short description
When holding the delete-button to rapid-fire-delete (individual characters), the deletion-process is slow to start and keeps going for half a second after releasing the button.
It seems to lag behind whatever the user is doing.

#### Environment information
- FlorisBoard Version: 0.3.12
- Install Source: Google PlayStore
- Device: Samsung Galaxy S9
- Android: 10

**Comment by patrickgold** [comment]
Thanks for your bug report!

This is because since the layout rework the internal batch level process has been removed and the update method is triggered rapidly again. The advantage of this is that all enabled states of buttons update immediately again. The disadvantage is that it lags behind and needs a bit of optimization to get it smoother. Does this issue  occur with suggestions turned off (or at least is it better) or only if they are turned on?

**Comment by Glitchy-Tozier** [comment]
It's not gone but it's better. (Still annouing though)

**Comment by 0xlne** [comment]
I can confirm this is a serious issue (RedMagic 6/Android 11).
I would be typing a few sentences & suddenly everything will be deleted by backspace with no way of stopping the action.

**Comment by patrickgold** [comment]
@0xlne Later today I will release v0.3.13-beta03. In that a lot of stuff regarding the input logic, rendering performance and state management has changed and (hopefully) improved. Could you try it out (when it is released) and give me feedback if the rapid-fire is still delayed? Thanks in advance!

**Comment by patrickgold** [comment]
@Glitchy-Tozier I will add this issue to the #966 PR as at least on my testing equipment (and also on my emulator which isn't the fastest thing in the world) the rapid-fire delete is now butter-smooth. Hopefully no other lags occur with such rapid-fire gestures in the future, but only feedback from more users will tell.

**Comment by Glitchy-Tozier** [comment]
@patrickgold Perfect!

On-topic question: What suddenly caused this issue?

Off-topic question: I started programming a small app due to personal needs and your comment made me think of a question: My PC sucks and kind of ... dies ... whenever I use the android emulation. Do you know of any tricks to speed it up?
I tried simulating a low-end model instead of a Pixel phone, but in my tests that didn't help much.

**Comment by patrickgold** [comment]
> On-topic question: What suddenly caused this issue?

This issue was there since word suggestions were first introduced, though it got slowly worse and worse as more features got added. v0.3.12 was a pretty bad release in terms of rendering performance and state logic optimization, a lot of this is improved in #966 (especially totally unnecessary redraw operations are not done anymore which makes the rapid-fire much faster).

> My PC sucks and kind of ... dies ... whenever I use the android emulation

Depends on if you are on Windows, Mac or Linux. Generally speaking you want to make sure you don't render the emulated Android OS with the CPU, but use hardware-accelerated GPU rendering and virtualization. On Windows you want to make sure you have Hyper-V and, if your CPU is a Intel one, have HAXM installed ([Microsoft explains it well here](https://docs.microsoft.com/en-us/xamarin/android/get-started/installation/android-emulator/hardware-acceleration?pivots=windows)). Speaking from experience though, Android Studio and its emulator runs better on a PC running a Linux distro (I am on Linux Mint for instance and it feels a lot snappier than it was on Windows, but this may also just be with my hardware configuration).

Additionally you want to make sure you boot your emulator from a snapshot and not doing cold boots, because cold booting an emulator takes a while. This are my "emulator performance" settings for my emulated Pixel 3a:
![image](https://user-images.githubusercontent.com/19412843/120216981-01dab680-c238-11eb-9b90-28cdcd329f99.png)

As you can see here, I use the host GPU for rendering the emulator, I have Multi core CPU enabled as well as quick boot.

Of course, the main performance factor is still CPU power and RAM size. Everything below 8GB will definitely make your PC feel completely sluggish when using Android Studio and the Emulator. Alternatively you can also use an old unused physical phone and connect it via ADB, this is definitely the best option for PCs which cannot really handle the Emulator.

**Comment by Glitchy-Tozier** [comment]
> I am on Linux Mint for instance

Yoooo, same!  :)

Ok, so
1. I have(&had) the same settings as you do.
2. When I now tried it, it now didn't lag, all of a sudden
3. However this intoduced new problems, so
4. I'll stick with building a Linux-Application for now and eventually figure out why java hates me.
