### ISSUE TITLE
Auto capitalise/capitalize proper nouns

### ISSUE THREAD

**Issue by opusforlife2** [florisboard/florisboard#891]
Whether you type out a proper noun or use swipe/glide typing to do it, Floris doesn't capitalise the first letter of the word, forcing the user to do so manually. Floris should automatically capitalise proper nouns stored in the dictionary.

**Comment by patrickgold** [comment]
Thanks for your feature proposal! This is because the dictionary in v0.3.12 does not differentiate between lower case / upper case words etc. In v0.3.13 I will look for some other dictionaries and improve the caps situation with suggestions. As this has been mentioned in several suggestions-related issues though, I will close this issue and use the already existing ones.
