### ISSUE TITLE
Show Dashboard on the top of keyboard when Suggestion in disabled

### ISSUE THREAD

**Issue by hamedsj** [florisboard/florisboard#9]
It will be awsome if We can add a dashboard including "select all", "copy", "cut", "paste", "left arrow", "right arrow" on the top of the keyboard while Suggestion feature is disabled.

like [this Keyboard](https://i.ibb.co/5j7RGbD/photo5877334691135206355.jpg)

**Comment by patrickgold** [comment]
Your proposed feature is in general a mix of the planned clipboard support and the also planned cursor movement support. I will definitely look into it when I'm implementing these two features. Thank you for the idea!

**Comment by patrickgold** [comment]
I've implemented cursor/clipboard related tools in #13, if you have any feedback to the newly added feature, please post it either here or in the PR. Thank you!

**Comment by rancidfrog** [comment]
They clipboard tools are great.
But is there a way to have both suggestions and tools?
Or a quick way to switch from one to another, like  right arrow since there is a left arrow which takes you to the tab with emojis settings...
As both are used often

**Comment by patrickgold** [comment]
@rancidfrog I see suggestions like this quite a lot (but more commonly with the number row). I am unsure how to handle it yet and what could be useful, what not. The Smartbar will get a huge overhaul in the course of the next week (due to experimenting with adding proper suggestions). I will see what I'll come up with then.
