### ISSUE TITLE
Dual number rows when entering password

### ISSUE THREAD

**Issue by pokegamer5547** [florisboard/florisboard#905]
When entering password on a website, or apps like Aegis or Keepass DX. Switching to number row shows two number rows.
Edit: Want to mention that "number row" option is also disabled in settings, enabling that option fixes this. Using 0.3.13 beta 01.
![IMG_20210518_161136](https://user-images.githubusercontent.com/65234485/118637815-d39ab700-b7f3-11eb-970f-d7257d24ad11.jpg)

**Comment by Glitchy-Tozier** [comment]
1. I agree that there probably only should be one number-row.
2. What a pretty theme you use!  :)

**Comment by pokegamer5547** [comment]
>     2. What a pretty theme you use!  :)

Thanks! :) I made it when i first time installed Florisboard and messing the theme settings.So it's my first ever theme and favourite too!

**Comment by patrickgold** [comment]
Above commit fixes quite some nasty bugs with the Smartbar number row while in a password field with the additional character number row enabled. Will be released with v0.3.13-beta02 in the next few days.

**Comment by ostrya** [comment]
The reason for this bug is that the number row is always shown in the symbol keyboard regardless of the "number row enabled" setting. On the other hand, the number row in the smart bar is shown whenever the keyboard is in a password context and the "number row enabled" setting is off (to ease password typing, I believe). On the other hand, if the number row is enabled, the smart bar is always hidden in password mode, regardless of the "enable smart bar" setting and the currently shown keyboard.

The question is what the default behavior should be. I feel the number row should always be included in the symbol keyboard (and other code also relies on this at the moment). So probably the most consistent option would be to hide the smart bar in password mode when the symbol keyboard is selected.

**Comment by pokegamer5547** [comment]
I have tested out latest beta and it's still showing up two nunber rows in v0.3.13-beta02 when using Aegis, KeePass DX and in Firefox when entering password.

**Comment by patrickgold** [comment]
Omg I just realized that I fixed a double-number row bug you didn't even mentioned (previously on a password field there was both a number row and the Smartbar number row when the character number row was enabled). The screenshot you provided is within the symbols layout, I see. Reopening this issue :)

**Comment by pokegamer5547** [comment]
> Omg I just realized that I fixed a double-number row bug you didn't even mentioned (previously on a password field there was both a number row and the Smartbar number row when the character number row was enabled). The screenshot you provided is within the symbols layout, I see. Reopening this issue :)

Oof 😂 so that's why it didn't fixed for me, it's alright :) it's not a serious bug and don't really need immediate action

**Comment by lm41** [comment]
I cannot reproduce this. Can anybody confirm that this is still an issue with the latest beta version?

**Comment by pokegamer5547** [comment]
> I cannot reproduce this. Can anybody confirm that this is still an issue with the latest beta version?

It seems it's no longer happening anymore as of current latest release i'm testing with. Closing the issue.
