### ISSUE TITLE
Wrong popup placed as default in Greek layout

### ISSUE THREAD

**Issue by tsiflimagas** [florisboard/florisboard#912]
#### Short description
After v0.3.13-beta01 update the default placed popup for "υ" and "ι" letters (they're the only ones to have multiple accents) has changed on Greek layout (for the respective capitals too). Probably the same thing happens on other layouts too, but I don't know how they're supposed to be so as to check :/

Here's v0.3.13-beta01
![Screenshot_20210519-031643_Bromite](https://user-images.githubusercontent.com/45879751/118738884-c364f500-b850-11eb-9eeb-cf43336761f8.png)

And here's v0.3.12 (same case for "ι")
![Screenshot_20210519-031716_Bromite](https://user-images.githubusercontent.com/45879751/118739331-e348e880-b851-11eb-9884-9ddee180398c.png)

#### Environment information
- FlorisBoard Version: v0.3.13-beta01
- Install Source: GitHub
- Device: Xiaomi Redmi Note 8
- Android: 11, custom rom

**Comment by patrickgold** [comment]
Thanks for your bug report! This is because the popup logic has pretty much changed because of the support for multiple symbol hints etc.

Are there some popups which must be the first popup? If so, I (or you if you want) can modify the [Greek extended popup mapping](https://github.com/florisboard/florisboard/blob/master/app/src/main/assets/ime/text/characters/extended_popups/el.json) and set the corresponding letters as the default one.

**Comment by tsiflimagas** [comment]
@patrickgold I can totally do that! Thank you for letting me know about it!
