### ISSUE TITLE
FlorisBoard Beta (0.3.13-beta01) word suggestions in smartbar not displayed

### ISSUE THREAD

**Issue by hakerdefo** [florisboard/florisboard#941]
- FlorisBoard Version: 0.3.13-beta01
- Install Source: IzzyOnDroid
- Device: Nokia 3
- Android: Pie 9.0

After updating to 0.3.13-beta01 word suggestions have stopped appearing on smartbar. Before this update they were working as they should.

**Comment by patrickgold** [comment]
This is intended (and stated in the changelog) as I've began moving some stuff to C++ and the old suggestions logic got kicked out. Suggestions will return in future beta versions. I will close this issue as it's not really a bug.

**Comment by hakerdefo** [comment]
My bad! It's written as clear daylight in the changelog yet I missed it!

> Important: this release is the beginning for the suggestions rework. In this release the suggestions
bar will only show user dictionary suggestions or inline suggestions from autofill services.

Sorry for the incorrect reporting. Hope this feature will return soon.
Thanks.

**Comment by dessalines** [comment]
Just tested beta 47, suggestions still don't work.

**Comment by gammerboy** [comment]
I was wondering for a while if something was wrong with my phone and couldn't find any open issue mentioning broken suggestion. Just out of curiosity removed the is:open tag from search and this came up. Had missed looking up the v0.3.13 beta 01 changelog too.

@patrickgold can a not working heading added to the change log along with the improvements, added headings along with each release/beta-release so that it would be easier to track if a major feature is working / broken in each release. Just thinking it would help people find such intended rework of features easier. Thank you :).

**Comment by Gottarocket** [comment]
Any update on this as its an must have option as typos are common now 😬

**Comment by slmb3** [comment]
@Gottarocket use the non-beta version in the meantime https://f-droid.org/packages/dev.patrickgold.florisboard/

**Comment by moriel5** [comment]
Interestingly, glide typing seems to be working here, does it not rely on suggestions?

**Comment by patrickgold** [comment]
> Interestingly, glide typing seems to be working here, does it not rely on suggestions?

Yesn't. Glide typing is intended to rely on suggestions once these are properly implemented, in the meantime there's a temporary copy of the most frequent used English words kinda hardcoded (in a JSON file) so glide typing does not break down.
