### ISSUE TITLE
Suggestion doesnt  display

### ISSUE THREAD

**Issue by Gottarocket** [florisboard/florisboard#952]
Sorry if its mentioned I searched but couldnt find on my end I cant find suggestions i believe its due to dark background as the column separating bar appears in grey but no text prediction was turned off and on same issue

**Comment by Glitchy-Tozier** [comment]
Hi, could you share screenshots and post your version information?

**Comment by just-Nob** [comment]
Hi @Gottarocket ,

if you think that's because of the dark design, have you tried to change it to a light one?
Is it still there if you do?

Anyway, I have another suspicion, because I'm also facing the poblem with suggestions not being diesplayd, but in my case there seems to be another reason for it. Here it goes!

It's quite simple and quickly explained: When typing using glide typing, no suggestions were displayed. If typing character by character, suggestions are working as expected. :-)

Detected on v0.3.13-beta02, taken from F-Droid.

**Comment by just-Nob** [comment]
@Gottarocket , could you please confirm if my error description applies to your problem?
If not, I need to open a separate issue to ensure that my problem will be noticed.

**Comment by just-Nob** [comment]
Ok, seems that the issue described by me is already targeted by issue #948.
Sorry for that.

Anyway, did you have that issue in view?

**Comment by Gottarocket** [comment]
Yes can you change your options on dynamic option on settings under typing and check also please add an ss so I cn check if its similar an video perhaps since you mentioned it happened when you used glid feature

**Comment by just-Nob** [comment]
Thanks for your quick answer.

As far as I understand it, this issue actually **is** a double of issue #948.
If you think it's not, then it would be up to you to take a video showing your problem more precisely.

Issue #948 may be a little more comprehensive as my description above. But I think that the sentence "Its also not present in suggestions." that can be found in that issue's descrition reflects the problem that I found.

**Comment by patrickgold** [comment]
Thanks for your bug report! This issue is known and fully intended for this and the next beta release, see #941. Closing this issue as a duplicate.

**Comment by Gottarocket** [comment]
Thanks its solved now
