### ISSUE TITLE
Emoji style fancy.. option to have standard ?

### ISSUE THREAD

**Issue by Docop2** [florisboard/florisboard#958]
Hi
 So the emoji are nice and are very good looking. But when you wrote sms, using just 1 emoji end up eating like 3 sms to send it. It's quite a lot. Normal emoji with less details or something could be usefull to have. Or best, just have an option to choose : enhanced emoji or standard blend one. That could be quite usefull. to send text sms with 1 emoji in 1 normal sms of 128 car long and not being a 4 sms sended because of the size of the fancy emo.
thanks great project

**Comment by just-Nob** [comment]
I guess that indeed this is not a problem of FlorisBoard, but the way emojis are encoded when you're sending an SMS.
If you take an emoji from FlorisBoard's "usual" emoji selection (see picture below), then probably a picture is inserted, and the SMS will become an MMS - or a lot of binary stuff is inserted into the SMS, trying to encode the emoji's picture (the exact behaviour will probably depend on your SMS app).
![grafik](https://user-images.githubusercontent.com/25401767/120073899-a2936f80-c09a-11eb-981d-7b3cd9056113.png)

As far as I know, many SMS apps offer a set of emojis for inserting, but they will be encoded by "standard ASCII smileys" like :-), :-(, ;-) etc., i.e. a standard friendly looking emoji ![grafik](https://user-images.githubusercontent.com/25401767/120074220-1b46fb80-c09c-11eb-81ea-25945b66b816.png) will be endod by these three characters;
:-)

I'm not sure, but I guess that the feature that you like to have will be available in some later version of Florisboard by choosing the ";-)" section rigt near the "standard" emojis:
![grafik](https://user-images.githubusercontent.com/25401767/120073916-b343e580-c09a-11eb-80d1-ebde8001a56e.png)
Although there's no "yet not implemented" hint, I guess this is not yet implemented.  ;-)

**Comment by Docop2** [comment]
oh yeah indeed. That could be it.

**Comment by kj7rrv** [comment]
Related to #950?

**Comment by patrickgold** [comment]
Thanks for your issue! Emojis were and are always a mess, because they literally invented an emoji for everything and this requires quite an effort to encode properly. FlorisBoard uses the official encoding table from Unicode and inserts the code points (4-12 bytes per emoji) into the target app editor. These are text bytes, not pictures. Of course, what the SMS app does with this input is not in the hand of the keyboard, but using emojis in an SMS can thus lead to easily requiring multiple SMSes because of the Unicode formatting and because your carrier probably counts 1 byte as one letter (pretty stupid IMO because many non-Latin languages have multiple bytes per character). I suggest you use :) ;) etc., these are more space-reserving and shouldn't eat so fast on the limit.

> I'm not sure, but I guess that the feature that you like to have will be available in some later version of Florisboard by choosing the ";-)" section rigt near the "standard" emojis:

Yes, that's a bug, normally there should be some presets for the asciimojis.

There's not really a thing I can do here, so I will close this issue.
