### ISSUE TITLE
Transparent or blurred background

### ISSUE THREAD

**Issue by praveenchandranpk** [florisboard/florisboard#959]
Is it possible to have a transparant or blurred keyboard? I have never seen one on android.

**Comment by just-Nob** [comment]
Nice idea, although I have never missed such a keyboard so far.
Where have you already seen such a keyboard, just to have an example?

**Comment by praveenchandranpk** [comment]
> Nice idea, although I have never missed such a keyboard so far.
> Where have you already seen such a keyboard, just to have an example?

I have never seen one on android. But the default ios keyboard has that feature.

**Comment by patrickgold** [comment]
> Is it possible to have a transparant or blurred keyboard? I have never seen one on android.

It is possible, but no keyboard does it because the target app does not re-render the area under the keyboard to save on performance, even if the keyboard background is transparent. Thus having a transparent keyboard you see some out-of-date or weird UI. With FlorisBoard's customization of themes you can have a transparent background though if you really want, just create a custom theme and set the keyboard background color to a transparent one.

**Comment by praveenchandranpk** [comment]
Thanks!
